// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i24cN7Yo+iuc3gewPbvVspyZwYwAY44i24lObEtHkjM4O/LdoarY3RxVkxWSJbkT",
	"GLj/cP/wfskBFx/FqmI9WmpJjlN7AxOri8/FxcX1Xr9NEr7KOSNMycn+bxOZLMkKwz8PLiXPCkVOsFrq",
	"v1MiE0FzRTmb7E9OSS6I1N0QZgjbtmhOM4JyrJazyXSSC54ToSiB8fLoOOdLUvbWTZDiCJtxOENqSZBc",
	"S0VWM/SeK4LUEiuE2RqRT1Qqyham6Q3NMnRJEL8m4kZQpQjTKyCf8CrPyGR/snuNxW7GF7s4z2cZX0ym",
	"E7XO9RepBGWLyefP/hd++W+SqMnn6eQgz8/ht9iydWvE57BGnOcZTbD+CvOyYjXZ/8kAV5LJdPJLgdOM",
	"qMnH+rzTyacd3XznGguGVxpWP7l5D313+8P/dqOYtbkpDzlThCm9TJxlx/PJ/k+/Tf6HIPPJ/uQ/dssT",
	"3rXHu/uGZsR1+jztbntKMqzotcED3ViQXwoqSKoXCof6sQG52vpes+sfsTBYUMEJUn7AaUp1W5ydVJrU",
	"TmlaO4jX7JoKzlaEKXSNBcWXGUFXZL1zjbNCYxQVcooo0+siKUoLPQwSBVN0RWZIn+MVWSPMUmR6EJws",
	"0aqQSqPTJVE3hDC0Bw1e/PUblCyxwIkiQs4mjW23oJADw4ng1zQl4iwnyfCzisBRn0IVkLhE1J6xoNnn",
	"6UTjWst1LCdEupWHxt7////+f1UYoIyzxRRJhYVCN1QtEUYZUYoIxAVixeqSiCnALuFMYcoQ4+hmSRWR",
	"OU7IbNAt/G3CGRkAqKMVXpA2cPdh+RHLKGvv/fHzx+6zPVNYFTJOLMw3TSowkpQtsiqMLZlLyTU1IHHU",
	"40SQHFsicaZBbP55WjBm/vVaCC4m08kHdsX4DZtMJ5piZESRdDihqe4gnLPxMVhE41u5qsYnt8zGh3Ld",
	"jU/BRqqA/pFnhcHc8vpUwf2KzCkjEmHA3hRdQw9USJKiyzU8V1VqXb1K8YvxgdFfCmLug6X54bga9ymL",
	"PQVN/A7pJ0z28Y44b0DSQNgY3OokqLp1syPZ3P1bKhXgb4C2trHeI1VkJQfQntoZlncdC4HXvfTTdDP4",
	"0X3LtnLk7xtnHTlPfZxzIghLSIxJsp80U2PueJ7xNUnR8eHRjoZRRjFTiOpT1BRTX685ThS6xMmVfqg6",
	"547hUrieHpIlz4rVCov1QNKVZSEQZTvZ+p7gTC3Xk+nkFVkInJI0Qqo2Jk/V1ZZztDYJJm9tE6FM1QZ+",
	"uRp0hVoecjaniyac9Df9xs3pooleuFDLY7HAjP5qpihH6bwwLd0+T2HE+IHBQjRko7iq+304fdvS7cPp",
	"234s81OXo01bdxjFwHZoRNYkNPdJUsTDHhbShWi5z4RpNjA1Q85xkanJ/hxnktS5x6M5UqIgUySLPOdC",
	"oTkX6Cg9Qbmhk/V5qUR27ABQl5xnBLMGpNwqYkD4FqskIg3Bz3oWzBDJCHC1lKFL+FmSXwp9r5v7zeiK",
	"qjgzt8Kf6KpYWV5M05iciIQwBRRnbq+v1ASqyFOsCLLPGMyppxr2EJ34UeH1WlGmp53s7/nNU6bIgggj",
	"HEiSkURx0XcH3uJLkp25xrpjkSREyvOlIHLJs7RvgHBdn9sO4sxCtuVA3GeUWs5CwyezTyLAyQDwkiDy",
	"iSSFxlfKOs5Lts53UB3XzAhy0fCH1uDW56k+hCPTYa/+0k719caKLNZ9o53yLOOFOnPN61jux4mh+aHe",
	"81xTVnJGF5o/PNVblxFkbW2KRKBqQML+qC+q5qYXjKQoKfuiueArOKDDgwglzumPREiYsQH6kyP7rXLO",
	"1+Y3kiIDEcMRUFkuy3Lxc31pzdZn6IwI3RHJJS8ykH6uidBbSfiC0V/9aNJxBprKSX3ZFREMZ0YYNaLT",
	"Cq+RIHpcVLBgBGgiZ+gdF/rWzvk+WiqVy/3d3QVVs6u/yxnl+khXBaNqvatFMEEvC8WF3E3JNcl2JV3s",
	"YJFogSxRhSC7OKc7sFhmcG6V/ocgkhciITL6olxRljZh+QNlKZAxZFpa2dqDzLE2p6/PzpGbwIDVQDA4",
	"9BKYGhCUzYkwLf1JE5bmnDIFfyQZ1VRTFpcrqqTDFw3nGTrEjHEQZQ2tS2foiKFDvCLZIZbk3kGpoSd3",
	"NMjiwFwRhVOscN+dPAYYvSMKw022vHxXj9bbZYXjifRc9e2GMd0bzEJ53yyqBJu0K9+IbmhBZAPaAXIL",
	"4KEjq61NR2Jx/8TCP19x6bLzbAY9fe3vzefmCziSrkcgXfqsDeHajFSY49+IVjgdR/V8/yVwnhMtavOC",
	"pQijQhKxkwgCYsbh2ekUrXhKMs37M3RVXBLBiCISUQ7AxDmdBfyGnF3vzTqXEBFPPuXUiC5nJOEslTHN",
	"AfQ3GmtPM65xRlOq1sD9AMaUE+tp5lyssDK89jcvJk3Wezohn5TAXfp2f88aR1y/PzVFvB4YYWWQi0in",
	"OdHgNVYbB2NgzjScc54XRrq7XMOvBydHSMKN0bCH9nrnmq7R1apQWp6KqN0NIkW5ynOQZCT52192CEu4",
	"luhOXr8r//3D4dl/7D3Xy5mhd46TXxKkX6aZ5zUpyYCjxyE+dDGshipUjuRyrUjs4gALK95HNVBHLDVI",
	"BmsSHidMH0PwgVT9UuCMzilJQUEZvaAFjRC7D0evHuCcgkVIvIjpFz/A7wB1vQ2gvgTehCuyRqZXsH8r",
	"olIpiyr3X3koehFYb7lf9fcAgKmRQofNFeTYjPS16EhLhMJ5Lvg1znZTwijOdueYZoUgSHqFn99lYL6R",
	"LXBHdF4aZWWT4gVN43fUDtmU56Yl4BDXMriH+aDbpcmrEZ8jXKP/ZhSb+mR5eNNm6AfGbxhKgoaCoAMA",
	"HUmn6BVhVP9XQ+gNplYtNIxTcWNGteAhNgRbiOKAH6h9g+XxpURhmkl4QDgjCOsrp9xxJ4UQwIEofaaO",
	"d9VIfRqQtJruCUt1LjCTMNM5bbMq6nZI0RUxM/mlKd+XpIYv0uuyaKg4woyrJRGV09YM0I4eK86JSE0v",
	"mqv4vlhhhgTBKWCTbYeouROar3PQwZe8UHbFfnlRgsYv4bqn3xFGzDsd3/3MsTKzhW9piEoVGjdYAuXT",
	"b1aKitxMG77rf/tL9F0XBMuooIKeXgpK5s+QaVGyDm7OJ3LQTgcKiG5UJxC6kQZ2M9bp2g1QRt1sVzCN",
	"oZwHQHn+nZel34hUgdEUkJLP0Tloi9+ALhlZ40Bo+9DfJ9MJNNjY2lFbnR2r9qsbuvZzaKioQrOJj9Zv",
	"pcQ6GkoSwW4cpZtMJ+cn734kAngMYy9xHwwNhD1rAthsCvpaepmR+h+OppxgIaHp2Zol8I8fNZ+rWxjd",
	"4xE7EXwhiNSH/0GLP9YmnpPENX1XZIrmGTm+YURIWNc1TcgroiUfKrVcoTsNO4jXTPAsWxGm7Hsa7Lfx",
	"rbrd1ic5GKK1jYdlawsP5NYW1eWckpxLqrhYR0GvId76oXE+4Ud/Vm8yQpQ7BfgjdmrmNIKzMz+EJ2h+",
	"GXqOBs3ndFG3aA8zV3xHVaR7n5PID577PyOJIOoWHia3mPV7pfJYN4BBXrhTeceZPuimc1H1vV6ZZv1u",
	"baVugyPbqZ91DUePujV0e5o1d2J2KTh7/SnXuBRndARniPgGyLyX8NTpsdMiA60NXRE5u2B6k7YFlejn",
	"PyP7/z/vox30jjItve6jn//8M1pZifD5zl//MUM76HteiManF9/oT6/wWgPtHWdqWW2xt/PNnm4R/bT3",
	"Iuj8L0Ku6qP/bXbBzoxxkqRIHyRWXC9iRzfc90Kr5r6NpuopmS1mUxiGMrTUS/bjkWsi1vDbMz3vzzs/",
	"76NTzBZlr+c7f/8ZALf3Ah2802f/d3TwzrSe/ryPQFfnGu9N917Y1lIBF7z3Qi3RCmBo+uz+vI/OFMnL",
	"Ze26PmYx9R5nxkGqupe/lyDR7/Lfgy4X7LVx8tSQQ893/j7d+9vOi2/skUZZmcNCKr4yhOWIzXmXOqTO",
	"TYG2yKh8U5TAQMheMHsA0Snr4m4wCGUGGUFQBMaz6lbRYGLMwpuLM79XzWX5ci1pgrNgvFHJPVrERovY",
	"bsmADJdubJ9b2Lo+tt7jhudj0y0vrqOqibOhZ2K3CyLISuk6/vo7P5G50xloNLtZ0mQJug/oiQZ5Oupp",
	"wDE4Qkff+1lcG+QkaS+gxkcPRN5hZxb30f08bXd2LGVA28T7EcIlq63rdr6PdfG4RffjXfr0eQUA9Zsf",
	"hFdVl7bYqyZNA4c/S/Cuqzl8Rjz+qmhK7VPaiabha2fULY7ygRIidDDdikKi29+x6czSA1XDh7cB8jDQ",
	"n5VaBAOvVu9AQVhKBElbn+FT28A9vK3j9mmVq/N0blLyrJXDsJ9DRsMqS+DnhDNGEqtX8Icdc4ICZv3o",
	"VZwQ2c/o6FWosqrNEEcM0/Nd8HTU8N3zen4WR6gdadPrtuaHl5VIkgQzeC2l0RaDcxbO6K9GrelDgohY",
	"UYazqV+zcQ/T3aaIqKTtuHB6zLL1ZB+8EquoWdvVNABg+1GGcnMTEG4wy3dih1JpVdr2+vDGGSosFkQN",
	"ezbDpZxDv7iyzww5bEvBOE0y7o1J5rJIPUNjayuiljytXqlQBfaBEVD4gIIrUVysT4kcHMfVteJg5K5m",
	"1Vk9FI70OyioWh8uSXLVRpDa29Zvb5VkUdcDJboLyonQN8LYxG/5BuxE34BS4qnPaVZ0B9Lfvvnb0f7W",
	"kXq0yBsAs8Q6FxjzgUkn/Yc6Vq/i2wQPYxsoZ+pqE66hvZ1fXXuTct1NsLbq5C1z0oaijbub1yR4mCXV",
	"Uoda3x5pwIFpUxanRG9gb8pF9zA3urWHVfN9pCvNCa5yt/fa4NfQs+RRhxnObnWrbGCYOSLHWqt8dRc4",
	"3/piNhcz+Gq2PgCBMt3jd/x63uoq1q5Fy5bablbPHW5e3/LavcVSnRHC2h4N973+UACqSf1BhViIW+9f",
	"1jpR0yxs+Q9jBSXMuVVoyZDW/Gk6ULmGP34B7Rj0ls5Jsk4y8j3nVw5xHAZ8S+ZchLaLg7kiIvjbNDgl",
	"l5yHLcofNsGMylIaU0fa1FfTOky4wLZxgjU3gXMrsSdzvbcgMNbVo+Xg2+IWanu9HaMQG6SNEIVJBGIQ",
	"a3IExgBpqUHVKlb9ZUOSVFt1najUPldWEfkeW1pPsyp5ijp6l9+qXt3mdzmqtx/dhzs4iUGaMWvMGN2z",
	"vzT37OnEKgWHnaDjurbn1x3zB3hFFOTxeGUctZqqcqNS7Ddum3agWUqpbrSiDCsuUF6InEuDwI72dq2k",
	"SWI1tLFKlpQtwB2i47LM9XfQ3EvjDAYda4zoUH/WGtwDSDQWNBTcp0Ty7LoD3Fgaj01oHoe42aNriLBE",
	"XDdGT1mRZYjOEePml2d6s/pH/ew7DVjEkPpAB+z2Hj3gXJBrygv5bpODtmfs+mZra9NOb3ngYA/gWdHu",
	"6fU9v3GK03lGEwWMtbAbCwFgjO6wm8l08p67f8G+XpGWjCKdKFdbWzvKHct4oEb4FZlPl/aJNjpCdHzm",
	"VcOt+qhV1BX0vDKISb9gDGhiWBS8GbdzU7dhlo/PBm/hx6oxwG0j/mbrL6/oojVEIoVv9bGM+wWSS/zi",
	"r3/bx89ns9mzoaCpTtoBKLhsS5ofLjFbPA5lr68heuUZuemgcozcWLpm6J2nboKs+DVJhxE3Rxo6JnJN",
	"4rMxzsiQqdovbvtJee+/jRDbM5N9arokL4ZxGtV1OJVTSuXVXfqvyIoP5XVaRsggbuz2Q9T9/vNi4tdl",
	"Nzj0dLqviay495nzqt6LMr3Kv7Cw8tuhoIomOLt1MpfYQsNcMc2v5eSxr8GCYp/dImPfQm9p/71YkSA7",
	"QdwhzGYRwWxtnSuriqYwWcXHeq48CCMLPn+cxoP+tIQoYDk+O4cJB+AMwRTIZc/Q0uIuFzZAzf06QwcK",
	"ZQRrgs5I2dilcXO5TSoJEn+rrX5/QsrMei9zwdMCLK5TRYl4OReQPDA1RCu8xtVNxlwN3HLMLpXQfEmY",
	"UCPISGKhYLSA1O5TztAH6cL09JttfTmxRKV/bg0k0nkSXnjZY6bx8qWZbG9q1Uf5Ekvyp5cnhKWULS4m",
	"z1qU8xVIbXePMPiwPVaRIdjjFVnvGbP13vSKrF/8yfzxIr6hz11EBS6FzDmTpPdW1LHZdDPSNGzTxNh4",
	"BUGAfAYKqZUlJ/vffG66SVRbtLsUeeBqbvuGCIJs0ph5kWVrC/A05lPU8JioTNlOfLsY2Br7ijs8MUtP",
	"lWEZ2OxFFrfKwVZzQW/IFklLVia3EPP9FmuIesDHppc8ix30eXCPcKLodekYYj0iNtU+OX+XaIxzVY25",
	"sacDBIkNXIeVhKxgB1xThLropVUecOtzX02KNRwGNa/7GBRMBt60xVHHfHRGGlmLF6hFH2jB8gQrRQST",
	"XemPjCYkty0rm2lQW+Mx7tZRMGp0KlOTkZQL+C8vFJLFfE4/TZHJHbQkWbYj1TojaJHxSzcZrB9mxwtM",
	"mVQuLDJbo4zjlJgpYE0r/OktYQu1nOy/+OvfphM7xGR/8v/89HznH3jn14Od/9q/uNj579kF/N9PFxcf",
	"/3RxsXNx8eeLi39+/M+n/3NYu2f/fHpxMfvJNIx9/h+xh6o/u6LRVp7wjCYDmd8PQQ+Dru3vR7dbStMR",
	"JW7rkUFiR0s8ke27wmBJp5nxGE1UgbMyevWutNYK5SHJLc1MG9CXpotv5I7hpqPixqPXHD2Hxz/7MwA4",
	"Gldc5/Sp4RgNDsYxndUtY57D92YQwS69MMEtwxq8b+W84PwttmOkRk/fH5+/3jeGBB8ZQiViXCFBVCFY",
	"JV/As4FWbS1SLfjOvyVnO3TBuLCyvV68s6ndysa54Qvl+1TeqE0l3o3tCw3MNuTehe8MGKBs7+leugnJ",
	"S1vcU4IrVllV9UpP4jc8BGOIx/4+wNmU6y2hFh57B2d6a8/vANOXWKQ3WBAwTpoQNM3Jm72iirlw+x7h",
	"dg0uIcA2fMIjoLmdoX+jBLpx96JjiAqN58oNHTZOuJZk0uP5vOJ/dHCDqYLgX+sUbSLDQdt/ggu5oQ9A",
	"ZUPB0hrfgtVGvlZVL5VPTSeUyufKNiPf614JlY8xYESa1eFTHmeFpAyLCDzOnSe5uQ1BAiTyKeeypPV4",
	"QZiaXbDXOFlCWpuECwEycmoSXZQMvLkW1jEgwTm+pBlV69kF648tNJuo3KqEZ5kpf+AN262MkV5kq8eE",
	"fgsPFlBqwTSJJxkObNUtYwQtNO9hglstnBqRj+XIGnVi8QLfcq7Q0atNhjKhm0Oej0a0qH4vHRE00I7v",
	"8thTyjNHKQcur25CDwHqodBcxbR6fO10q8HD9zjP59ASbCorzPCi1ONYdwcosZFkRaq/3CwJc787f5hL",
	"glJ+w6z8pN8Rm3In4q9r252ZyO1epsZsxrf2j/tt+3/uAVt6K8ueWdNWfeDC59Hmbt7i81jZ7O2ex+YQ",
	"G3jBlQDzLnD5OX+FIc/TcaGO5/bfgevjbewRlUUGU0S+hrNGO9d8MKtfGyaHUMzrYcucStNFJ4HVzwsT",
	"cOHmxLgilDVGwHjfKfuWmNz22A3IPOQzrP/WeIsO0KUg+Erf6M6dXK7RRbiui0nTn7NELlnnab+Axds1",
	"dS9ccYWzFrOc/hQE38ZmGpgJylK/Lwk6Vnrpgk49CgxANY0ga/38axuOUiMqr3qzpGycmGT6hWVWiT7g",
	"Vm0FL7cZAN5uKq9MVsVNyrSlVIChae3rtDnNs3W2CMbs3ktH1bBXVIoCZv22SG1sYU15WGtRzcpPrklm",
	"y5XwG5LqZdnWhkwKk5wIUcDT3GYoaoJhIXiRf7tuVw4a49sVWQPzbmO6EHSDqnTOMamc/xKWW9GWBfri",
	"pz8d7PwX3vn1+c4/Pv604//937uzj39+9s/g4wBNLyimPzB8jan1AomWhjA1GgKq484I+Z7+UrvCaQZ8",
	"oPvuKPEAXw96pq9VppijgjXn9ee40fxRHq4IE/RZwjZ5rilI++J89l23Dp+dwEQ4K44SW6nKFJPzHUrG",
	"12U1BedHjCAhF722wUdE3x479uUaYaNmLBhVM1Tm/fE/QgbKffSzNCl0pMkfPEU/r8wPJiuO/mFpfoD8",
	"P4DeAar9c/+nvZ1/fLy4SP/87J8XF+lPcrWM49VrlnDN1A8JsSW2raFzECENhAErXPOdD7m6PMNUi7Um",
	"S+/gBG1mqhPb2f39rR3kc5inrawvU68S41rsWN1tH2dcjnlmOzRrvjTGjL1IjSRyTdg2mnTUwbC5XDU2",
	"mgV0mj7GiIgx4c8fMOFP40Jtlvun2X27JS9ack7GBIbWpmWe37jGwBOKwHqHSpLVnucBu+SVHRmlb5ZE",
	"LYkIEyijJZbokhCG3ACxslnWoeouVWAPXLpwMxKoU/M8W5d191qyqTUOz+5zoxMKZK1B4kT7UTf5+J5J",
	"+048sJ3f9ewPWnzHgTfByiaJCk//BsvKwQ8LQ3c9vm3LUFVNdKXbDhCfglGn4ZYiUsh0wyO4hQNDBPD+",
	"gGZRXIvHQ0abVUMjG01GluDRgySjZzLIhaLJOI6Rk19rYZs4w9JPA8DjlBpXU9/QUJ9G2yfSxUGBW08k",
	"LEO2BKLEyqiEFSGkyUodviuRR7zqJTY89+J0Atr0077caefwHHXmTwOUtemhZv+WnKGn3Bp1O9y/t8qt",
	"uDoAzoXohtpiu5aBodI7HS0JQ/oOBQ8IlTH2qoXD0ec5DNlarFwtDTd7BQc9SiX7eytmKnCC66s+EuJy",
	"swTJbOPCIs0yGuQONH9rpUKa6ouO07VNuhjMJb+xCjBNguHWg8ctRm8yulgqdKhJMs9CZA1SuTSLJGuy",
	"nHgl3UaamINCQc3TQAFT0B33CsWP/cPpW3c6H47KWwhGdFRI48qcC/eK/e9TpFEEuI+MsiuTxBrmc29n",
	"h8PBbVVMbZqmGrzKCVphMAglAI79aOHqXZdFgewbX11WBWlMydZboIYZeie4kjvxxI6H0DAojfAKK1wu",
	"M7zmoJUE0o/d0vX4aE4ziLZB52/P4hffLOaKrDsX8QNZbzT5FVn3zV2/7C1QaS5x0MEPJwkDKIPL0Kmv",
	"Bb/loQf70kjFBVWtIC/bHrim7dAPuRQ/MqrU9Gu7wLGoXMMJ61cYiEeaCiK990fvxtFTx9QuuVRatt3P",
	"uVAD4qw7AOQXGz15zf1GjvnaCKOBjtn6EZBr4xiOFeIJeIH7CmzG6S1CzOORcXXxHUqrgRnDwMKQYEEX",
	"C+DXQI7QkxvTipFXgDeCKEYyp5+M1YRQ0Dzp4fbRUzB7gAON/kE+C2awX3Gh+ArqtrmglTinNwrG2xaM",
	"0zK8v/MV1CO6VADg4H8NOSuM1neYbviUzImAKuujSLxtkbilwtqBuXdlpteaAFpPNKvhmNtqaFu0BrTX",
	"QpNLLtQUrXCypIyU67THD/SnmmqkVjXNkKPAfOlcQw5NbcigStKhrf7ocze6Dx+8L3/1l0ZDl3il9ks4",
	"ZjPgsOXnWo/Dkw+N8PnDkw/1gPvDkw/v9dNeNnoH+Qgafc3P9e7m19oIr6i8avTXP9Z7699qfYNYp6qP",
	"efCh4ZoefKunG3hFpWVVwuyaESf1ms94/WefLCj4UBv1ECLmVcPD0P7e9C30HaJehf48N6pV5mTjGja0",
	"pLbqTgrVUcRL/3LEru1vR/aROsfyyk8c/nhCxAoziLAM7kBL4TL38xHD1Q+W2qdlk/KiNYuUlcsLa5aV",
	"tzj89Uxh0fzVL7UygHUGqf/+LVbJ8hWVucn4VPtqoUYyB/dG13DcsAzbob7gKjixQZXdGrArP0WLvekf",
	"KVs0CFSlEFz9R9/aeKefEqm4aEmuY3oO4grOTNOgsGS7o13AQB6b+o2GnkyRpTUhJfekxtGhj/02pW7N",
	"bpVpiZSonPrSlmZTU8s4t7LtQXakCPe+Yz2NElfIdKoftgLe+bTMIWL5+XUOUlclSZIJ0c5zG+reSR06",
	"9bTdaft6CMsGI9cz1LWlleoJa2xJQtV5EVtGbO/RMWpAGYYOW3aJj7vRQnvWWKNPAwas9oiPagnEgNFM",
	"y/gojjgPGMY2LceJvEytxRvrLeOjNJ+yAQM2OpVjdz1rrc7KrV3CcStvSDemRBs3x+pdV6VZIN25KGlT",
	"BD/MRvZ5OrCeZ+vgg6KaW67/sN7dpO42Y9SJWn9l0Tbk3KRnKxYOLdsZRY/+zr3Y2jdExxXfpOtmm+6k",
	"npt0biHmGw9xp0XEyfXnjxulCQQepMVPxX2q+aZcg+ZkdEh5dIcUfxDDvFBAhTx6nny1nieBoBUVsPwq",
	"jMoMrhlke9MSZVNZVrPsuM79BoIN5+kxmPh5Y3t+QzOncmnbM3w0DgxzGitokXT1h0AHpMgnhZ5+OH+z",
	"83cwTJiwh9I2VU4CMXR2mpj7gW7n4h76rcpBGEc0OkZvv71inv7qa+S1BEu1pP+mGXkiTVzUNAiFsSYb",
	"iIhxmZdZsSKCJujo1Qy9MhE6QHgvJoJzdTGJ3xKeks6pcyKsDhTptjP0f3gBxMMsxoTir/RVn+MVzSgW",
	"iCcKZ86XISMYolp+JYK7FIvP//aXv8DxYeNmldCV7WDq6MX6/OXF82eaeqmCpruSqIX+j6LJ1Rpd2sAe",
	"5Av1zNDRHDIGeYhNTSR+dTNwBfQ+JUoDgOnlxWumFrI1T7uBFqQVvoeDasO5Y6f/DyvuJF4NZ9MnBxlw",
	"hgUIVYYOtHrhz6d+7MrPToz5aFe4WahoSEZ6ObDwzvU1PriEfOrkBIOjy2/NgEpPFVpCK4Hhi9xtG0we",
	"Gn5JmKV05M/GGKIxhqiUmTaLGzJdthsrBGPGJS3/qSppmQIV401+dEmrPIhBkpah2aOk9bVKWv1qnEbY",
	"8iXUZonycPAJ2NBqopgyaP5h6ul0WE1i1r+51ZRHpUGfHcC0qmcZgS0PzIxi04CfEJFoKtVWGMY207y2",
	"befEsVtMNi+yvo2VLe+yOUVWuaaZnaEQoWx9Xu3g/J+ptGikKbp1bQYXfh7FH0VXJD0uVN8moR0MdJc9",
	"3jqBzvBZumoa1WE8tZcxhlpTn8MmwASP6wHgBpGFpoL4q6ALgd0zRhgeBadvgwB9Z9hP1e8d3t0keIuQ",
	"ruCWhrhLkALpQO4I8D5Axw0ZDw/tmsU8+urp5sbk2QdsA1IfoGJjwTRWE0jES1x6zyh8t3e6HVNDJROW",
	"kk0PuITC5oddtdg9/CFbC/+D3ifLBd3/TapZUh8eus6xIwZe4ZoIrMgikijAjqHFIGjh3Z1Kby9Ibfzt",
	"vb8+1Sfnzu9NfecDjjEaxtlss1kEZ4ODqFlCTAjkt308iWXYygobhqyY2tI1gHVm9yo1M/GtdgRFw1Z6",
	"A6HtVoeVyjitNIbgobJaVKeEWSktFSBhyyWzX2t1MJt5I2uZCu9NQRbUQ2qki41rs+qJH91+WxG7E6Nv",
	"jcqDS4pA6ykiYCHBWbZGtJQ2gquxxNcELDgQg2beSEgsx/CCVCLAKEMY3SzbLIqbhRn7E797RY60kaV2",
	"kzLQnlQNUnFVqdWGcc3fEUYETU5Jzr2xpqtOWR4J1u/zUjJDO6e0QrSIoU9zDm7Vayj8qcgzSPpt3JqG",
	"VZbVQ9s20b1SFSmg1XidF1Sd6u3E8yFYlysTm/kdVdXSUcgED26SGtQlBHXFhunCUaDSqyvKmZbQ6X9e",
	"y6G86jLO7QIdPyXXtCsnhPmqF124GnW9623Uh/OLb8w6bUtyOp2wQTx/rb5a/2qYYaLtyccm/p7zq4PE",
	"GVtLe2YtI/m8s1SQqVNuS0muiIpkxLwkiHwiSaFMQopBlEivrZMaKboivE3P9EWn60RP5JNqts4nqyfV",
	"bJ2YpejJ8sndM3Z+jmUGHuZCW2LHacEmnz+Czbj6YySF5vWPWNwlF8rrssoousaCQjjeFVnvGMtFjqmA",
	"4gL/NmKmSwNbMA3jaJZtUbBWp6WVBnQVQ8PKBZitERaLYgWcQyFBwlWYpVikpl4ckmum8CeNPNQXGTXn",
	"LtHKevG6mSTKaQ6y8QJS4001RlG43mtTmNItAhVadEYYXWK5RDuJ8QP6FFfN3XBx9Yq2uHHojybFs0vW",
	"bLYL6VhNBuSCMWcHsgsdQOoK1kpSymu7vwmu+W4nWC2P814HiEqf1580g2cKLPauK2jcNHIyRPzngLgR",
	"jX9QUoEjJQqij86zIXGaZ3NAkzR6arEtN+4Tb/Gi8lGyT+UzpOcHlx+swIOMZLbMv3mF9RYkVlRa1yb4",
	"1S99uOWx4pwTIcjt3AC2riqeLTD+cghUAB4tPaiBU06M6/0dwRzLMz7VUI3iiFJ5mRt4g8q2hxVuSS/y",
	"+/PzE1N8Q1OCCBuPZ4mIvF0mXzFy3n+Cc4UOD6L4k2Mpb7hI2xgw8xXZ9AZG2x9Zl7d/+PFi4XhXNDfG",
	"3x+J8FnkI6kvrmhuGV3LNKLroEM82afK5CBgnL89MylZnM/hoKXr0a/IevjoV2Q9fHB+1VYiED5tB/qF",
	"JKKdR3Rfe+ca4IBX3oBuaWKpVD5QnGBmJcMECk0VTqJkRP/qRAgjhz6RhojYOluKBwlHnddsvbwiLEUS",
	"jZclf3cjqFKE3VkcEU1xxEkT2FbuXrMEdQgqphxtbPPCewB/OH1rSGXCV5rkz5VNsXuJJXydoSOFEsws",
	"G0PQLwWBEg0Cr4gCl5siWSIs99HFZFdTxF3Fd53rxj+h9Uto3ea32Sry+ON7eCnHYWQbXb+lLmBZeRI6",
	"uZGyZRCKvBUdAmAtnDtHCc4y/W4mGWdGSo1iEsSymyopLTilxzP4ZlhBzjJT0Mt11eyv8Xuwcnx51FCM",
	"Xki0glxGGsEdZhoGGOQkeLvsqh2/ebl2B2w9ppA+C81Uw0qItHw05PRZkiw3tEyZZD92R740pVK5dzna",
	"SI8yDc81hjFHK7wgbbXRB7v+BgP8yLNiRWo1zhuC9irqgnIa0lNH3TBlRCDoUXJFYSl4nFwNKr1iJo1m",
	"PY6D5aTIslLpXRbOOJq/5+rEaFkbJTRcVcSqe/iTsM+TGfqXFkckUfDtILvBa/nEuLmbjVKJ8gIMAZqE",
	"r0GsrvV6r79UOgFLiTNBcLpG5BO43bGW4ptmzsm0vhkYdaCnuYaPH0f/URtL/2THcyCNYMd+K3J0hm+W",
	"o7m0CAOPu7KStkifV5VMOPaJM26dx4dHO6BJoZgpC3nNjwhF5ziJcMB5BY16NxVgHezIpXLqvi39CzPK",
	"dkEWVCpN2ID8rPBakyzcuGm6I+Mmq701Zx4fHvnBQJ7PuKacElktKhcrT0F1WzOQDKsxDXll3X6jJwd1",
	"WR+eXJlysB01+0OCZFmyweJmsJoyfKI726ld0EBaBo2HMLv9+zTSt36dIbCkSV8GC9jOlbwuW98v89QK",
	"uFhGhId1AIhkZIiZ5okQXLxrS0OmZ4cWyCZacTm9nNprjmlWiDhTzgVdUIYznyZxUCCsIEqsD3kRC/57",
	"X3GCNMRUYXlVVsfQvWlFoTHIHbEChfrK+063Ndz/4Q+6mTTjHs48d5N8Kad/g6U7eHRJ5lwQ6/ywwuLK",
	"aMLyEjDW8eeOKBIsdAi+/FBcEsGIIvKMJIKobsK5LaI1nUiYbagBs1wlMh0jDg96y7fUNFRKm5gJAm0C",
	"jNyi8h0GkHLN0QFkjpOOUeBz71Dxd6AcfhpAqNdFw/YuDymGOuDIEg9RKh/SlEpFWaJsIvwpulmCVQQn",
	"S0ShirlERmWmzIW4mFyR9UswDV1MTDl08gmv8oyY4mvelvQyFzwtEpsaW/N7nL0s5A7BUu3sgfs1ES8v",
	"cXJFGJAb/2T3llasuujEdgeVIZ3Hj43Dgt+MaoZfg6nHBlmW0UTI4LYsMviwwipZvjUVAkzUk0qWpSnD",
	"mBYP3r8i6Qy9XuVqvcuKLKvNLk03pLlYm++sdjNqo/bRvHf19lBs0q/0TlURVjjXG//tiqyncMafjf0v",
	"XtWgiXIuOicafKW/BLk9nQuUtZesmVoSRZPyOErbRGgh1JhrjuMaC8oL6T2JYBlyhg5KbaCWK8C4AcoW",
	"bjLQ/VY6VU2RW9jneC4ByorI1X9nxBWNPzTIo6z/xiijK+ol3jIcAtDb60eNwZn60l2VAhREAGMCEfEA",
	"IV+UM0zDDKlb8S8F8RF5TumjOKJSwgcjOrkCR1YqCqLGsHGCAtcoKg1ZAEdi/SpeGzUTI5+UuytleVAP",
	"7kMDJlP4OuFMUgmqYBhLL8sGnlm/HOJAZnda1VPrfTtDFFTMFZCTWouMc3LjzPXmTHMspb569tLCiTvH",
	"T6MWq9bnNtZk2Kc72lpGa5qaxPmZg5SFtHXlowJqQEL6CzJFBcuIlGjNC7MeQRJCPSitOQJSzLMqY9Si",
	"+F5hyihbHCmyauFk6lFLl1IfrJayAbnsOgHw5sHUBEqD32qmbdZwd9BuK5DqwPd0yOJE8dQSNMhzANZ2",
	"R9lA6VPHc78PtyiJClN4HfDUAFIP44CekblCBYPLw1LEV1QFfgaSCIoz+quR2ysLDQIb0FObJOGSJLiQ",
	"BFH4DM5/y4KBPZ6XXwEENl081PCHRs/K/QhiQWcwsL4nsxHvfnCrnbjQTp6lYE/ADF3vzfb+ilJu0k4Q",
	"FcxhsFwznEwfo96EN4LU8Ubv7M9EKroCpfKfzW2jv1r3yYRn+vxgEaZSgo8J1vMKApSybWyjWwZqILwf",
	"h9U3DYnsarwZ796+4ynJxurgQXXwd28ht0iGUkHnBpmszR2zWKUGaBwPZHkf8Ll+WCvlmAlbWGdJU5Jg",
	"8bpSv8WpnpdK5fu7uxlPcLbkUu3/9fnzvd2VfjWSZjlnMKf4RydcjN+xnc1lanl9DaQ4W6ODo2eDTKkf",
	"NSpVOaOmfBQ1S58DEbClxMOH2HKPoFMDbVNcXgUPjbZaC95tpCyICW8RMGy19LdHmlF+zxX89/UnzedM",
	"ppNXnMj3XMHfUancxNy37Muy+aYN4LMLwxzKbtfQXIMw2HQE7LJL3jC8cOnvMzwOv364psL5kem61xQS",
	"TObzXrLyRZGIjWmcBn8QItBYcvlNPwpVjhtnmaYqwK6lca7bMBGWeYBK8I7tM4U9TFujg41ktmCMm0wU",
	"dxFKysbw6li/gqBoTeNFSWza/3O6IlLhVd5RNVWPZfMu3GjW0+QpGl4qNbXlADady3IMqakvMHy+BWFE",
	"tPgCHSDDDiaeHatkncDeBoLKUcpKfFB9z4beoBOeFxmUZ3HwNmVm0CnB6Y4WpgbGi9+5Ut87I5HaZBpX",
	"ZO1kP0PQwC8Ds1D04WKBmeZ2dDstXS240H8+lQnPza+Gtj/zMszk1t4TNrlK9GG4YSSqnQiyfmCF+A24",
	"dJvEevC7lnbRBSSx2NVzXUysCqZFbqhIPlH/SisnhjU2jKgzp860CNzoExlkeylLNZZJZIY5NdWrv0Rh",
	"UFEghtEEtSd7zLKyvSwrw3Dan03aeewVrsAkXIHxY7rIY3MnPeEaUyCNyczGZGa74bWIRmx2ZjXqu2hx",
	"3X+9RTVLWfh1TFb2+MnKGucxSFaqkNsxddnXmrqsQT46LzvE35fmF33Zgq/Nu55SmWd4HVcrfQ/VHX31",
	"NmAf5JLfuHBOEYcV+WSu51EE/V7bb+joleeuawscwHueYJUsXWX+/d/K+7KBD3JvDBBUJTYKuVCBg1OT",
	"MDfPjEXXpM6FJBItupt4BM8B+l9nx+/RCQdqBjE8bT7HRQs/Z66u5q1TMKTYRc0ayMfzrkDZOuHoStxW",
	"fnOqdUtGjPBSpSNBZjfTKrrBAaUpHsZXpqsIzMftRTGAZHaDpad0m+UqCWaNHeYpybCi1y3xHqdh+mFh",
	"mxo3DIeAQ2LRDyJ9nTnBKRHec2WFX8yshzDgiW7vNCP8moggTsT7GEykSHYpS8mn2b/lMJJQcfuP7dt/",
	"dYgbVi8TlXB0hxALqqxTe/T8TzvOvxJEH8D8O6pCXADPV1RRnY/82Cg5jZKTD+UxF2WzXNBBv+0mhC4H",
	"jotd1e9Voct/o2Oq9y9A5hK14xgkcgUUfxS4vlaBq0Z1Oi55XdiquTlVmYphGRvqOZZ6szWEQZh9jc/k",
	"smzbs/WW7F/1FpulAKtC5I4puKqD3TUP12apsJyd9iAjQp0WGYmJKMEOblPBHeux40mDizbr4CuHe47H",
	"pSvDZQe+1fiaCC2SFdJKcfzSegda93iYWEtr6A2c5353cp7+tDtdKXcuLtL/bMuyM53kPTnEq7nDzY6M",
	"c4egi4UmlDFIGsOp8YC/JoKq/kSD4Xmf2U6+ylMl/Z4bMTimyj6qts9e5KpM1swMYb82cMaJMGWx96AW",
	"/BGb84Fhl61rKQdubRLM2NrGLCXY9A/RR/TUv4v62UDkkxbeU3RNMWz74OQo3PShxl9wuyJndKGX6XRF",
	"kVrtvpaxK3hbKX9eq+E6mU7OWxO8hpJhxY3DKtpa6z8fnnxopVh5EfMJmU5eUXnVmiOQyqt4L+uH1+p+",
	"0+6m53xtWru2euI0K8+GLjKDS8+2QKLvzetaV0+mxRYo9s7YDsR6pc+Kr1ATb+L8R6dTYZeVHbvHKua8",
	"pV9BeKQzEAd0qxk6dg715tcc3N8txaHSZX/bgH2uv5oRLlriVZ5RtoDItetYHQL/yF0SdUMIc/tH0FWv",
	"+wHeLZ8nriNFXNtRT8OjiOy461EAKtRKH/XXqsKp4oMBsRHW4d5E19o47VI5yU06FQgPsDQXhE46GgtH",
	"5dSonIqX495UPRX03LaCqqNGeENEMTE4vQG1phl4jUG0n3MYpBJV6I7BgHhBTH3QVH2PZcSaoH91DKwJ",
	"1IDGD1cvJV6lvzU4uhdg0EpCDrRCU5/NAdZlAApAOa0cYWV5fdjhFJgjNX9kNaTtvGbJxnwU8AKjIvLr",
	"VUTWXphOtq+mjHRlrZ/KZ56pM3GKnVq4ntzjvih3NckoZY1UZke6pW9hMkeVHcprrzBlJnA3xm+aRGWM",
	"a9Rxvam+069xsrTpA6pDGT93N4BecMj0dt/Vh01LOCR/uvPY93nUm5C+r/TpES6lG/9uoQ8O+99RI4xv",
	"R0o7c6E7xeghvLhtQWWeYUFLzch49w69jpawOzfwdx2BHn7wII4jMvamhfYGKrYfyQGnMnmUA2Pk5jge",
	"cwE3lNyY0uroKfWJsi4zAuGFrMggqn2yr0RBYtpmfc14ITsmcE3uMIt95t5QkqUdnAFEBNvgF0hibvuV",
	"JKCkLR7VHSRNWIqPzLESg/nPzBfJsX9HasEMjBOs8KXVfUWRq1m0LW7F8K/Ykt/A6wVtffkXjU1BSaQu",
	"1SpURjqzEVNtRKDaqKmvdNWthisrayN2ACPM+RiprGU+O3OOq06Wm1/rtWjqVxQCec1lOi/LOnTqPIsy",
	"EXnaPKYBtZjqh/sZzkcUsK9vi3RB+hdRb1+WeT1fCiKXPEv7xgh8GOPuYn2Vzc6Na6OpagZCMKeJSQpq",
	"i/NJt0d9I6snExK1KirErtiZXG4pP/rZ2fdd6dFzQa+xIj+Q9QmWMl8KLEl7nnPz3ahI5fLE9/0y0ptX",
	"ltSbhtzuHAA0PBN5DHFCG/pmDscyPOYeM/09pTzW2695ILoEyF2Jj7tS/pa7ihG5NsbRMovUaKhVIZiV",
	"RjW2JTjL7MOXcvbE5RtHJs1NEM456i7uV3eh707k7IrFgkA4Ofit2sPRbW3KZOqyNU3Rc0TnLtFJnVv9",
	"5kVUUzgqL7aqvGjJ4zjEAaWU1AwcXWBEi+yMZdzTZYWTJWWkdaqb5bo2gT5oy+VeTN6YNJIXE7semx6I",
	"yjJDFlnlam0z+kBCoKroWebVOkCnsEyUZFiYuGjnfm03C2h8WWjKQ0xqIX5NhKApQS0aadlN4lyQiwce",
	"OoYEZfvoYnJmmJqLCeIi3Om9o41m+3cwS3csSHtJfkyHZTduyYTHgBLpYg/CeW+x11px14oxMwxX90U5",
	"x5dgtEmONknoUbs8m5kl6523a5msjR73n480qjrR1xqMXODjW7BiRzJI9Vp/CkZD1tdqyIqRpb673/Ct",
	"r7z9VgXTzgKATiwuBJu60TdLLoPC3va+z8FlmPczRGb8IZv1tHdYlsOwsncjueHGPvIb1krotIZYrD5Q",
	"HdmvKkm8PXBvsDSmjCDidUgmrE1MFx+nPfh0C/OU34DFvRmcL12R/+KucoXLlfiWG0fn2ho0TH7ljJSZ",
	"mIS0Togw29HB+wMXOn1w+vpg9+3x4cH50fF7l6Nb/1jlgU1WW33SXCCeEMzMG+J6+sK6UFUXC0WTIsMC",
	"SapPgqoltXYkLAiegshu427RwYoImuDd9+Tmv/8PF1dT9LrQ+Ld7ggV17qAFw6tLuih4IdE3O8kSC5xA",
	"sTS3V5MxW/oqvU8vJt+9O7+YTNHF5MP54cXkWZQ8GT31WbIkqY2nqBsFyhdb2lauOB/Xx5iglN+wjGNb",
	"Yza16CbDxNKKrtxXbosnIVvyOMJL9KqqD0W1RirwWkJ9J3BCXgVRGkN17ipArs6307Vr0Og4UQpYouoW",
	"r9t4pe+oCkluPB1fy0V1g378bIoMFIKqtT7ZlZn0kmBBxEFhXA3MX28cPfhf/zrXfCS0nuzbr+WUEI0N",
	"FSQWRy1FOj98iCeXqKRiCwxoCL3DubSFjcIOZTLFGcOmDDLVk0B+eZcJa18v5b9poD7GOf2BrCef9e41",
	"kXFpxnEC+ERWmGaT/YkiePU/5xldLFWishnl5Yh6F2/gCyTeFjxD5wSvJla1O3HsQ6V3I6veT9UhPj6N",
	"dXtmOSlztta+kWRYmPD+FWZ4QaBsNJ+bpxOII0kXxNvjbMpnKqAssr6B0hQNyGhCmLEx2J0d5DhZEvRi",
	"9ryxmZubmxmGzzMuFru2r9x9e3T4+v3Z650Xs+ezpVpl5p4oyBNQA9LBydFkWuL05HoPZ/kS79kUrgzn",
	"dLI/+Wb2fLZnXR8AHzU3tXu9t4sLtdxNvI5+EeMgviMKyoGaHOKuBlNph5n5xKmUM42hE43nVkUOifwg",
	"GzfM++L5c4cbtgxKUNpp999Wn2bufG9hp3IWQLxaipgfNAj+svf3rc3nxcNmgYECXHaUhwtJYfIX/3iA",
	"yc85R+8wWyMb3WMEWIUXEM1UPThDnyqHb8shktbj/9E20KSihgaQCz5+/K4XIJ0rGAqsYKSqc2RUTZvc",
	"0jwVWhKcAmV0V6tQSy5cQqhpAMo6tf54j3jYdTR6J7ANwIcHmfRbnDpUMJPuPdhOKSv3+oe8eNPJXx/k",
	"jF2NKyvKo9dCcDH43idlsKA0wYJOqm8lAqD6aA0yrDoZVomB7tnaUfaRB0jyaplW31DTBlPwxnk4Qh1Q",
	"r7+wRaGDmiKWNYIR9ACQ39nk7Fb1Rk9cEY0ntgyCtct4P6hqjYkWDskXWemiStNYqmObnt2EIylBE1WW",
	"hgD3aVv7w2WsNpmMqbCljqqFUaG8qS/QE1toVik69HCrNc5eUyc1QSULm31dg/iKoCcvn0zRk5f6fzW7",
	"9eRPL5+4PPpQrWnPlGvam16R9Ys/mT9eWFkrtlOY8XY71Zi0wp/oqlhVSoIYxPObDAuVlEVIzsuiMJAF",
	"ylTAaEe0SndE51Ush7RSZtBatZcVXptCH5e+LKgt9uYvDsS+BfVVAEKtmEFXkA2qhFOvLfte39lWKgKa",
	"9XYW8Ot9dT8wbDkg++49/+YBZn3DxSVNU8Ie/al9iN2eWTHxA/NW9cpD2/qYQnhzzmNGn0NT3RUPeFGb",
	"D6rp3BXwbxfwLU/X93/5DMxKXYgSBfncoAJ7D7WQGKDTkQzcOxl4/hBkQEv7GTX6vZHwdBCeQcz+7m/6",
	"of9syFNGVEQDbX6vEipkrx0qCU6VQL2CTl0EqlcjEIYd9dNIzX2alXpWBmJ8PCdj64pWidSXpy5w/Mof",
	"hmb85QGmfM8VesMLlo5Eo5dbiYr+gmBT3rCUKZKOu12lBd8R9cCEYGHcbu9OBaaTgtFfCmJLcQFf8zjy",
	"zUgrRlrx5Uk2WCXxoufJ8paSDfR9YHKR+7qB22IbhspeOzD1f252mpUyAIMkr0emT6PQ9XURxVHO+8LI",
	"cBFl2aAqRo1rOxzMtZ2a/g9MisvcQA9Oix9MD/ao1HhUw40vwvgijJo/p/nbxXkuuE04Gn1IDqCBSX1E",
	"2LqLr2+y88a9tbXDgZt8a4+JKUUeLnh8TEbWfiTkIyH/fRNy43SMIfOK3BVEFqZ0Ydy4fArfvafyJZYk",
	"RZwZ96DSYwezdJdbNxz/6ywiCujRTIiOvCfbshndzPRIBLC6BDPJSPtGl5JHIQuV+z75OJ182hGX2CTf",
	"sYmpbGjapKyTD9ZauKWOQnxu0pAeB09zC/q8OUtiMLpujq6bo+vmV+K6GcERm3wMzTO80HhiggqJSV6r",
	"V7NaYbGuRt7KGfqX3gmAiiOQrFzwmQELQLKSBxduvh0siFG14ZcAcEjv+MRgUwXvn5Qwqodh3uh1PLED",
	"66GeQFZBUbRe/aBtDMt8MrZ7tQMb+jo6tY4cyCNzIEM8WGssQ5u7qq83dX/yw0M7ooazjuru0ev0D0YZ",
	"mrLFAH/SV86ftJdsmJaebGykIa4NPrqHjirQ0eVr03e/PRVA/+X9jqit3dyt+XM+BNM+Xtvx2j4yu97t",
	"ltl7daHh1i7v6F25RQIyShKjvXUUXrZFJ2PuLsZjZQiZtB6SWyOUvwvfx030LA9HGEedzkiJR0r81amR",
	"dlMCNeakz+IYo9g+LWZpgDLqnqBvU7VUftyigqkc9HdBxkMojLzuSGFHCf2R6V2GpZKEsM48nL5guG4J",
	"aXylwqu8hTB1aObeYqnO9Gxb0dC1rmtufAp/H9o7D5MOXvMvkSroHLKx6kWMZGQkI49MRgRhKYEL1UNG",
	"XMMgY36DVpzaNtvU5scmd05PiS/suC2qMW0tMnzF+A3zC/nR5buPOwZB49Nq28mXamsYqdQoTo50sUYX",
	"y4pQnVQxLIYxnJs6c4XhRmvnaO0cmaAvw9q58XUObJ9bu9CjBXTUCo2UbKRkd7FHbkzIKtbJrZGy0UY5",
	"kq6RdI0y3hck4xEmeJatCFMDaliVjStBZjGp7rVv6stYDaaeeGC6KxMGC+X8GKJSFtXEqlD0PRf8mqYk",
	"nYbV6GwA3ZIkV4j25USxcXYyPgnE00HsIpUowZL4ED/q9HQ2PrIOEaj0irMMcbUkAvpObfFYD+VwIhMm",
	"CSu/JKZ8fWv8rRSPplprHPxI0kdu9A9CYMubG81C0vjck0ygvEoDq0Q1OowpBsYUA2OKgbE61IYv91gV",
	"agyg/xLf0r5YetbxZLbF1Td63FOIfXOeB462b1nA6KQ9Bt6P3HmUO98gHH8zymN6xSjPRhrm9inHgP1R",
	"Zh/VsL8rzqY9W8BmtKWie70XwvI78bAZxO+MBGZUCj6OINOZZWCzKw+d7vnSj14490N4RhlrZKdGduoe",
	"6GtXdoLNyKv1BbpnAvu78A26pRLrUWjrqDsb6fpI1/946rpb1GSKvAfNZ8D2uodn4HdXdamxBV+J6rGf",
	"A7eQfpXiSKBHNcNILm8V1nd3heTtPOpHteRIL0Z68XhqyTuRgbiS8j4IwaiqHFWVIwUcRdqvQVV5J5Lb",
	"pri8D6I7qi9H5m9k/r4WYfFaz9MqEp4SJSi5JhJhH4hguswuWDwwxQzYF4zyh4l3OONCIS5SIiB80Rb3",
	"g/gDvSGX/K8aa/JEj/EEPWXkRlPfORVStS4OBq8sKjVDQZVTmUymE8KKlUYGDH/Bjx+nt43VMOdvzk0f",
	"kQu26Ivj2U6dxa86iuletRH62MY4jzHO4/GeIo2B1ednnhHSFxv5Rrfpi4d8YwYaYyDHGMgxBvLrLbN8",
	"ZDMutNVTdpsGutK2EpzaHK3yzAzyeOWLgWyNj/L4KD/aoww3ZUjx4uoz3BZjCa3uKa7SjP3AsZTBpKMP",
	"2Bg/+cciCg1Offc3+O/nXUVWeYaVZggl5aydhQf2w7VGvnmMhz+3rX4sG/WqrfkNM9yTfvUb07QoqecB",
	"kbplZvRRkhgliVGSGLOpaDpbo1sjOz+y87+jl3tA6oPUpj5oPLAt6Q5qF+LO7/j9PeN1y/fAmcecCqN5",
	"eTQvV9UHUe5fEJwa1te/+7005DuiRgLykASkDu2RkoyU5IviXAbnZupVUpqGTkm5kVNcdegx7dJ4sceL",
	"vQ0WARIf9V7c74ja0q3dYvDQH8M8OZKNkWw8rmGyM4FSL+mAdlsiHmPA0fZox6gHHYOMRjPtlkhkVw6k",
	"Xgppo4e2RCN/F/FBG/iSPBhJHN1WRhI8kuCvS2vVl3MDFORl2GdVVe4IclwUvl1s570KxKMsOsqif2BZ",
	"tF57drhkuq27PMqno3w6ErGRiN1CWhRGCNyQGQlFx20RsVGAHHmgkXz8DiQd49g9KHlESqWiLFHeAdv0",
	"9TkRSjpTUoJ1TtqyTLw1Mw8gNXoU6xPtCYywC/OLEHzVZo27oiztpDcut4Itaz8kr8IBmtPMxgvU18JZ",
	"tjYRAz7iGaklDqMCFvSaMNPeO7rfixf9FlZpHMj7Vrl1D/gS3cx6HyRZxe2kX/IJr/LM9DCrfW1+gUtt",
	"LcD7E/tj6X+vb07mrgE42pt0L9dUcLYiTL3MBU+LRBkHOkEWlLOXhdwhWKqdPb0BSsTLS5xcEZaaiz2M",
	"hsDlG73cRy/3R3uLAO+rbxEXC8zor7COzfIZVXrOEDrWtM1QC1n9aEicJh+FJAItsUQ4SYjU9CWeluK4",
	"sqp75AzDicarOV7NB7+a5UsFSVt4DfHdzQ1/r15gQXIuqeKCkp6EMKeu5bovK8xpOOaYG2aM6BwjOseI",
	"zgHkr6Qw41s6vqWPxub6J3E9JEFL5Flsy9JSNr2nVC3BBA+cr6U+8+j9MiZt+QNSixbGepNYqkH0xLSu",
	"0JONrD+RScbQqtEmM9pkbsMgdMRXDbrM3xG19Zv8O/Eu62Ybxqs8XuUH5vW7Y54GXWfrXbXlCz26mG2Z",
	"qIxiyOiEP0o+26SdncFQg0indWvbOvH8Xbi2baq8eViCOSqLRio9UumvSj9lbbhrlvRafk3TszVL+m2/",
	"ZdvR+Dsaf0fj72j8HcgUlIRjNP+O5t9HfDDLh3GYATjyOrabgMvG92YEDqZ4cDNwfe6Rtx8NwX9IutHG",
	"am9mCx5EWpw1uEJaNtSbRCYaLcKjWD+akW7HM3TahAddarAK38ON/t1Yhrs5ifFSj5f6wQWBPuvwoItt",
	"TaP3cLVHG/HWycsoo4z2h1Es2i4V7bETDyKi3lJ8D2T0d2It3lTL89DEc9QrjTR7pNlflSrLVipqMxZr",
	"+VbaoYNCTA25tqwvdW8kakBRpdGy8tBo5fDnI/Q1RlPzUhcim+xPdif6tbSt68h17LDIZC/SlJAwZbcw",
	"C+p4VD5MmtbeYCDO0CERis51a3JGF4yyhYVb1dHB2f3L1tK0Fv4R6J7H5CmKDmqqlHSPoLds2iGcKFdk",
	"uTKA/b13Ja+Z4Fm2Ikx17ZT4VoN2qNdnsxVRtkDkWqNMOJz+oXdp1aR0YX+TBmuTJdgURDgRXEqU0vmc",
	"CMLio5vEJpuMHib+iA5ZybjQt++21Ap2rMCFp3+kNlcdP1ZA2gfsOCEUNhyh63ZEd6s/f/z8fwMAAP//",
	"Im8FrFFzAgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
