// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i24cN7Yo+iuc3gewPbvVspyZwYwAY44i24lObEtHkjM4O/LdoarY3RxVkxWSJbkT",
	"GLj/cP/wfskBFx/FqmI9WmpJjlN7AxOri8/FxcX1Xr9NEr7KOSNMycn+bxOZLMkKwz8PLiXPCkVOsFrq",
	"v1MiE0FzRTmb7E9OSS6I1N0QZgjbtmhOM4JyrJazyXSSC54ToSiB8fLoOOdLUvbWTZDiCJtxOENqSZBc",
	"S0VWM/SeK4LUEiuE2RqRT1Qqyham6Q3NMnRJEL8m4kZQpQjTKyCf8CrPyGR/snuNxW7GF7s4z2cZX0ym",
	"E7XO9RepBGWLyefP/hd++W+SqMnn6eQgz8/ht9iydWvE57BGnOcZTbD+CvOyYjXZ/8kAV5LJdPJLgdOM",
	"qMnH+rzTyacd3XznGguGVxpWP7l5D313+8P/dqOYtbkpDzlThCm9TJxlx/PJ/k+/Tf6HIPPJ/uQ/dssT",
	"3rXHu/uGZsR1+jztbntKMqzotcED3ViQXwoqSKoXCof6sQG52vpes+sfsTBYUMEJUn7AaUp1W5ydVJrU",
	"TmlaO4jX7JoKzlaEKXSNBcWXGUFXZL1zjbNCYxQVcooo0+siKUoLPQwSBVN0RWZIn+MVWSPMUmR6EJws",
	"0aqQSqPTJVE3hDC0Bw1e/PUblCyxwIkiQs4mjW23oJADw4ng1zQl4iwnyfCzisBRn0IVkLhE1J6xoNnn",
	"6UTjWst1LCdEupWHxt7////+f1UYoIyzxRRJhYVCN1QtEUYZUYoIxAVixeqSiCnALuFMYcoQ4+hmSRWR",
	"OU7IbNAt/G3CGRkAqKMVXpA2cPdh+RHLKGvv/fHzx+6zPVNYFTJOLMw3TSowkpQtsiqMLZlLyTU1IHHU",
	"40SQHFsicaZBbP55WjBm/vVaCC4m08kHdsX4DZtMJ5piZESRdDihqe4gnLPxMVhE41u5qsYnt8zGh3Ld",
	"jU/BRqqA/pFnhcHc8vpUwf2KzCkjEmHA3hRdQw9USJKiyzU8V1VqXb1K8YvxgdFfCmLug6X54bga9ymL",
	"PQVN/A7pJ0z28Y44b0DSQNgY3OokqLp1syPZ3P1bKhXgb4C2trHeI1VkJQfQntoZlncdC4HXvfTTdDP4",
	"0X3LtnLk7xtnHTlPfZxzIghLSIxJsp80U2PueJ7xNUnR8eHRjoZRRjFTiOpT1BRTX685ThS6xMmVfqg6",
	"547hUrieHpIlz4rVCov1QNKVZSEQZTvZ+p7gTC3Xk+nkFVkInJI0Qqo2Jk/V1ZZztDYJJm9tE6FM1QZ+",
	"uRp0hVoecjaniyac9Df9xs3pooleuFDLY7HAjP5qpihH6bwwLd0+T2HE+IHBQjRko7iq+304fdvS7cPp",
	"234s81OXo01bdxjFwHZoRNYkNPdJUsTDHhbShWi5z4RpNjA1Q85xkanJ/hxnktS5x6M5UqIgUySLPOdC",
	"oTkX6Cg9Qbmhk/V5qUR27ABQl5xnBLMGpNwqYkD4FqskIg3Bz3oWzBDJCHC1lKFL+FmSXwp9r5v7zeiK",
	"qjgzt8Kf6KpYWV5M05iciIQwBRRnbq+v1ASqyFOsCLLPGMyppxr2EJ34UeH1WlGmp53s7/nNU6bIgggj",
	"HEiSkURx0XcH3uJLkp25xrpjkSREyvOlIHLJs7RvgHBdn9sO4sxCtuVA3GeUWs5CwyezTyLAyQDwkiDy",
	"iSSFxlfKOs5Lts53UB3XzAhy0fCH1uDW56k+hCPTYa/+0k719caKLNZ9o53yLOOFOnPN61jux4mh+aHe",
	"81xTVnJGF5o/PNVblxFkbW2KRKBqQML+qC+q5qYXjKQoKfuiueArOKDDgwglzumPREiYsQH6kyP7rXLO",
	"1+Y3kiIDEcMRUFkuy3Lxc31pzdZn6IwI3RHJJS8ykH6uidBbSfiC0V/9aNJxBprKSX3ZFREMZ0YYNaLT",
	"Cq+RIHpcVLBgBGgiZ+gdF/rWzvk+WiqVy/3d3QVVs6u/yxnl+khXBaNqvatFMEEvC8WF3E3JNcl2JV3s",
	"YJFogSxRhSC7OKc7sFhmcG6V/ocgkhciITL6olxRljZh+QNlKZAxZFpa2dqDzLE2p6/PzpGbwIDVQDA4",
	"9BKYGhCUzYkwLf1JE5bmnDIFfyQZ1VRTFpcrqqTDFw3nGTrEjHEQZQ2tS2foiKFDvCLZIZbk3kGpoSd3",
	"NMjiwFwRhVOscN+dPAYYvSMKw022vHxXj9bbZYXjifRc9e2GMd0bzEJ53yyqBJu0K9+IbmhBZAPaAXIL",
	"4KEjq61NR2Jx/8TCP19x6bLzbAY9fe3vzefmCziSrkcgXfqsDeHajFSY49+IVjgdR/V8/yVwnhMtavOC",
	"pQijQhKxkwgCYsbh2ekUrXhKMs37M3RVXBLBiCISUQ7AxDmdBfyGnF3vzTqXEBFPPuXUiC5nJOEslTHN",
	"AfQ3GmtPM65xRlOq1sD9AMaUE+tp5lyssDK89jcvJk3Wezohn5TAXfp2f88aR1y/PzVFvB4YYWWQi0in",
	"OdHgNVYbB2NgzjScc54XRrq7XMOvBydHSMKN0bCH9nrnmq7R1apQWp6KqN0NIkW5ynOQZCT52192CEu4",
	"luhOXr8r//3D4dl/7D3Xy5mhd46TXxKkX6aZ5zUpyYCjxyE+dDGshipUjuRyrUjs4gALK95HNVBHLDVI",
	"BmsSHidMH0PwgVT9UuCMzilJQUEZvaAFjRC7D0evHuCcgkVIvIjpFz/A7wB1vQ2gvgTehCuyRqZXsH8r",
	"olIpiyr3X3koehFYb7lf9fcAgKmRQofNFeTYjPS16EhLhMJ5Lvg1znZTwijOdueYZoUgSHqFn99lYL6R",
	"LXBHdF4aZWWT4gVN43fUDtmU56Yl4BDXMriH+aDbpcmrEZ8jXKP/ZhSb+mR5eNNm6AfGbxhKgoaCoAMA",
	"HUmn6BVhVP9XQ+gNplYtNIxTcWNGteAhNgRbiOKAH6h9g+XxpURhmkl4QDgjCOsrp9xxJ4UQwIEofaaO",
	"d9VIfRqQtJruCUt1LjCTMNM5bbMq6nZI0RUxM/mlKd+XpIYv0uuyaKg4woyrJRGV09YM0I4eK86JSE0v",
	"mqv4vlhhhgTBKWCTbYeouROar3PQwZe8UHbFfnlRgsYv4bqn3xFGzDsd3/3MsTKzhW9piEoVGjdYAuXT",
	"b1aKitxMG77rf/tL9F0XBMuooIKeXgpK5s+QaVGyDm7OJ3LQTgcKiG5UJxC6kQZ2M9bp2g1QRt1sVzCN",
	"oZwHQHn+nZel34hUgdEUkJLP0Tloi9+ALhlZ40Bo+9DfJ9MJNNjY2lFbnR2r9qsbuvZzaKioQrOJj9Zv",
	"pcQ6GkoSwW4cpZtMJ+cn734kAngMYy9xHwwNhD1rAthsCvpaepmR+h+OppxgIaHp2Zol8I8fNZ+rWxjd",
	"4xE7EXwhiNSH/0GLP9YmnpPENX1XZIrmGTm+YURIWNc1TcgroiUfKrVcoTsNO4jXTPAsWxGm7Hsa7Lfx",
	"rbrd1ic5GKK1jYdlawsP5NYW1eWckpxLqrhYR0GvId76oXE+4Ud/Vm8yQpQ7BfgjdmrmNIKzMz+EJ2h+",
	"GXqOBs3ndFG3aA8zV3xHVaR7n5PID577PyOJIOoWHia3mPV7pfJYN4BBXrhTeceZPuimc1H1vV6ZZv1u",
	"baVugyPbqZ91DUePujV0e5o1d2J2KTh7/SnXuBRndARniPgGyLyX8NTpsdMiA60NXRE5u2B6k7YFlejn",
	"PyP7/z/vox30jjItve6jn//8M1pZifD5zl//MUM76HteiManF9/oT6/wWgPtHWdqWW2xt/PNnm4R/bT3",
	"Iuj8L0Ku6qP/bXbBzoxxkqRIHyRWXC9iRzfc90Kr5r6NpuopmS1mUxiGMrTUS/bjkWsi1vDbMz3vzzs/",
	"76NTzBZlr+c7f/8ZALf3Ah2802f/d3TwzrSe/ryPQFfnGu9N917Y1lIBF7z3Qi3RCmBo+uz+vI/OFMnL",
	"Ze26PmYx9R5nxkGqupe/lyDR7/Lfgy4X7LVx8tSQQ893/j7d+9vOi2/skUZZmcNCKr4yhOWIzXmXOqTO",
	"TYG2yKh8U5TAQMheMHsA0Snr4m4wCGUGGUFQBMaz6lbRYGLMwpuLM79XzWX5ci1pgrNgvFHJPVrERovY",
	"bsmADJdubJ9b2Lo+tt7jhudj0y0vrqOqibOhZ2K3CyLISuk6/vo7P5G50xloNLtZ0mQJug/oiQZ5Oupp",
	"wDE4Qkff+1lcG+QkaS+gxkcPRN5hZxb30f08bXd2LGVA28T7EcIlq63rdr6PdfG4RffjXfr0eQUA9Zsf",
	"hFdVl7bYqyZNA4c/S/Cuqzl8Rjz+qmhK7VPaiabha2fULY7ygRIidDDdikKi29+x6czSA1XDh7cB8jDQ",
	"n5VaBAOvVu9AQVhKBElbn+FT28A9vK3j9mmVq/N0blLyrJXDsJ9DRsMqS+DnhDNGEqtX8Icdc4ICZv3o",
	"VZwQ2c/o6FWosqrNEEcM0/Nd8HTU8N3zen4WR6gdadPrtuaHl5VIkgQzeC2l0RaDcxbO6K9GrelDgohY",
	"UYazqV+zcQ/T3aaIqKTtuHB6zLL1ZB+8EquoWdvVNABg+1GGcnMTEG4wy3dih1JpVdr2+vDGGSosFkQN",
	"ezbDpZxDv7iyzww5bEvBOE0y7o1J5rJIPUNjayuiljytXqlQBfaBEVD4gIIrUVysT4kcHMfVteJg5K5m",
	"1Vk9FI70OyioWh8uSXLVRpDa29Zvb5VkUdcDJboLyonQN8LYxG/5BuxE34BS4qnPaVZ0B9Lfvvnb0f7W",
	"kXq0yBsAs8Q6FxjzgUkn/Yc6Vq/i2wQPYxsoZ+pqE66hvZ1fXXuTct1NsLbq5C1z0oaijbub1yR4mCXV",
	"Uoda3x5pwIFpUxanRG9gb8pF9zA3urWHVfN9pCvNCa5yt/fa4NfQs+RRhxnObnWrbGCYOSLHWqt8dRc4",
	"3/piNhcz+Gq2PgCBMt3jd/x63uoq1q5Fy5bablbPHW5e3/LavcVSnRHC2h4N973+UACqSf1BhViIW+9f",
	"1jpR0yxs+Q9jBSXMuVVoyZDW/Gk6ULmGP34B7Rj0ls5Jsk4y8j3nVw5xHAZ8S+ZchLaLg7kiIvjbNDgl",
	"l5yHLcofNsGMylIaU0fa1FfTOky4wLZxgjU3gXMrsSdzvbcgMNbVo+Xg2+IWanu9HaMQG6SNEIVJBGIQ",
	"a3IExgBpqUHVKlb9ZUOSVFt1najUPldWEfkeW1pPsyp5ijp6l9+qXt3mdzmqtx/dhzs4iUGaMWvMGN2z",
	"vzT37OnEKgWHnaDjurbn1x3zB3hFFOTxeGUctZqqcqNS7Ddum3agWUqpbrSiDCsuUF6InEuDwI72dq2k",
	"SWI1tLFKlpQtwB2i47LM9XfQ3EvjDAYda4zoUH/WGtwDSDQWNBTcp0Ty7LoD3Fgaj01oHoe42aNriLBE",
	"XDdGT1mRZYjOEePml2d6s/pH/ew7DVjEkPpAB+z2Hj3gXJBrygv5bpODtmfs+mZra9NOb3ngYA/gWdHu",
	"6fU9v3GK03lGEwWMtbAbCwFgjO6wm8l08p67f8G+XpGWjCKdKFdbWzvKHct4oEb4FZlPl/aJNjpCdHzm",
	"VcOt+qhV1BX0vDKISb9gDGhiWBS8GbdzU7dhlo/PBm/hx6oxwG0j/mbrL6/oojVEIoVv9bGM+wWSS/zi",
	"r3/bx89ns9mzoaCpTtoBKLhsS5ofLjFbPA5lr68heuUZuemgcozcWLpm6J2nboKs+DVJhxE3Rxo6JnJN",
	"4rMxzsiQqdovbvtJee+/jRDbM5N9arokL4ZxGtV1OJVTSuXVXfqvyIoP5XViI9Sd9vNi4ge1qxsK2m4c",
	"lxXfPAPsKlKXuVH+hYUVvg4FVTTB2a0zscQWGiZ6aX4tJ499DRYU++wWGfsWujr778WKBKkF4t5cNgUI",
	"ZmvrGVnVEoWZJj7WE91BDFjw+eM0HrGnxTsBy/GpNYwvP2cIpkAu9YUW9Xa5sNFl7tcZOlAoI1hTY0bK",
	"xi4Hm0tMUslu+Ftt9fsTUqbFe5kLnhZgLp0qSsTLuYDMf6mhOOEdrG4y5ifglmN2qYRmKsJsGEE6EQsF",
	"o8Kjdp9yhj5IF2OnH1zriIklKp1rayCRzg3wwgsOM42XL81ke1Or+8mXWJI/vTwhLKVscTF51qJZr0Bq",
	"u3uEwYftsYoMwR6vyHrP2Jz3pldk/eJP5o8X8Q197iIqcClkzpkkvbeijs2mmxGFYZsmQMZL9wHyGSik",
	"VhCc7H/zuenjUG3R7g/kgatZ5RsiCLIZX+ZFlq0twNOYQ1DD3aEyZTvx7eI+a7wn7nCjLN1MhqVPsxdZ",
	"3CqBWs1/vCEYJC0pldxCzPdbrCHqvh6bXvIsdtDnwT3CiaLXpVeHdWfYVHXknFWiAcpVHeTGbgoQ4TVw",
	"HVaMsVIZsDwR6qKXVnnArcN8NaPVcBjUXOZjUDDpc9MWLxvz0VlYZM3ZvxY6oKXCE6wUEUx25S4yaozc",
	"tqxspkFtjbu3W0fBqFGITE06US7gv7xQSBbzOf00RSbxz5Jk2Y5U64ygRcYv3WSwfpgdLzBlUrmYxmyN",
	"Mo5TYqaANa3wp7eELdRysv/ir3+bTuwQk/3J//PT851/4J1fD3b+a//iYue/Zxfwfz9dXHz808XFzsXF",
	"ny8u/vnxP5/+z2Htnv3z6cXF7CfTMPb5f8Qeqv7UiEbVeMIzmgzkXD8EPQy6tr8f3T4lTS+SuKFGBlkZ",
	"LfFEtu8KgxmcZsbdM1EFzsrQ07vSWitRhyS3tBFtQF+a/rmRO4abXoYbj17z0hwevOzPAOBo/Gidx6aG",
	"YzSyF8cUTrcMWA7fm0EEu3ShBJ8Ka62+leeBc5bYjoUZPX1/fP5631gBfFgHlYhxhQRRhWCVYP9nA03S",
	"WqRa8J1/S8526IJxYQVzvXhnELuVgXLDF8r3qbxRm0q8GxsHGphtyL2LvRkwQNne0710E5KXtviWBFes",
	"sqrqlZ7Eb3gIxhCP/X2AsynXW0ItPPYOzvTWbtsBpi+xSG+wIGBZNPFjmpM3e0UVW9/23bntGlw0/zYc",
	"uiOguZ2VfqPst3HfoGMI6Ywnug29LU64lmTS4/m84jx0cIOpgshd69FswrpBVX+CC7mhAb+yoWBpjW/B",
	"aiNfq6qXyqemB0nlc2Wbke91l4LKxxgwIs3q8CmPs0JShoXzHefODdzchiB7EfmUc1nSerwgTM0u2Guc",
	"LCEnTcKFABk5NVkqSgbeXAtr1U9wji9pRtV6dsH6AwPNJiq3KuFZZmoXeKt0K2OkF9nq7qDfwoMF1Ekw",
	"TeIZggNDc8sYQQvNe5jIVAunRthiObJGnZiz/7ecK3T0apOhTNzlkOejEeqp30tHBA2047s89pTyzFHK",
	"gcur279DgHooNFcxrR5fO91q8PA9nu85tASDyAozvCj1ONZXAepjJFmR6i83S8Lc786Z5ZKglN8wKz/p",
	"d8Tmy4k429p2ZybsupepMZvxrf3jftv+n3vAlt7KLGfWtFUHtvB5tImXt/g8VjZ7u+exOcQGLmwlwLz/",
	"Wn7OX2FI0nRcqOO5/Xfgt3gbe0RlkcEUka/hrNHONQfK6teGySEU83rYMqfSdKFFYLLzwgRcuDkxfgRl",
	"gRCwvHfKviUmtz12A9IG+fTovzXeogN0KQi+0je6cyeXa3QRruti0nTGLJFL1nnaL2Dxdk3dC1dc4azF",
	"LKc/BZGzsZkGpnGy1O9Lgo6VXrqgUw/hAlBNI8haP//ahqPUiMqr3hQnG2cVmX5haVGiD7hVW8HLbQaA",
	"t5vKK5MScZMaaykVYGha+yJrTvNsPSWCMbv30lHy6xWVooBZvy1SGxhYUx7WWlRT6pNrktlaI/yGpHpZ",
	"trUhk8JkFkIU8DS36YWaYFgIXuTfrtuVg8b4dkXWwLzbgCwE3aCknPMqKue/hOVWtGWBvvjpTwc7/4V3",
	"fn2+84+PP+34f//37uzjn5/9M/g4QNMLiukPDF9jal04onUdTIGFgOq4M0K+p7/UruqZAR/ovjvqM8DX",
	"g57pa2Ul5qhgzXn9OW40f5SHK8LsepawTZ5rCtK+OJ86163DpxYw4cmKo8SWmTKV4HyHkvF1KUnBcxEj",
	"yKZFr23kENG3x459uUbYqBkLRtUMlUl7/I+QPnIf/SxN/htpkv9O0c8r84NJaaN/WJofIHkPoHeAav/c",
	"/2lv5x8fLy7SPz/758VF+pNcLeN49ZolXDP1Q+JjiW1r6ByENwNhwArXHN9Dri7PMNVirUmxOzi7mpnq",
	"xHZ2f39rB/kcJlkri8PUS7y4FjtWd9vHGZdjntkOzYItjTFjL1IjA1wTto0mHUUsbCJWjY1mAZ2mjzGc",
	"YczW8wfM1tO4UJsl7ml23269ipaEkTGBobVpmaQ3rjHwhCKw3qGSZLUnacAu82RHOuibJVFLIsLsx2iJ",
	"JbokhCE3QKzmlXWouksJ1wOX69uMBOrUPM/WZdG8llRojcOz+9zohAJZa5A40X7UTT6+Z9K+Ew9s53c9",
	"+4MWx2/gTbCyGZ7C07/BsnLww2LIXY9v29JLVbNU6bYDxKdg1Gm4pYgUMt3wCG7hwBABvD+gWRTX4sGM",
	"0WbVuMZGk5ElePQIx+iZDHKhaDKOY9jj11qVJs6w9NMA8DilxtXUNzTUp9H2iXRBTODWE4mpkC1RJLEa",
	"KGE5B2lSSofvSuQRr3qJDU+cOJ2ANv20L/HZOTxHncnPAGVtbqfZvyVn6Cm3Rt0O9++tcisuib9zIbqh",
	"tlKuZWCo9E5HS8KQvkPBA0JljL1q4XD0eQ5DthYrV0vDzV7BQY9Syf7eipkKnOD6SoeEuNysHzLbuCpI",
	"swYGuQPN31qdj6b6ouN0bZMuBnPJb6wCTJNguPW2gP+bjC6WCh1qksyzEFmDPCzNCseaLCdeSbeRJuag",
	"UFCwNFDAFHTHvULxY/9w+tadzoej8haCER0V0rgy58K9Yv/7FGkUAe4jo+zKZKCG+dzb2eFwcFsVU5um",
	"qQavcoJWGAxCCYBjP1q4YtVlRR/7xleXVUEaU2/1Fqhhht4JruROPCvjITQM6hq8wgqXywyvOWglgfRj",
	"t3Q9PprTDKJt0Pnbs/jFN4u5IuvORfxA1htNfkXWfXPXL3sLVJpLHHTww0nCAMrg0mvqa8FveejBvjRS",
	"cUFVK8jLtgeuaTv0Qy7Fj4wqBfnaLnAspNZwwvoVBuKRpoJI7/3Ru3H01DG1Sy6Vlm33cy7UgCDpDgD5",
	"xUZPXnO/kWO+NsJooGO2fgTk2jiGY4V4Al7gvnyacXqLEPN4ZFxdfIe6aGDGMLAwJFjQxQL4NZAj9OTG",
	"tGLkFeCNIIqRzOknYzUhFDRPerh99BTMHuBAo3+Qz4IZ7FdcKL6ComsuaCXO6Y2C8bYF47SMze98BfWI",
	"Lo4fHPyvIeGE0foO0w2fkjkRUCJ9FIm3LRK3lEc7MPeuTNNaE0DrWWI1HHNbymyL1oD2QmZyyYWaohVO",
	"lpSRcp32+IH+VPOE1EqeGXIUmC+da8ihKewYlDg6tKUbfeJF9+GD9+Wv/tJo6LKm1H4Jx2wGHLb8XOtx",
	"ePKhET5/ePKhHnB/ePLhvX7ay0bvIB9Bo6/5ud7d/Fob4RWVV43++sd6b/1brW8Q61T1MQ8+NFzTg2/1",
	"dAOvqLSsSpgaM+KkXvMZr//sM/0EH2qjHkLEvGp4GNrfm76FvkPUq9Cf50aFxpxsXMOGlrxU3RmdOipw",
	"6V+O2LX97cg+UudYXvmJwx9PiFhhBhGWwR1oqTrmfj5iuPrBUvu0bFJetGaFsXJ5YcGx8haHv54pLJq/",
	"+qVWBrDOIPXfv8UqWb6iMjfpmmpfLdRI5uDe6BqOG9ZQO9QXXAUnNqgsWwN25adopTb9I2WLBoGqVHGr",
	"/+hbG+/0UyIVFy2ZcUzPQVzBmWkaVIVsd7QLGMhjU3zR0JMpsrQmpOSe1Dg69LHfptSt2a0yLZH6klNf",
	"l9JsamoZ51a2PUhtFOHed6ynUeKqkE71w1bAO5+WOUQsP7/OQeqqZDgyIdp5bkPdO6lDp562O+deD2HZ",
	"YOR6erm2nFA9YY0tGaQ6L2LLiO09OkYNKMPQYcsu8XE3WmjPGmv0acCA1R7xUS2BGDCaaRkfxRHnAcPY",
	"puU4kZeptfJivWV8lOZTNmDARqdy7K5nrdVZubVLOG7lDenGlGjj5li966o0C6Q7FyVtKtiHqcQ+TwcW",
	"42wdfFBUc8v1H9a7m9TdZow6UesvC9qGnJv0bMXCoTU3o+jR37kXW/uG6Ljim3TdbNOd1HOTzi3EfOMh",
	"7rSIOLn+/HGjHH/Ag7T4qbhPNd+Ua9CcjA4pj+6Q4g9imBcKqJBHz5Ov1vMkELSiApZfhVGZwTWDbG9a",
	"omwqy2qWHde530Cw4Tw9BhM/b2zPb2jmVC5te4aPxoFhTmPVKJKu/hDogBT5pNDTD+dvdv4OhgkT9lDa",
	"pspJIIbOThNzP9DtXNxDv1U5COOIRsfo7beXu9NffYG7lmCpltzdNCNPpImLmgahMNZkAxExLm0yK1ZE",
	"0AQdvZqhVyZCBwjvxURwri4m8VvCU9I5dU6E1YEi3XaG/g8vgHiYxZhQ/JW+6nO8ohnFAvFE4cz5MmQE",
	"Q1TLr0Rwl2Lx+d/+8hc4PmzcrBK6sh1MEbxYn7+8eP5MUy9V0HRXErXQ/1E0uVqjSxvYg3yVnRk6mkPG",
	"IA+xqYnEr24GroDep0RpADC9vHjB00K2Jlk30IKcwPdwUG04d+z0/2G5nMSr4Wzu4yADzrAAocrQgVYv",
	"/PnUj1352YkxH+0KNwsVDclILwcW3rm+xgeXkAydnGBwdPmtGVDpqUJLaCUwfJG7bYPJQ8MvCbOUjvzZ",
	"GEM0xhCVMtNmcUOmy3ZjhWDMuKTlP1UlLVNdYrzJjy5plQcxSNIyNHuUtL5WSatfjdMIW76EwipRHg4+",
	"ARtaTRRTBs0/TDGcDqtJzPo3t5ryqDToswOYVvUsI7DlgZlRbBrwEyISTaXaqrrYZprXtu2cOHaLyeZF",
	"1rexsuVdNqfIKtc0szMUIpStz6sdnP8zlRaNNEW3rs3gws+j+KPoiqTHherbJLSDge6yx1sn0Bk+S1dB",
	"ojqMp/YyxlBr6nPYBJjgcT0A3CCy0FQQfxV0IbB7xgjDo+D0bRCg7wz7qfq9w7ubBG8R0hXc0hB3CVIg",
	"HcgdAd4H6Lgh4+GhXbOYR1893dyYPPuAbUDqA1RsLJjGagKJeIlL7xmF7/ZOt2NqqGTCUrLpAZdQ2Pyw",
	"qxa7hz9ka+F/0PtkuaD7v0k1S+rDQ9c5dsTAK1wTgRVZRBIF2DG0GAQtvLtT6e0FqY2/vffXp/rk3Pm9",
	"qe98wDFGwzibbTaL4GxwEDVLiAmB/LaPJ7EMW1lhw5AVUxi6BrDO7F6lZia+1Y6gaNhKbyC03eqwUhmn",
	"lcYQPFRWi+qUMCulpQIkbLlk9mutiGUzb2QtU+G9KciCekiNdLFxbVY98aPbbytid2L0rVF5cEkRaD1F",
	"BCwkOMvWiJbSRnA1lviagAUHYtDMGwmJ5RhekEoEGGUIo5tlm0VxszBjf+J3r8iRNrLUblLD2ZOqQSqu",
	"KrXaMK75O8KIoMkpybk31nTVKcsjwfp9XkpmaOeUVogWMfRpzsGteg1VOxV5Bkm/jVvTsLKwemjbJrpX",
	"qiIFtBqv84KqU72deD4E63JlYjO/o6paOgqZ4MFNUoO6hKCuUjBdOApUenVFOdMSOv3PazmUV13GuV2g",
	"46fkmnblhDBf9aILV6Oud72N+nB+8Y1Zp21JTqcTNojnr9VX618NM0y0PfnYxN9zfnWQOGNrac+sZSSf",
	"d5YKMkXGbSnJFVGRjJiXBJFPJCmUSUgxiBLptXVSI0VXhLfpmb7odJ3oiXxSzdb5ZPWkmq0TsxQ9WT65",
	"e8bOz7HMwMNcaEvsOC3Y5PNHsBlXf4yk0Lz+EYu75EJ5XVYZRddYUAjHuyLrHWO5yDEVUFzg30bMdGlg",
	"C6ZhHM2yLQrW6rS00oCuYmhYuQCzNcJiUayAcygkSLgKsxSL1NSLQ3LNFP6kkYf6IqPm3CVaWS9eN5NE",
	"Oc1BNl5AarypxigK13ttClO6RaBCi84Io0ssl2gnMX5An+KquRsurl7RFjcO/dGkeHbJms12IR2ryYBc",
	"MObsQHahA0hdwVpJSnlt9zfBNd/tBKvlcd7rAFHp8/qTZvBMgcXedQWNm0ZOhoj/HBA3ovEPSipwpERB",
	"9NF5NiRO82wOaJJGTy225cZ94i1eVD5K9ql8hvT84PKDFXiQkczW6DevsN6CxIpK69oEv/qlD7c8Vpxz",
	"IgS5nRvA1lXFswXGXw6BCsCjpQc1cMqJcb2/I5hjecanGqpRHFEqL3MDb1DZ9rDCLelFfn9+fmKKb2hK",
	"EGHj8SwRkbfL5CtGzvtPcK7Q4UEUf3Is5Q0XaRsDZr4im97AaPsj6/L2Dz9eLBzviubG+PsjET6LfCT1",
	"xRXNLaNrmUZ0HXSIJ/tUmRwEjPO3ZyYli/M5HLR0PfoVWQ8f/Yqshw/Or9pKBMKn7UC/kES084jua+9c",
	"AxzwyhvQLU0slcoHihPMrGSYQKGpwkmUjOhfnQhh5NAn0hARW2dL8SDhqPOarZdXhKVIovGy5O9uBFWK",
	"sDuLI6IpjjhpAtvK3WuWoA5BxZSjjW1eeA/gD6dvDalM+EqT/LmyKXYvsYSvM3SkUIKZZWMI+qUgUKJB",
	"4BVR4HJTJEuE5T66mOxqirir+K5z3fgntH4Jrdv8NltFHn98Dy/lOIxso+u31AUsK09CJzdStgxCkbei",
	"QwCshXPnKMFZpt/NJOPMSKlRTIJYdlMlpQWn9HgG3wwryFlmCnq5rpr9NX4PVo4vjxqK0QuJVpDLSCO4",
	"w0zDAIOcBG+XXbXjNy/X7oCtxxTSZ6GZalgJkZaPhpw+S5LlhpYpk+zH7siXplQq9y5HG+lRpuG5xjDm",
	"aIUXpK02+mDX32CAH3lWrEitxnlD0F5FXVBOQ3rqqBumjAgEPUquKCwFj5OrQaVXzKTRrMdxsJwUWVYq",
	"vcvCGUfz91ydGC1ro4SGq4pYdQ9/EvZ5MkP/0uKIJAq+HWQ3eC2fGDd3s1EqUV6AIUCT8DWI1bVe7/WX",
	"SidgKXEmCE7XiHwCtzvWUnzTzDmZ1jcDow70NNfw8ePoP2pj6Z/seA6kEezYb0WOzvDNcjSXFmHgcVdW",
	"0hbp86qSCcc+ccat8/jwaAc0KRQzZSGv+RGh6BwnEQ44r6BR76YCrIMduVRO3belf2FG2S7IgkqlCRuQ",
	"nxVea5KFGzdNd2TcZLW35szjwyM/GMjzGdeUUyKrReVi5SmobmsGkmE1piGvrNtv9OSgLuvDkytTDraj",
	"Zn9IkCxLNljcDFZThk90Zzu1CxpIy6DxEGa3f59G+tavMwSWNOnLYAHbuZLXZev7ZZ5aARfLiPCwDgCR",
	"jAwx0zwRgot3bWnI9OzQAtlEKy6nl1N7zTHNChFnyrmgC8pw5tMkDgqEFUSJ9SEvYsF/7ytOkIaYKiyv",
	"yuoYujetKDQGuSNWoFBfed/ptob7P/xBN5Nm3MOZ526SL+X0b7B0B48uyZwLYp0fVlhcGU1YXgLGOv7c",
	"EUWChQ7Blx+KSyIYUUSekUQQ1U04t0W0phMJsw01YJarRKZjxOFBb/mWmoZKaRMzQaBNgJFbVL7DAFKu",
	"OTqAzHHSMQp87h0q/g6Uw08DCPW6aNje5SHFUAccWeIhSuVDmlKpKEuUTYQ/RTdLsIrgZIkoVDGXyKjM",
	"lLkQF5Mrsn4JpqGLiSmHTj7hVZ4RU3zN25Je5oKnRWJTY2t+j7OXhdwhWKqdPXC/JuLlJU6uCANy45/s",
	"3tKKVRed2O6gMqTz+LFxWPCbUc3wazD12CDLMpoIGdyWRQYfVlgly7emQoCJelLJsjRlGNPiwftXJJ2h",
	"16tcrXdZkWW12aXphjQXa/Od1W5GbdQ+mveu3h6KTfqV3qkqwgrneuO/XZH1FM74s7H/xasaNFHORedE",
	"g6/0lyC3p3OBsvaSNVNLomhSHkdpmwgthBpzzXFcY0F5Ib0nESxDztBBqQ3UcgUYN0DZwk0Gut9Kp6op",
	"cgv7HM8lQFkRufrvjLii8YcGeZT13xhldEW9xFuGQwB6e/2oMThTX7qrUoCCCGBMICIeIOSLcoZpmCF1",
	"K/6lID4izyl9FEdUSvhgRCdX4MhKRUHUGDZOUOAaRaUhC+BIrF/Fa6NmYuSTcnelLA/qwX1owGQKXyec",
	"SSpBFQxj6WXZwDPrl0McyOxOq3pqvW9niIKKuQJyUmuRcU5unLnenGmOpdRXz15aOHHn+GnUYtX63Maa",
	"DPt0R1vLaE1Tkzg/c5CykLaufFRADUhIf0GmqGAZkRKteWHWI0hCqAelNUdAinlWZYxaFN8rTBlliyNF",
	"Vi2cTD1q6VLqg9VSNiCXXScA3jyYmkBp8FvNtM0a7g7abQVSHfieDlmcKJ5aggZ5DsDa7igbKH3qeO73",
	"4RYlUWEKrwOeGkDqYRzQMzJXqGBweViK+IqqwM9AEkFxRn81cntloUFgA3pqkyRckgQXkiAKn8H5b1kw",
	"sMfz8iuAwKaLhxr+0OhZuR9BLOgMBtb3ZDbi3Q9utRMX2smzFOwJmKHrvdneX1HKTdoJooI5DJZrhpPp",
	"Y9Sb8EaQOt7onf2ZSEVXoFT+s7lt9FfrPpnwTJ8fLMJUSvAxwXpeQYBSto1tdMtADYT347D6piGRXY03",
	"493bdzwl2VgdPKgO/u4t5BbJUCro3CCTtbljFqvUAI3jgSzvAz7XD2ulHDNhC+ssaUoSLF5X6rc41fNS",
	"qXx/dzfjCc6WXKr9vz5/vre70q9G0iznDOYU/+iEi/E7trO5TC2vr4EUZ2t0cPRskCn1o0alKmfUlI+i",
	"ZulzIAK2lHj4EFvuEXRqoG2Ky6vgodFWa8G7jZQFMeEtAoatlv72SDPK77mC/77+pPmcyXTyihP5niv4",
	"OyqVm5j7ln1ZNt+0AXx2YZhD2e0ammsQBpuOgF12yRuGFy79fYbH4dcP11Q4PzJd95pCgsl83ktWvigS",
	"sTGN0+APQgQaSy6/6UehynHjLNNUBdi1NM51GybCMg9QCd6xfaawh2lrdLCRzBaMcZOJ4i5CSdkYXh3r",
	"VxAUrWm8KIlN+39OV0QqvMo7qqbqsWzehRvNepo8RcNLpaa2HMCmc1mOITX1BYbPtyCMiBZfoANk2MHE",
	"s2OVrBPY20BQOUpZiQ+q79nQG3TC8yKD8iwO3qbMDDolON3RwtTAePE7V+p7ZyRSm0zjiqyd7GcIGvhl",
	"YBaKPlwsMNPcjm6npasFF/rPpzLhufnV0PZnXoaZ3Np7wiZXiT4MN4xEtRNB1g+sEL8Bl26TWA9+19Iu",
	"uoAkFrt6rouJVcG0yA0VySfqX2nlxLDGhhF15tSZFoEbfSKDbC9lqcYyicwwp6Z69ZcoDCoKxDCaoPZk",
	"j1lWtpdlZRhO+7NJO4+9whWYhCswfkwXeWzupCdcYwqkMZnZmMxsN7wW0YjNzqxGfRctrvuvt6hmKQu/",
	"jsnKHj9ZWeM8BslKFXI7pi77WlOXNchH52WH+PvS/KIvW/C1eddTKvMMr+Nqpe+huqOv3gbsg1zyGxfO",
	"KeKwIp/M9TyKoN9r+w0dvfLcdW2BA3jPE6ySpavMv/9beV828EHujQGCqsRGIRcqcHBqEubmmbHomtS5",
	"kESiRXcTj+A5QP/r7Pg9OuFAzSCGp83nuGjh58zV1bx1CoYUu6hZA/l43hUoWyccXYnbym9OtW7JiBFe",
	"qnQkyOxmWkU3OKA0xcP4ynQVgfm4vSgGkMxusPSUbrNcJcGsscM8JRlW9Lol3uM0TD8sbFPjhuEQcEgs",
	"+kGkrzMnOCXCe66s8IuZ9RAGPNHtnWaEXxMRxIl4H4OJFMkuZSn5NPu3HEYSKm7/sX37rw5xw+plohKO",
	"7hBiQZV1ao+e/2nH+VeC6AOYf0dViAvg+YoqqvORHxslp1Fy8qE85qJslgs66LfdhNDlwHGxq/q9KnT5",
	"b3RM9f4FyFyidhyDRK6A4o8C19cqcNWoTsclrwtbNTenKlMxLGNDPcdSb7aGMAizr/GZXJZte7bekv2r",
	"3mKzFGBViNwxBVd1sLvm4dosFZaz0x5kRKjTIiMxESXYwW0quGM9djxpcNFmHXzlcM/xuHRluOzAtxpf",
	"E6FFskJaKY5fWu9A6x4PE2tpDb2B89zvTs7Tn3anK+XOxUX6n21ZdqaTvCeHeDV3uNmRce4QdLHQhDIG",
	"SWM4NR7w10RQ1Z9oMDzvM9vJV3mqpN9zIwbHVNlH1fbZi1yVyZqZIezXBs44EaYs9h7Ugj9icz4w7LJ1",
	"LeXArU2CGVvbmKUEm/4h+oie+ndRPxuIfNLCe4quKYZtH5wchZs+1PgLblfkjC70Mp2uKFKr3dcydgVv",
	"K+XPazVcJ9PJeWuC11AyrLhxWEVba/3nw5MPrRQrL2I+IdPJKyqvWnMEUnkV72X98Frdb9rd9JyvTWvX",
	"Vk+cZuXZ0EVmcOnZFkj0vXld6+rJtNgCxd4Z24FYr/RZ8RVq4k2c/+h0KuyysmP3WMWct/QrCI90BuKA",
	"bjVDx86h3vyag/u7pThUuuxvG7DP9VczwkVLvMozyhYQuXYdq0PgH7lLom4IYW7/CLrqdT/Au+XzxHWk",
	"iGs76ml4FJEddz0KQIVa6aP+WlU4VXwwIDbCOtyb6Fobp10qJ7lJpwLhAZbmgtBJR2PhqJwalVPxctyb",
	"qqeCnttWUHXUCG+IKCYGpzeg1jQDrzGI9nMOg1SiCt0xGBAviKkPmqrvsYxYE/SvjoE1gRrQ+OHqpcSr",
	"9LcGR/cCDFpJyIFWaOqzOcC6DEABKKeVI6wsrw87nAJzpOaPrIa0ndcs2ZiPAl5gVER+vYrI2gvTyfbV",
	"lJGurPVT+cwzdSZOsVML15N73BflriYZpayRyuxIt/QtTOaoskN57RWmzATuxvhNk6iMcY06rjfVd/o1",
	"TpY2fUB1KOPn7gbQCw6Z3u67+rBpCYfkT3ce+z6PehPS95U+PcKldOPfLfTBYf87aoTx7UhpZy50pxg9",
	"hBe3LajMMyxoqRkZ796h19ESducG/q4j0MMPHsRxRMbetNDeQMX2IzngVCaPcmCM3BzHYy7ghpIbU1od",
	"PaU+UdZlRiC8kBUZRLVP9pUoSEzbrK8ZL2THBK7JHWaxz9wbSrK0gzOAiGAb/AJJzG2/kgSUtMWjuoOk",
	"CUvxkTlWYjD/mfkiOfbvSC2YgXGCFb60uq8ocjWLtsWtGP4VW/IbeL2grS//orEpKInUpVqFykhnNmKq",
	"jQhUGzX1la661XBlZW3EDmCEOR8jlbXMZ2fOcdXJcvNrvRZN/YpCIK+5TOdlWYdOnWdRJiJPm8c0oBZT",
	"/XA/w/mIAvb1bZEuSP8i6u3LMq/nS0Hkkmdp3xiBD2PcXayvstm5cW00Vc1ACOY0MUlBbXE+6faob2T1",
	"ZEKiVkWF2BU7k8st5Uc/O/u+Kz16Lug1VuQHsj7BUuZLgSVpz3NuvhsVqVye+L5fRnrzypJ605DbnQOA",
	"hmcijyFOaEPfzOFYhsfcY6a/p5THevs1D0SXALkr8XFXyt9yVzEi18Y4WmaRGg21KgSz0qjGtgRnmX34",
	"Us6euHzjyKS5CcI5R93F/eou9N2JnF2xWBAIJwe/VXs4uq1NmUxdtqYpeo7o3CU6qXOr37yIagpH5cVW",
	"lRcteRyHOKCUkpqBowuMaJGdsYx7uqxwsqSMtE51s1zXJtAHbbnci8kbk0byYmLXY9MDUVlmyCKrXK1t",
	"Rh9ICFQVPcu8WgfoFJaJkgwLExft3K/tZgGNLwtNeYhJLcSviRA0JahFIy27SZwLcvHAQ8eQoGwfXUzO",
	"DFNzMUFchDu9d7TRbP8OZumOBWkvyY/psOzGLZnwGFAiXexBOO8t9lor7loxZobh6r4o5/gSjDbJ0SYJ",
	"PWqXZzOzZL3zdi2TtdHj/vORRlUn+lqDkQt8fAtW7EgGqV7rT8FoyPpaDVkxstR39xu+9ZW336pg2lkA",
	"0InFhWBTN/pmyWVQ2Nve9zm4DPN+hsiMP2SznvYOy3IYVvZuJDfc2Ed+w1oJndYQi9UHqiP7VSWJtwfu",
	"DZbGlBFEvA7JhLWJ6eLjtAefbmGe8huwuDeD86Ur8l/cVa5wuRLfcuPoXFuDhsmvnJEyE5OQ1gkRZjs6",
	"eH/gQqcPTl8f7L49Pjw4Pzp+73J06x+rPLDJaqtPmgvEE4KZeUNcT19YF6rqYqFoUmRYIEn1SVC1pNaO",
	"hAXBUxDZbdwtOlgRQRO8+57c/Pf/4eJqil4XGv92T7Cgzh20YHh1SRcFLyT6ZidZYoETKJbm9moyZktf",
	"pffpxeS7d+cXkym6mHw4P7yYPIuSJ6OnPkuWJLXxFHWjQPliS9vKFefj+hgTlPIblnFsa8ymFt1kmFha",
	"0ZX7ym3xJGRLHkd4iV5V9aGo1kgFXkuo7wROyKsgSmOozl0FyNX5drp2DRodJ0oBS1Td4nUbr/QdVSHJ",
	"jafja7mobtCPn02RgUJQtdYnuzKTXhIsiDgojKuB+euNowf/61/nmo+E1pN9+7WcEqKxoYLE4qilSOeH",
	"D/HkEpVUbIEBDaF3OJe2sFHYoUymOGPYlEGmehLIL+8yYe3rpfw3DdTHOKc/kPXks969JjIuzThOAJ/I",
	"CtNssj9RBK/+5zyji6VKVDajvBxR7+INfIHE24Jn6Jzg1cSqdieOfaj0bmTV+6k6xMensW7PLCdlztba",
	"N5IMCxPev8IMLwiUjeZz83QCcSTpgnh7nE35TAWURdY3UJqiARlNCDM2BruzgxwnS4JezJ43NnNzczPD",
	"8HnGxWLX9pW7b48OX78/e73zYvZ8tlSrzNwTBXkCakA6ODmaTEucnlzv4Sxf4j2bwpXhnE72J9/Mns/2",
	"rOsD4KPmpnav93ZxoZa7idfRL2IcxHdEQTlQk0Pc1WAq7TAznziVcqYxdKLx3KrIIZEfZOOGeV88f+5w",
	"w5ZBCUo77f7b6tPMne8t7FTOAohXSxHzgwbBX/b+vrX5vHjYLDBQgMuO8nAhKUz+4h8PMPk55+gdZmtk",
	"o3uMAKvwAqKZqgdn6FPl8G05RNJ6/D/aBppU1NAAcsHHj9/1AqRzBUOBFYxUdY6MqmmTW5qnQkuCU6CM",
	"7moVasmFSwg1DUBZp9Yf7xEPu45G7wS2AfjwIJN+i1OHCmbSvQfbKWXlXv+QF286+euDnLGrcWVFefRa",
	"CC4G3/ukDBaUJljQSfWtRABUH61BhlUnwyox0D1bO8o+8gBJXi3T6htq2mAK3jgPR6gD6vUXtih0UFPE",
	"skYwgh4A8jubnN2q3uiJK6LxxJZBsHYZ7wdVrTHRwiH5IitdVGkaS3Vs07ObcCQlaKLK0hDgPm1rf7iM",
	"1SaTMRW21FG1MCqUN/UFemILzSpFhx5utcbZa+qkJqhkYbOvaxBfEfTk5ZMpevJS/69mt5786eUTl0cf",
	"qjXtmXJNe9Mrsn7xJ/PHCytrxXYKM95upxqTVvgTXRWrSkkQg3h+k2GhkrIIyXlZFAayQJkKGO2IVumO",
	"6LyK5ZBWygxaq/aywmtT6OPSlwW1xd78xYHYt6C+CkCoFTPoCrJBlXDqtWXf6zvbSkVAs97OAn69r+4H",
	"hi0HZN+95988wKxvuLikaUrYoz+1D7HbMysmfmDeql55aFsfUwhvznnM6HNoqrviAS9q80E1nbsC/u0C",
	"vuXp+v4vn4FZqQtRoiCfG1Rg76EWEgN0OpKBeycDzx+CDGhpP6NGvzcSng7CM4jZ3/1NP/SfDXnKiIpo",
	"oM3vVUKF7LVDJcGpEqhX0KmLQPVqBMKwo34aqblPs1LPykCMj+dkbF3RKpH68tQFjl/5w9CMvzzAlO+5",
	"Qm94wdKRaPRyK1HRXxBsyhuWMkXScbertOA7oh6YECyM2+3dqcB0UjD6S0FsKS7gax5HvhlpxUgrvjzJ",
	"BqskXvQ8Wd5SsoG+D0wucl83cFtsw1DZawem/s/NTrNSBmCQ5PXI9GkUur4uojjKeV8YGS6iLBtUxahx",
	"bYeDubZT0/+BSXGZG+jBafGD6cEelRqParjxRRhfhFHz5zR/uzjPBbcJR6MPyQE0MKmPCFt38fVNdt64",
	"t7Z2OHCTb+0xMaXIwwWPj8nI2o+EfCTkv29CbpyOMWRekbuCyMKULowbl0/hu/dUvsSSpIgz4x5Ueuxg",
	"lu5y64bjf51FRAE9mgnRkfdkWzajm5keiQBWl2AmGWnf6FLyKGShct8nH6eTTzviEpvkOzYxlQ1Nm5R1",
	"8sFaC7fUUYjPTRrS4+BpbkGfN2dJDEbXzdF1c3Td/EpcNyM4YpOPoXmGFxpPTFAhMclr9WpWKyzW1chb",
	"OUP/0jsBUHEEkpULPjNgAUhW8uDCzbeDBTGqNvwSAA7pHZ8YbKrg/ZMSRvUwzBu9jid2YD3UE8gqKIrW",
	"qx+0jWGZT8Z2r3ZgQ19Hp9aRA3lkDmSIB2uNZWhzV/X1pu5PfnhoR9Rw1lHdPXqd/sEoQ1O2GOBP+sr5",
	"k/aSDdPSk42NNMS1wUf30FEFOrp8bfrut6cC6L+83xG1tZu7NX/Oh2Dax2s7XttHZte73TJ7ry403Nrl",
	"Hb0rt0hARklitLeOwsu26GTM3cV4rAwhk9ZDcmuE8nfh+7iJnuXhCOOo0xkp8UiJvzo10m5KoMac9Fkc",
	"YxTbp8UsDVBG3RP0baqWyo9bVDCVg/4uyHgIhZHXHSnsKKE/Mr3LsFSSENaZh9MXDNctIY2vVHiVtxCm",
	"Ds3cWyzVmZ5tKxq61nXNjU/h70N752HSwWv+JVIFnUM2Vr2IkYyMZOSRyYggLCVwoXrIiGsYZMxv0IpT",
	"22ab2vzY5M7pKfGFHbdFNaatRYavGL9hfiE/unz3cccgaHxabTv5Um0NI5UaxcmRLtboYlkRqpMqhsUw",
	"hnNTZ64w3GjtHK2dIxP0ZVg7N77Oge1zaxd6tICOWqGRko2U7C72yI0JWcU6uTVSNtooR9I1kq5RxvuC",
	"ZDzCBM+yFWFqQA2rsnElyCwm1b32TX0Zq8HUEw9Md2XCYKGcH0NUyqKaWBWKvueCX9OUpNOwGp0NoFuS",
	"5ArRvpwoNs5OxieBeDqIXaQSJVgSH+JHnZ7OxkfWIQKVXnGWIa6WREDfqS0e66EcTmTCJGHll8SUr2+N",
	"v5Xi0VRrjYMfSfrIjf5BCGx5c6NZSBqfe5IJlFdpYJWoRocxxcCYYmBMMTBWh9rw5R6rQo0B9F/iW9oX",
	"S886nsy2uPpGj3sKsW/O88DR9i0LGJ20x8D7kTuPcucbhONvRnlMrxjl2UjD3D7lGLA/yuyjGvZ3xdm0",
	"ZwvYjLZUdK/3Qlh+Jx42g/idkcCMSsHHEWQ6swxsduWh0z1f+tEL534IzyhjjezUyE7dA33tyk6wGXm1",
	"vkD3TGB/F75Bt1RiPQptHXVnI10f6fofT113i5pMkfeg+QzYXvfwDPzuqi41tuArUT32c+AW0q9SHAn0",
	"qGYYyeWtwvrurpC8nUf9qJYc6cVILx5PLXknMhBXUt4HIRhVlaOqcqSAo0j7Nagq70Ry2xSX90F0R/Xl",
	"yPyNzN/XIixe63laRcJTogQl10Qi7AMRTJfZBYsHppgB+4JR/jDxDmdcKMRFSgSEL9rifhB/oDfkkv9V",
	"Y02e6DGeoKeM3GjqO6dCqtbFweCVRaVmKKhyKpPJdEJYsdLIgOEv+PHj9LaxGub8zbnpI3LBFn1xPNup",
	"s/hVRzHdqzZCH9sY5zHGeTzeU6QxsPr8zDNC+mIj3+g2ffGQb8xAYwzkGAM5xkB+vWWWj2zGhbZ6ym7T",
	"QFfaVoJTm6NVnplBHq98MZCt8VEeH+VHe5ThpgwpXlx9httiLKHVPcVVmrEfOJYymHT0ARvjJ/9YRKHB",
	"qe/+Bv/9vKvIKs+w0gyhpJy1s/DAfrjWyDeP8fDnttWPZaNetTW/YYZ70q9+Y5oWJfU8IFK3zIw+ShKj",
	"JDFKEmM2FU1na3RrZOdHdv539HIPSH2Q2tQHjQe2Jd1B7ULc+R2/v2e8bvkeOPOYU2E0L4/m5ar6IMr9",
	"C4JTw/r6d7+XhnxH1EhAHpKA1KE9UpKRknxRnMvg3Ey9SkrT0CkpN3KKqw49pl0aL/Z4sbfBIkDio96L",
	"+x1RW7q1Wwwe+mOYJ0eyMZKNxzVMdiZQ6iUd0G5LxGMMONoe7Rj1oGOQ0Wim3RKJ7MqB1EshbfTQlmjk",
	"7yI+aANfkgcjiaPbykiCRxL8dWmt+nJugIK8DPusqsodQY6LwreL7bxXgXiURUdZ9A8si9Zrzw6XTLd1",
	"l0f5dJRPRyI2ErFbSIvCCIEbMiOh6LgtIjYKkCMPNJKP34GkYxy7ByWPSKlUlCXKO2Cbvj4nQklnSkqw",
	"zklblom3ZuYBpEaPYn2iPYERdmF+EYKv2qxxV5SlnfTG5VawZe2H5FU4QHOa2XiB+lo4y9YmYsBHPCO1",
	"xGFUwIJeE2bae0f3e/Gi38IqjQN53yq37gFfoptZ74Mkq7id9Es+4VWemR5mta/NL3CprQV4f2J/LP3v",
	"9c3J3DUAR3uT7uWaCs5WhKmXueBpkSjjQCfIgnL2spA7BEu1s6c3QIl4eYmTK8JSc7GH0RC4fKOX++jl",
	"/mhvEeB99S3iYoEZ/RXWsVk+o0rPGULHmrYZaiGrHw2J0+SjkESgJZYIJwmRmr7E01IcV1Z1j5xhONF4",
	"Ncer+eBXs3ypIGkLryG+u7nh79ULLEjOJVVcUNKTEObUtVz3ZYU5Dcccc8OMEZ1jROcY0TmA/JUUZnxL",
	"x7f00dhc/ySuhyRoiTyLbVlayqb3lKolmOCB87XUZx69X8akLX9AatHCWG8SSzWInpjWFXqykfUnMskY",
	"WjXaZEabzG0YhI74qkGX+Tuitn6TfyfeZd1sw3iVx6v8wLx+d8zToOtsvau2fKFHF7MtE5VRDBmd8EfJ",
	"Z5u0szMYahDptG5tWyeevwvXtk2VNw9LMEdl0UilRyr9VemnrA13zZJey69perZmSb/tt2w7Gn9H4+9o",
	"/B2NvwOZgpJwjObf0fz7iA9m+TAOMwBHXsd2E3DZ+N6MwMEUD24Grs898vajIfgPSTfaWO3NbMGDSIuz",
	"BldIy4Z6k8hEo0V4FOtHM9LteIZOm/CgSw1W4Xu40b8by3A3JzFe6vFSP7gg0GcdHnSxrWn0Hq72aCPe",
	"OnkZZZTR/jCKRduloj124kFE1FuK74GM/k6sxZtqeR6aeI56pZFmjzT7q1Jl2UpFbcZiLd9KO3RQiKkh",
	"15b1pe6NRA0oqjRaVh4arRz+fIS+xmhqXupCZJP9ye5Ev5a2dR25jh0WmexFmhISpuwWZkEdj8qHSdPa",
	"GwzEGTokQtG5bk3O6IJRtrBwqzo6OLt/2Vqa1sI/At3zmDxF0UFNlZLuEfSWTTuEE+WKLFcGsL/3ruQ1",
	"EzzLVoSprp0S32rQDvX6bLYiyhaIXGuUCYfTP/QurZqULuxv0mBtsgSbgggngkuJUjqfE0FYfHST2GST",
	"0cPEH9EhKxkX+vbdllrBjhW48PSP1Oaq48cKSPuAHSeEwoYjdN2O6G7154+f/28AAAD///6WTTwOcwIA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
