// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9i3IcN5Io+ivY3hMhabbZlOSZiVlGOObQlGzzWA8ekvLEWVN3DVahuzGsBmoAFKm2",
	"QxH3H+4f3i85gUygClWFejRFUrZcuxFjsQvPRCKR7/x1lshNLgUTRs8Ofp3pZM02FP55eKllVhh2Qs3a",
	"/p0ynSieGy7F7GB2ynLFtO1GqCDUtSVLnjGSU7NezOazXMmcKcMZjJdHxzlfs6q3bUKMJBTHkYKYNSN6",
	"qw3bLMgbaRgxa2oIFVvCPnBtuFhh0xueZeSSEXnN1I3ixjBhV8A+0E2esdnBbP+aqv1MrvZpni8yuZrN",
	"Z2ab2y/aKC5Ws48fy1/k5T9ZYmYf57PDPD+H32LLtq2JXMIaaZ5nPKH2K8wris3s4CcErmaz+exfBU0z",
	"Zmbvm/POZx/2bPO9a6oE3VhY/eTnPSq7ux/+tx8F1+anPJLCMGHsMmmWvV3ODn76dfY/FFvODmb/vl+d",
	"8L473v1vecZ8p4/z/ranLKOGXyMe2MaK/avgiqV2oXCo71uQa6zvpbj+kSrEghpOsOoDTVNu29LspNak",
	"cUrzxkG8FNdcSbFhwpBrqji9zBi5Ytu9a5oVFqO40nPChV0XS0la2GGIKoThG7Yg9hyv2JZQkRLswWiy",
	"JptCG4tOl8zcMCbIM2jw/C9fkWRNFU0MU3oxa227A4U8GE6UvOYpU2c5S8afVQSO9hTqgKQVog6MBc0+",
	"zmcW1zquYzUhsa1KaDz7///f/68OA5JJsZoTbagy5IabNaEkY8YwRaQiothcMjUH2CVSGMoFEZLcrLlh",
	"OqcJW4y6hb/OpGAjAHW8oSvWBe4hLD8WGRfdvd9/fN9/tmeGmkLHiQV+s6SCEs3FKqvD2JG5lF1zBImn",
	"HieK5dQRiTMLYvznaSEE/uulUlLN5rN34krIGzGbzyzFyJhh6XhCU99BOGfrY7CI1rdqVa1PfpmtD9W6",
	"W5+CjdQB/aPMCsTc6vrUwf2CLblgmlDA3pRcQw9SaJaSyy08V3VqXb9K8YvxTvB/FQzvg6P54bgW97mI",
	"PQVt/A7pJ0z2/hNxHkHSQtgY3JokqL513JFu7/4V1wbwN0Bb19jukRu20SNoT+MMq7tOlaLbQfqJ3RA/",
	"+m/ZnRz5m9ZZR87THueSKSYSFmOS3CfL1OAdzzO5ZSl5e3S8Z2GUcSoM4fYULcW012tJE0MuaXJlH6re",
	"uWO4FK5ngGTps2KzoWo7knRlWQhE3U22vmc0M+vtbD57wVaKpiyNkKqdyVN9tdUcnU2CyTvbRChTvUG5",
	"XAu6wqyPpFjyVRtO9pt945Z81UYvWpj1W7Wigv+CU1Sj9F6Yjm4f5zBi/MBgIRayUVy1/d6dvuro9u70",
	"1TCWlVNXo807dxjFwG5oRNakLPfJUiLDHg7Sheq4z0xYNjDFIZe0yMzsYEkzzZrc4/GSGFWwOdFFnktl",
	"yFIqcpyekBzpZHNerokbOwDUpZQZo6IFKb+KGBC+oSaJSEPws52FCsIyBlwtF+QSftbsX4W91+39ZnzD",
	"TZyZ29APfFNsHC9maUzOVMKEAYqzdNdXWwJV5Ck1jLhnDOa0U417iE7KUeH12nBhp50dPCs3z4VhK6ZQ",
	"ONAsY4mRaugOvKKXLDvzjW3HIkmY1udrxfRaZunQAOG6PnYdxJmDbMeB+M8kdZyFhU/mnkSAEwLwkhH2",
	"gSWFxVcues5Ld853WB8XZwS5aPxDi7j1cW4P4Rg7PGu+tHN7valhq+3QaKcyy2RhznzzJpaX48TQ/Mju",
	"eWkpKzvjK8sfntqt6wiydjYlKlA1EOV+tBfVctMrwVKSVH3JUskNHNDRYYQS5/xHpjTM2AL9ybH7Vjvn",
	"a/yNpQQhghwB19WyHBe/tJcWt74gZ0zZjkSvZZGB9HPNlN1KIleC/1KOpj1nYKmctpfdMCVohsIoik4b",
	"uiWK2XFJIYIRoIlekNdS2Vu7lAdkbUyuD/b3V9wsrv6mF1zaI90UgpvtvhXBFL8sjFR6P2XXLNvXfLVH",
	"VWIFssQUiu3TnO/BYgXi3Cb9d8W0LFTCdPRFueIibcPyBy5SIGMEWzrZugSZZ21OX56dEz8BghUhGBx6",
	"BUwLCC6WTGHL8qSZSHPJhYE/koxbqqmLyw032uOLhfOCHFEhJIiySOvSBTkW5IhuWHZENbt3UFro6T0L",
	"sjgwN8zQlBo6dCffAoxeM0PhJjtevq9H5+1ywvFMl1z17YbB7i1mobpvDlWCTbqV70Q3rCCyA+0AuQXw",
	"0JPVzqYTsbh/YlE+X3HpsvdsRj193e/Nx/YLOJGuz0C67Fkj4dqNVODx70QrvI6jfr7/UDTPmRW1ZSFS",
	"QkmhmdpLFAMx4+jsdE42MmWZ5f0FuSoumRLMME24BGDSnC8CfkMvrp8tepcQEU8+5BxFlzOWSJHqmOYA",
	"+qPGuqQZ1zTjKTdb4H4AY6qJ7TRLqTbUIK/91fNZm/Wez9gHo2ifvr28Z60jbt6fhiLeDkyoQeRi2mtO",
	"LHjRauNhDMyZhXMu8wKlu8st/Hp4ckw03BgLe2hvd27pGt9sCmPlqYjaHREpylWegySj2V//vMdEIq1E",
	"d/LydfXvH47O/v3ZU7ucBXntOfk1I/ZlWpS8JmcZcPQ0xIc+hhWpQu1ILreGxS4OsLDqTVQDdSxSRDJY",
	"kypxAvsgwQdS9a+CZnzJWQoKyugFLXiE2L07fvEA5xQsQtNVTL/4Dn4HqNttAPVl8CZcsS3BXsH+nYjK",
	"tS7q3H/toRhEYLvlYdXfAwCmQQo9NteQYzfS16EjrRCK5rmS1zTbT5ngNNtfUp4VihFdKvzKXQbmG90B",
	"d8KXlVFWtyle0DR+R92QbXluXgGOSCuDlzAfdbsseUXxOcI1lt9QsWlPVoY3bUF+EPJGkCRoqBg5BNCx",
	"dE5eMMHtfy2EvqXcqYXGcSp+zKgWPMSGYAtRHCgH6t5gdXwpM5RnGh4QKRih9soZf9xJoRRwIMaeqedd",
	"LVKfBiStoXui2pwrKjTMdM67rIq2HTF8w3Cmcmmm7MtS5IvsuhwaGkmokGbNVO20LQO0Z8eKcyLa0ov2",
	"Kr4vNlQQxWgK2OTaEY53wvJ1Hjr0UhbGrbhcXpSgyUu47ul3TDB8p+O7X3hWZrEqWyJRqUPjhmqgfPbN",
	"SkmR47Thu/7XP0ffdcWojgoq5PGl4mz5hGCLinXwcz7So3Y6UkD0o3qB0I80shtapxs3wKC62a1gHkO5",
	"EgDV+fdelmEjUg1Gc0BKuSTnoC3+FnTJxBkHQtuH/T6bz6DBztaOxurcWI1f/dCNn0NDRR2abXx0fisV",
	"1vFQkgh24yndbD47P3n9I1PAY6C9xH9AGgh7tgSw3RT0tfwyY80/PE05oUpD07OtSOAfP1o+17ZA3eOx",
	"OFFypZi2h//Oij/OJp6zxDd9XWSG5xl7eyOY0rCua56wF8xKPlxbucJ2GncQL4WSWbZhwrj3NNhv61t9",
	"u51PcjBEZ5sSlp0tSiB3tqgv55TlUnMj1TYKegvxzg+t8wk/lmf1bcaY8acAf8RODU8jODv8ITxB/GXs",
	"OSKaL/mqadEeZ674jptI9yEnkR9K7v+MJYqZW3iY3GLW743JY90ABnnhT+W1FPag285F9fd6g82G3doq",
	"3YYkrtMw6xqOHnVr6Pc0a+8Ed6mkePkht7gUZ3SUFISVDQi+l/DU2bHTIgOtDd8wvbgQdpOuBdfk5z8R",
	"9/8/H5A98poLK70ekJ//9DPZOInw6d5f/nNB9sj3slCtT8+/sp9e0K0F2mspzLre4tneV89si+inZ8+D",
	"zv9g7Ko5+l8XF+IMjZMsJfYgqZF2EXu24UEptFruGzVVj9litZjDMFyQtV1yOR67ZmoLvz2x8/689/MB",
	"OaViVfV6uve3nwFwz56Tw9f27P9GDl9j6/nPBwR0db7xs/mz5661NsAFP3tu1mQDMMQ++z8fkDPD8mpZ",
	"+74PLqbZ4wwdpOp7+VsFEvsu/y3ociFeopOnhRx5uve3+bO/7j3/yh1plJU5KrSRGyQsx2Ip+9QhTW4K",
	"tEWo8k1JAgMRd8HcAUSnbIq7wSBcIDKCoAiMZ92tosXE4MLbi8Pf6+ayfL3VPKFZMN6k5J4sYpNFbL9i",
	"QMZLN67PLWxd7zvvccvzse2WF9dRNcTZ0DOx3wURZKV0G3/9vZ/I0usMLJrdrHmyBt0H9CSjPB3tNOAY",
	"HKGjb8pZfBviJelSQI2PHoi8484s7qP7cd7t7FjJgK5J6UcIl6yxrtv5PjbF4w7dT+nSZ88rAGi5+VF4",
	"VXdpi71qGht4/FmDd13D4TPi8VdHU+6e0l40DV87VLd4ygdKiNDB9E4UEv3+jm1nlgGoIh/eBcijQH9W",
	"aREQXp3egYqJlCmWdj7Dp66Bf3g7xx3SKtfn6d2kllknh+E+h4yGU5bAz4kUgiVOr1AedswJCpj14xdx",
	"QuQ+k+MXocqqMUMcMbDn6+DpaOB7yeuVs3hC7UmbXbczP3xdiyRJqIDXUqO2GJyzaMZ/QbVmGRLE1IYL",
	"ms3LNaN7mO02J8wkXcdF07ci284OwCuxjpqNXc0DAHYfZSg3twHhB3N8J/Uoldal7VIf3jpDQ9WKmXHP",
	"ZriUc+gXV/bhkOO2FIzTJuOlMQkvi7YztLa2YWYt0/qVClVg7wQDhQ8ouBIj1faU6dFxXH0rDkbua1af",
	"tYTCsX0HFTfbozVLrroIUnfb5u2tkyzue5DEdiE5U/ZGoE38lm/AXvQNqCSe5py4ok8g/d2bvx3t7xxp",
	"QIu8AzArrPOBMe+E9tJ/qGMtVXy74GFsA9VMfW3CNXS3K1fX3aRadxusnTp5x5x0oWjr7uYNCR5mSa3U",
	"Yba3RxpwYNqVxanQG9ibatEDzI1tXcKq/T7yjeUEN7nfe2Pwa+hZ8ajjDGe3ulUuMAyPyLPWJt98Cpxv",
	"fTHbixl9NTsfgECZXuJ3/Hre6io2rkXHlrpu1sAdbl/f6tq9otqcMSa6Hg3/vflQAKpp+8GEWEg771/W",
	"OVHbLOz4D7SCMuHdKqxkyBv+ND2o3MCfcgHdGPSKL1myTTL2vZRXHnE8BnzDllKFtovDpWEq+BsbnLJL",
	"KcMW1Q+7YEZtKa2pI22aq+kcJlxg1zjBmtvAuZXYk/nedyAwNtWj1eB3xS009no7RiE2SBchCpMIxCDW",
	"5gjQAOmoQd0qVv9lR5LUWHWTqDQ+11YR+R5b2kCzOnmKOnpX3+pe3fi7ntTbn92HOziJUZoxZ8yY3LN/",
	"a+7Z85lTCo47Qc913Z1fd8wf4AUzkMfjBTpqtVXlqFIcNm5jO9Aspdw22nBBjVQkL1QuNSKwp719K2mT",
	"WAttapI1Fytwh+i5LEv7HTT3Gp3BoGODER3rz9qAewCJ1oLGgvuUaZld94CbavTYhOZxiOMefUNCNZG2",
	"MXksiiwjfEmExF+e2M3aH+2z7zVgEUPqAx2w33v0gHPFrrks9OtdDtqdse+bbZ1NO73lgYM9QGZFt6fX",
	"9/LGK06XGU8MMNbKbSwEABrdYTez+eyN9P+Cfb1gHRlFelGusbZulHur44Ea4VeCny7dE406QvL2rFQN",
	"d+qjNlFX0PPaIJh+AQ1oalwUPI7bu6nbMMtvz0Zv4ce6McBvI/5m2y8v+KozRCKFb82x0P2C6DV9/pe/",
	"HtCni8XiyVjQ1CftARRctjXPj9ZUrD4PZW+uIXrlBbvpoXKC3Ti6hvSupG6KbeQ1S8cRN08aeibyTeKz",
	"CSnYmKm6L273SZXefzshdslMDqnpkrwYx2nU1+FVTinXV5/Sf8M2ciyv0zFCBnFjtx+i6fefF7NyXW6D",
	"Y0+n/5romnsfnlf9XlTpVf5BlZPfjhQ3PKHZrZO5xBYa5oppf60mj30NFhT77BcZ+xZ6S5ffiw0LshPE",
	"HcJcFhEqts65sq5oCpNVvG/myoMwsuDz+3k86M9KiAqWU2bnwHAAKQhMQXz2DCst7kvlAtT8rwtyaEjG",
	"qCXoglWNfRo3n9ukliDx18bqD2asyqz3da5kWoDFdW44U18vFSQPTJFohde4vsmYq4FfDu7SKMuXhAk1",
	"gowkDgqoBeRun3pB3mkfpmffbOfLSTWp/HMbINHek/CilD0WFi+/xsmezZ36KF9Tzf7t6xMmUi5WF7Mn",
	"Hcr5GqTudo8w+Lg91pEh2OMV2z5Ds/Wz+RXbPv83/ON5fEMf+4gKXAqdS6HZ4K1oYjN2Q2katokxNqWC",
	"IEA+hELqZMnZwVcf224S9RbdLkUlcC23fcMUIy5pzLLIsq0DeBrzKWp5TNSm7Ca+fQxsg32lPZ6YlafK",
	"uAxs7iKrW+Vga7igt2SLpCMrk18Ifr/FGqIe8LHptcxiB30e3COaGH5dOYY4j4hdtU/e3yUa41xXY+7s",
	"6QBBYiPX4SQhJ9gB1xShLnZptQfc+dzXk2KNh0HD6z4GBczAm3Y46uBHb6TRjXiBRvSBFSxPqDFMCd2X",
	"/gg1IblrWdtMi9qix7hfRyE46lTmmJFUKvivLAzRxXLJP8wJ5g5asyzb02abMbLK5KWfDNYPs9MV5UIb",
	"HxaZbUkmacpwCljThn54xcTKrGcHz//y1/nMDTE7mP0/Pz3d+0+698vh3n8dXFzs/ffiAv7vp4uL9/92",
	"cbF3cfGni4u/v/+Px/9zXLsnf398cbH4CRvGPv+P2EM1nF0RtZUnMuPJSOb3XdAD0bX7/eh3S2k7osRt",
	"PTpI7OiIJ3F9NxQs6TxDj9HEFDSrolc/ldY6oTwkuZWZaQf60nbxjdwx2nZU3Hn0hqPn+Pjn8gwAjuiK",
	"650+LRyjwcE0prO6Zcxz+N6MItiVFya4ZTiD962cF7y/xd0YqcnjN2/PXx6gIaGMDOGaCGmIYqZQopYv",
	"4MlIq7YVqVZy759aij2+ElI52d4u3tvUbmXj3PGFKvvU3qhdJd6d7QstzEZy78N3RgxQtS/pXroLyUs7",
	"3FOCK1ZbVf1Kz+I3PARjiMflfYCzqdZbQS089h7O9Nae3wGmr6lKb6hiYJzEEDTLyeNeSc1cePce4W4N",
	"PiHAXfiER0BzO0P/Tgl04+5FbyEqNJ4rN3TYOJFWkknfLpc1/6PDG8oNBP86p2iMDAdt/wkt9I4+ALUN",
	"BUtrfQtWG/laV73UPrWdUGqfa9uMfG96JdQ+xoARadaET3WcNZIyLiLwbe49yfE2BAmQ2Idc6orW0xUT",
	"ZnEhXtJkDWltEqkUyMgpJrqoGHi8Fs4xIKE5veQZN9vFhRiOLcRN1G5VIrMMyx+Uhu1OxsgustNjwr6F",
	"hysotYBN4kmGA1t1xxhBC8t7YHCrg1Mr8rEa2aJOLF7gGykNOX6xy1AYujnm+WhFi9r30hNBhHZ8l29L",
	"SnnmKeXI5TVN6CFASyi0VzGvH1833Wrx8APO8zm0BJvKhgq6qvQ4zt0BSmwkWZHaLzdrJvzv3h/mkpFU",
	"3ggnP9l3xKXcifjrunZnGLk9yNTgZsrW5eN+2/4fB8CW3sqyh2u6Ux+48Hl0uZvv8HmsbfZ2z2N7iB28",
	"4CqAlS5w+bl8QSHP09vCvF26fweuj7exR9QWGUwR+RrOGu3c8MGsf22ZHEIxb4At8ypNH50EVr9SmIAL",
	"t2ToilDVGAHjfa/sW2Fy12M3IvNQmWH919ZbdEguFaNX9kb37uRySy7CdV3M2v6cFXLpJk/7G1i8W1P/",
	"wo00NOswy9lPQfBtbKaRmaAc9fstQcdJL33QaUaBAajmEWRtnn9jw1FqxPXVYJaUnROTzH9jmVWiD7hT",
	"W8HLjQPA2831FWZV3KVMW8oVGJq2ZZ02r3l2zhbBmP176aka9oJrVcCs3xSpiy1sKA8bLepZ+dk1y1y5",
	"EnnDUrss1xrJpMLkRIQDnuYuQ1EbDCsli/ybbbdyEI1vV2wLzLuL6SLQDarSecekav5LWG5NWxboix//",
	"dLj3X3Tvl6d7//n+p73y3/+9v3j/pyd/Dz6O0PSCYvqdoNeUOy+QaGkIrNEQUB1/RqTsWV5qXzgNwQe6",
	"754SD/D1cGD6RmWKJSlEe97yHHeaP8rDFWGCPkfYZk8tBeleXJl916+jzE6AEc5GksRVqsJicmWHivH1",
	"WU3B+ZESSMjFr13wEbO3x419uSUU1YyF4GZBqrw/5Y+QgfKA/KwxhY7G/MFz8vMGf8CsOPaHNf4A+X8A",
	"vQNU+/vBT8/2/vP9xUX6pyd/v7hIf9KbdRyvXopEWqZ+TIgtc22RzkGENBAGamjDdz7k6vKMcivWYpbe",
	"0QnacKoT19n//Y0b5GOYp62qL9OsEuNb7Dnd7RBnXI155jq0a760xoy9SK0kcm3Ytpr01MFwuVwtNuIC",
	"ek0fU0TElPDnD5jwp3Whdsv90+5+tyUvOnJOxgSGzqZVnt+4xqAkFIH1jlQkqzvPA/XJK3sySt+smVkz",
	"FSZQJmuqySVjgvgBYmWznEPVp1SBPfTpwnEkUKfmebat6u51ZFNrHZ7b504nFMhao8SJ7qNu8/EDkw6d",
	"eGA7/9SzP+zwHQfehBqXJCo8/Ruqawc/Lgzd9/imK0NVPdGVbTtCfApGnYdbikgh8x2P4BYODBHAlwe0",
	"iOJaPB4y2qweGtlqMrEEnz1IMnomo1wo2ozjFDn5pRa2iTMswzQAPE45upqWDZH6tNo+0j4OCtx6ImEZ",
	"uiMQJVZGJawIoTErdfiuRB7xupfY+NyL8xlo00+Hcqedw3PUmz8NUNalh1r8U0tBHktn1O1x/75TbsXX",
	"AfAuRDfcFdt1DAzXpdPRmgli71DwgHAdY686OBx7nuOQrcPK1dFwt1dw1KNUsb+3YqYCJ7ih6iMhLrdL",
	"kCx2LizSLqPBPoHm31mpkLb6oud0XZM+BnMtb5wCzJJguPXgcUvJtxlfrQ05siRZZiGyBqlc2kWSLVlO",
	"SiXdTpqYw8JAzdNAAVPwPf8KxY/93ekrfzrvjqtbCEZ0Umh0Zc6Vf8X+9ymxKALcR8bFFSaxhvn829nj",
	"cHBbFVOXpqkBr2qCThiMQgmA4zBa+HrXVVEg98bXl1VDGizZegvUwKH3giu5F0/seAQNg9IIL6ih1TLD",
	"aw5aSSD91C/djk+WPINoG3L+6ix+8XExV2zbu4gf2Hanya/Ydmju5mXvgEp7iaMOfjxJGEEZfIZOey3k",
	"LQ892JdFKqm46QR51fbQN+2GfsillCOTWk2/rgsci8pFTti+wkA80lQxXXp/DG6cPPZM7VpqY2Xbg1wq",
	"MyLOugdA5WKjJ2+538gxX6MwGuiYnR8Bu0bHcGqITMALvKzAhk5vEWIej4xriu9QWg3MGAgLJMGKr1bA",
	"r4EcYSdH0wrKK8AbQRQjW/IPaDVhHDRPdrgD8hjMHuBAY3/QT4IZ3FdaGLmBum0+aCXO6U2C8V0LxmkV",
	"3t/7CtoRfSoAcPC/hpwVqPUdpxs+ZUumoMr6JBLftUjcUWHtEO9dlem1IYA2E81aOOauGtodWgO6a6Hp",
	"tVRmTjY0WXPBqnW64wf6U0810qiahuQoMF9615AjrA0ZVEk6ctUfy9yN/sO70pe//kuroU+80vglHLMd",
	"cNjxc6PH0cm7Vvj80cm7ZsD90cm7N/Zprxq9hnwErb74c7M7/toY4QXXV63+9sdmb/tbc/ZXr2XKsvb0",
	"+Htrfvy5MUgQMFV3VA8+tPzbg2/NnAUvuHb8TpiiM+Lp3nA8b/5cZhwKPjRGPYKwe9NyU3S/tx0Uyw5R",
	"18QSKXYqeOYF7AZKdeTH6s8s1VMJzP5yLK7db8fupTun+qqcOPzxhKkNFRCmGVykjupn/udjQesf3JOR",
	"Vk2q29qudFYtLyx8VpGC8NczQ1X713KptQGcR0nz92+oSdYvuM4xbVTjq4MayzzcW13DccNabkeWSpjg",
	"xEaVh2vBrvoUrRhnf+Ri1aJytWpyzR/L1ujifsq0kaojQw/2HMVanGHToDplt7dewIW+xSKQSE/mxJGb",
	"8DkoSY0nRe+HDVP96uE65xOpczkv62PipuaO++7k/YMUSxERYM+5KyW+Gurcvo4FMAtplYjECQXbHES3",
	"WqYljPPOcxcv30sdepW9/bn/BgjLDiM309x15aYaiI3syGTVexE7Ruzu0TNqQBnGDlt1iY+700IH1tig",
	"TyMGrPeIj+oIxIjRsGV8FE+cRwzjmlbjRF6mzgqQzZbxUdpP2YgBW52qsfuetU6P584u4bi1N6QfU6KN",
	"22MNrqvWLBARfag1VtIPU5p9nI8sCto5+KjQ6I7rP653P6m7zRhNojZcnrQLOXfp2YmFY2t/RtFjuPMg",
	"tg4N0XPFd+m626Z7qecunTuI+c5DfNIi4uT64/udcg0CD9Lh7OI/NRxcrkH9Mnm1fHavlvIgxrmygB56",
	"cl/5Yt1XAkErKmCVq0C9G1wzSBlnJcq2xq1hHvKdh60MO84zYHUp543t+VueeZVL157hI3pBLHmsKkbS",
	"1x+iJYhhHwx5/O78272/gXUDYycqA1c1CQTiuWliPgy2nQ+eGDZNB7Eg0RAbu/3usnv2a1loryPiqiOH",
	"OM/YI43BVfMgnsbZfSCsxqdvFsWGKZ6Q4xcL8gLDfIDwXsyUlOZiFr8lMmW9U+dMOUUqsW0X5P/IAogH",
	"Lgbj+Tf2qi/phmecKiITQzPvEJExCqExvzAlfZ7Gp3/985/h+Cj6aiV84zpgMb5Ynz8/f/rEUi9T8HRf",
	"M7Oy/zE8udqSSxcdRMpqPwtyvIS0QyXE5hjOX98MXAG7T03SAGB2efHCq4XuTPaO0ILcxPdwUF0499Yb",
	"EcKyPUmphnM5mIM0OuOijGpDB1q98OfTcuzaz16Mee9WuFu8aUhGBjmw8M4NNT68hKTs7ISCt8yv7ajM",
	"kip0xGcCwxe52y4iPbQeszDV6cSfTYFIUyBSJTPtFnyEXe424AjGjEta5ae6pIVVLqab/NklreogRkla",
	"SLMnSetLlbSG1Tit2OdLKPAS5eHgE7Ch9WwzVeT9wxTl6bGaxKx/S6cpj0qDZYoBbNVMVQJbHplexeUS",
	"P2EqsVSqq7qMa2Z5bdfOi2O3mGxZZEMbq1p+yuYM2+SWZvbGU4Sy9Xm9g3ei5tqhkaXozj8a4gBkFH8M",
	"37D0bWGGNgntYKBP2eOts/CMn6WvMFITxnN3GWOoNS8T4QSYUOJ6ALhRZKGtIP4i6EJg94wRhs+C07dB",
	"gKEzHKbq9w7vfhJ8h5Cu4ZaFuM+yAjlFPhHgQ4COGzIeHtoNi3n01bPN0eQ5BGwEaRnl4gLKLFYzyObL",
	"fI7QKHzv7nR7poZyKCJlux5wBYXdD7tusXv4Q3YW/ge9T44Luv+b1LCkPjx0vWNHDLzKN1HUsFUk24Ab",
	"w4pB0KJ0d6q8vSA/8jf3/vrUn5xPfm+aOx9xjNFY0Hab3cJAWxxEwxKCcZTfDPEkjmGrynQgWcEC1Q2A",
	"9aYIqzQz8a32RFbDVgajqd1Wx9XbOK01hgikquRUr4RZq08VIGHHJXNfG8U028knG+kO701BFhRVauWc",
	"jWuzmtkj/X47EbsXo2+NyqPrkkDrOWFgIaFZtiW8kjaCq7Gm1wwsOBDIhm8kZKcTdMVqYWRcEEpu1l0W",
	"xd1ilcsT//SyHmkr1e0utaRLUjVKxVWnVjsGR3/HBFM8OWW5LI01fcXO8kjE/5CXEg7tndIK1SGGPs4l",
	"uFVvoXqoYU8gczi6NY0rT2uHdm2ie+UmUoWr9TqvuDm124knVXAuVxjg+R039fpTBCMQd8kv6rOK+orF",
	"fOUpUOXVFeVMK+gMP6/VUKXqMs7tAh0/Zde8L7EEfrWLLnyhu8H1torMlYtvzTrvypQ6n4lRPH+jSNvw",
	"agQy0e7kYxN/L+XVYeKNrZU9s5HWfNlbbwiLnbt6lBtmImk1LxlhH1hSGMxqMYoS2bX1UiPDN0x26Zl+",
	"0zk/ySP9qJ7y89HmUT3lJxUpebR+9OlpPz/G0guPc6GtsOO0ELOP78FmXP8xkofz+keqPiWhysuqVCm5",
	"popDTN8V2+6h5SKnXEGFgn+imOlzyRbCwjiaqlsVotNpaWMBXcfQsPwBFVtC1arYAOdQaJBwDRUpVSkW",
	"nSN6Kwz9YJGHl5VK8dw12TgvXj+TJjnPQTZeQX69ucUoDtd7i9Ut/SJIYUVnQskl1Wuyl6Af0Ie4au5G",
	"qqsXvMONw37EPNE+4zNuF3K6YhrlQghvB3ILHUHqCtFJUqpre7ALrpXdTqhZv80HHSBqfV5+sAweVmkc",
	"XFfQuG3kFISVnwPixiz+QV0GSYwqmD26kg2J0zyXSJql0VOLbbl1n2SHF1UZavtYPyF2fnD5oQY8yFgm",
	"b9A5CF5huwVNDdfOtQl+LZc+3vJYc86JEORuboA6V5WSLUB/OQIqgBItS1ADp5yg6/0ngjmWrHxuoRrF",
	"EWPyKsHwDuVxj2rckl3k9+fnJ1jBw1KCCBtPF4mKvF2Y9Jh47z8lpSFHh1H8yanWN1KlXQwYfiUuRwJq",
	"+yPrKu0f5XixcLwrnqPx90emylT0kfwZVzx3jK5jGsl10CGeMdRkehQwzl+dYV4X73M4aul29Cu2HT/6",
	"FduOH1xeddUZhE93A/1CM9XNI/qvg3ONcMCrbkC/NLE2Jh8pTghcyTiBwlKFkygZsb96EQLl0EcaiYgr",
	"1mVkkLXUe802azTCUjSzeFnxdzeKG8PEJ4sjqi2OeGmCuvLfW5GQHkEFa9rGNq9KD+B3p6+QVCZyY0n+",
	"0rg8vZdUw9cFOTYkocKxMYz8q2BQ50HRDTPgclMka0L1AbmY7VuKuG/kvnfd+Du0/hpad/ltdoo85fE9",
	"vJTjMbKLrt9SF7CuPQm93EjVMghFvhMdAmAtnLskCc0y+24mmRQopUYxCWLZsdRKB07Z8RDfkBWUIsOq",
	"YL6rZX/R78HJ8dVRQ0V7pckGEiJZBPeYiQwwyEnwdrlVe37zcusP2HlMEXsWlqmGlTDt+GhIDLRmWY60",
	"zGDGILejsr6lMXnpcrSTHmUenmsMY443dMW6CqyPdv0NBvhRZsWGNQqltwTtTdQF5TSkp566US6YItCj",
	"4orCevI0uRpVvwUnjaZOjoPlpMiySuldVd84Xr6R5gS1rK06HL60Yt09/FHY59GC/MOKI5oZ+HaY3dCt",
	"foRu7rhRrklegCHAkvAtiNWNXm/sl1onYClpphhNt4R9ALc70VHBE+eczZubgVFHeppb+JTj2D8aY9mf",
	"3HgepBHsOOhEjt7wzWo0nxZh5HHXVtIV6fOilk7HPXHo1vn26HgPNCmcCuMgb/kRZfiSJhEOOK+h0eCm",
	"AqyDHfl8UP23ZXhhqGxXbMW1sYQNyM+Gbi3Joq2bZjsKianxnTnz7dFxORjI85m0lFMTp0WValNSUNsW",
	"B9JhSacxr6zfb/TkoLjrw5MrrCnbU/g/JEiOJRstbgarqcIn+lOmugWNpGXQeAyzO7xPlL7t6wyBJW36",
	"MlrA9q7kTdn6fpmnTsDFMiI8rANAJCNDzDTPlJLqdVcuMzs7tCAu0YpPDObVXkvKs0LFmXKp+IoLmpW5",
	"FkcFwipm1PZIFrHgvzc1J0gkpobqq6rEhu3NawqNUe6INSg0Vz50up3h/g9/0O2kGfdw5rmf5Ldy+jdU",
	"+4Mnl2wpFXPODxuqrlATlleAcY4/n4giwULH4MsPxSVTghmmz1iimOknnHdFtOYzDbONNWBWqyTYMeLw",
	"YLd8S01DrT4KThBoE2DkDpXvOIBUa44OoHOa9IwCnweHir8D1fDzAEKDLhqud3VIMdQBR5Z4iFL1kKZc",
	"Gy4S47Lpz8nNGqwiNFkTDqXQNUGVmcELcTG7YtuvwTR0McOa6uwD3eQZwwpupS3p61zJtEhcfm3L70nx",
	"daH3GNVm7xm4XzP19SVNrpgAclM+2YP1GesuOrHdQXlJ7/Hj4rDgN1TNyGsw9bggyyqaiCBu6yKDDxtq",
	"kvUrLDOAUU8mWVemDDQtHr55wdIFebnJzXZfFFnWmF1jN2K5WJfvrHEzGqMO0bzXzfZQsbJc6SeVVtjQ",
	"3G781yu2ncMZf0T7X7w0QhvlfHRONPjKfgkShHoXKGcv2QqzZoYn1XFUtonQQmgxF4/jmiouC116EsEy",
	"9IIcVtpAK1eAcQOULRIz0P1aOVXNiV/Yx3guAS6KyNV/jeKKxR8eJGO2f1OS8Q0vJd4qHALQu9SPosGZ",
	"l/W/alUsmALGBCLiAUJlZc8wlzPkf6X/KlgZkeeVPkYSrjV8QNHJV0lyUlEQNUbRCQpco7hGsgCOxPZV",
	"vEY1k2AfjL8rVY3REtxHCCasnp1IobkGVTCMZZflAs+cXw7zIHM7reup7b69IQrK7ipIbG1FxiW78eZ6",
	"PNOcam2vnru0cOLe8RPVYvUi32hNhn36o22kxeYpZt/PPKQcpJ0rH1dQSBLSX7A5KUTGtCZbWeB6FEsY",
	"L0HpzBGQp17UGaMOxfeGcsHF6tiwTQcn04xautT2YK2UDcjl1gmAxwfTEigLfqeZdqnH/UH7rUCqg7Kn",
	"RxYviqeOoEGeA7C2e8oGSp8mnpf78IvSpMDq7YCnCEg7jAd6xpaGFAIuj0iJ3HAT+BlopjjN+C8ot9cW",
	"GgQ2kMcuScIlS2ihGeHwGZz/1oUAe7ysvgIIXM75jGrX6Em1H8Uc6BADm3vCjZTuB7faiQ/tlFkK9gQq",
	"yPWzxbO/kFRi2glmgjkQyy3DKewx2k2URpAm3tid/YlpwzegVP4T3jb+i3OfTGRmzw8WgeUWyphgO69i",
	"QCm7xkbdMlADVfpxOH3TmMiu1pvh0gxPJcaDEuOvX0FukYykii8RmZzNnYpYuQdoHA9keRPwueWwTsrB",
	"CTtYZ81TllD1slYExque18bkB/v7mUxotpbaHPzl6dNn+xv7aiTtmtBgTikfnXAx5Y7dbD5Ty8trIMXZ",
	"lhwePxllSn1vUanOGbXlo6hZ+hyIgKtHHj7EjnsEnRpom+LyKnhodBVsKN1Gqqqa8BYBw9ZIf3tsGeU3",
	"0sB/X36wfM5sPnshmX4jDfwdlcox5r5jX47NxzaAzz4Mcyy73UBzC8Jg0xGw6z55A3nhyt9nfBx+83Cx",
	"TPoxdn3WFhIwffogWflNkYidaZwFfxAi0Fpy9c0+CnWOm2aZpSrArqVxrhuZCMc8QDl5z/ZhdRBsizrY",
	"SGYLISRmovgUoaRqDK+O8ysIKt+0XpTE1Q445xumDd3kPaVX7Vgu78KNZT0xT9H4equpqymw61yOY0ix",
	"SMH4+VZMMNXhC3RIkB1MSnaslnWCljYQUo1SlfODEn4u9IacyLzIoMaLhzfWqiGnjKZ7VpgaGS/+yeX+",
	"XqNE6pJpXLGtl/2QoIFfBhWh6CPVigrL7dh2VrpaSWX/fKwTmeOvSNuflDLM7NbeEy65SvRhuBEsqp0I",
	"sn5QQ+QNuHRjYj343Uq75AKSWOzbuS5mTgXTITfUJJ+of6WTE8NCHSjqLLk3LQI3+kgH2V6qeo9VEplx",
	"Tk3NEjJRGNQUiGE0QePJnrKs3F2WlXE4XZ5N2nvsNa4AE67A+DFd5Fu8kyXhmlIgTcnMpmRm++G1iEZs",
	"9mY1Grpocd1/s0U9S1n4dUpW9vmTlbXOY5SsVCO3U+qyLzV1WYt89F52iL+vzC/2sgVf23c95TrP6Dau",
	"VvoeSkSWJeCAfdBreePDOVUcVuwDXs/jCPq9dN/I8YuSu24scATveUJNsvbl/Q9+re7LDj7IgzFAUNoY",
	"FXKhAoemmDA3z9Cii6lzIYlEh+4mHsFzSP7X2ds35EQCNYMYni6f46KDn8Ora3nrFAwpblGLFvLJvC9Q",
	"tkk4+hK3Vd+8at2RERRe6nQkyOyGraIbHFGa4mF8ZfqKwLy/uygGkMxuqC4p3W65SoJZY4d5yjJq+HVH",
	"vMdpmH5YuabohuERcEws+mGkrzcneCXCG2mc8EuF8xAGPLHtvWZEXjMVxImUPgYzrZJ9LlL2YfFPPY4k",
	"1Nz+Y/suv3rEDauXqVo4ukeIFTfOqT16/qc9518Log9g/h03IS6A5yupqc4nfmySnCbJqQzlwYuyWy7o",
	"oN/dJoSuBo6LXfXvdaGr/ManVO+/AZlLNY5jlMgVUPxJ4PpSBa4G1em55E1hq+HmVGcqxmVsaOZYGszW",
	"EAZhDjU+0+uq7cDWO7J/NVvslgKsDpFPTMFVH+xT83DtlgrL22kPM6bMaZGxmIgS7OA2ZeCpHTueNLjo",
	"sg6+8LjneVy+QS478K2m10xZkazQToqTl8470LnHw8RWWiPfwnke9CfnGU6705dy5+Ii/Y+uLDvzWT6Q",
	"Q7yeOxx3hM4diq9WllDGIImGU/SAv2aKm+FEg+F5n7lOZZWnWvo9P2JwTLV91G2fg8hVm6ydGcJ9beGM",
	"F2Gqeu9BRfhjsZQjwy4711IN3NkkmLGzDS4l2PQP0Uf0tHwX7bNB2AcrvKfkmlPY9uHJcbjpI4u/4HbF",
	"zvjKLtPriiK12staxr7gba38eaOG62w+O+9M8BpKhjU3Dqdo66z/fHTyrpNi5UXMJ2Q+e8H1VWeOQK6v",
	"4r2cH16n+023m573tens2umJ0648G7rIjC492wGJoTevb10DmRY7oDg4YzcQm5U+a75CbbyJ8x+9ToV9",
	"VnbqH6uY85Z9BeGRzkAcsK0W5K13qMdfc3B/dxSHa5/9bQf2uflqRrhoTTd5xsUKIteuY3UIykfukpkb",
	"xoTfP4Gudt0P8G6VeeJ6UsR1HfU8PIrIjvseBaBCnfTRfq0rnGo+GBAb4RzuMbrWxWlXykmJ6VQgPMDR",
	"XBA6+WQsnJRTk3IqXo57V/VU0POuFVQ9NcJbIgrG4AwG1GIz8BqDaD/vMMg1qdEdxIB4QUx70Nx8T3XE",
	"mmB/9QwsBmpA44erlxKv0t8ZHD0IMGilIQdaYanP7gDrMwAFoJzXjrC2vCHs8ArMiZp/ZjWk67wVyc58",
	"FPACkyLyy1VENl6YXravoYz0Za0f6yclU4dxir1auIHc42VR7nqSUS5aqcyObcuyBWaOqjpU195QLjBw",
	"N8ZvYqIyIS3q+N7c3umXNFm79AH1odDP3Q9gFxwyvf139WHTEo7Jn+499ss86m1I31f69AiX0o9/t9AH",
	"h/0/USNMb0dKe3Ohe8XoEby4XUFlJcNC1paRKd077Do6wu78wN/1BHqUgwdxHJGxdy20N1Kx/ZkccGqT",
	"RzkwwW7exmMu4IayGyytTh7zMlHWZcYgvFAUGUS1zw6MKlhM22yvmSx0zwS+ySfM4p65bznL0h7OACKC",
	"XfALJDF3/SoSUNGWEtU9JDEspYzMcRID/mdRFslxf0dqwYyME6zxpfV9RZGrXbQtbsUoX7G1vIHXC9qW",
	"5V8sNgUlkfpUq1AZ6cxFTHURgXqjtr7SV7car6xsjNgDjDDnY6SyFn725hxfnSzHX5u1aJpXFAJ58TKd",
	"V2UdenWeRZWIPG0f04haTM3D/QjnowrY1zdFumLDi2i2r8q8nq8V02uZpUNjBD6McXexocpm5+jaiFXN",
	"QAiWPMGkoK44n/Z7tDeyfjIhUaujQuyKnen1HeVHPzv7vi89eq74NTXsB7Y9oVrna0U1685zjt9RRarX",
	"J2Xf30Z689qSBtOQu50DgMZnIo8hTmhD383hWIfHPGCmv6eUx3b7DQ9EnwC5L/FxX8rfalcxItfFODpm",
	"kaOG2hRKOGnUYltCs8w9fKkUj3y+cYJpboJwzkl3cb+6C3t3ImdXrFYMwsnBb9Udjm3rUiZzn61pTp4S",
	"vvSJTprc6lfPo5rCSXlxp8qLjjyOYxxQKkkN4egDIzpkZ6rjni4bmqy5YJ1T3ay3jQnsQTsu92L2LaaR",
	"vJi59bj0QFxXGbLYJjdbl9EHEgLVRc8qr9YhOYVlkiSjCuOivfu12yyg8WVhKQ/D1ELyminFU0Y6NNK6",
	"n8T5IJcSeOQtJCg7IBezM2RqLmZEqnCn9442lu3foyLdcyAdJPkxHZbbuCMTJQZUSBd7EM4Hi702irvW",
	"jJlhuHpZlHN6CSab5GSThB6Ny7ObWbLZ+W4tk43R4/7zkUZ1J/pGg4kL/PwWrNiRjFK9Np+CyZD1pRqy",
	"YmRp6O63fOtrb79TwXSzAKATiwvBWDf6Zi11UNjb3fcluAzLYYYIxx+z2ZL2jstyGFb2biU33NlHfsda",
	"Cb3WEIfVh6Yn+1UtiXcJ3Buq0ZQRRLyOyYS1i+ni/XwAn25hnio34HBvAefLN+y/pK9c4XMlvpLo6NxY",
	"g4XJL1KwKhOT0s4JEWY7Pnxz6EOnD09fHu6/ent0eH789o3P0W1/rPPAmNXWnrRURCaMCnxDfM+ysC5U",
	"1aXK8KTIqCKa25PgZs2dHYkqRucgsru4W3K4YYondP8Nu/nv/yPV1Zy8LCz+7Z9Qxb07aCHo5pKvCllo",
	"8tVesqaKJlAsze8VM2brskrv44vZd6/PL2ZzcjF7d350MXsSJU+opz5L1ix18RRNo0D1YmvXyhfnk/YY",
	"E5LKG5FJ6mrMpg7ddJhY2vCN/ypd8STiSh5HeIlBVfWRqtdIBV5Lme8UTdiLIEpjrM7dBMjV+3b6di0a",
	"HSdKAUtU3+J1F6/0HTchyY2n4+u4qH7Q9x+xyEChuNnak93gpJeMKqYOC3Q1wL++9fTgf/3j3PKR0Hp2",
	"4L5WU0I0NlSQWB13FOl89y6eXKKWii0woBHymubaFTYKO1TJFBeCYhlkbieB/PI+E9aBXcp/80B9THP+",
	"A9vOPtrdWyLj04zTBPCJbSjPZgczw+jmfy4zvlqbxGQLLqsR7S6+hS+QeFvJjJwzupk51e7Msw+13q2s",
	"ej/Vh3j/ONbtieOk8GydfSPJqMLw/g0VdMWgbLRc4tMJxJGlK1ba41zKZ66gLLK9gRqLBmQ8YQJtDG5n",
	"hzlN1ow8Xzxtbebm5mZB4fNCqtW+66v3Xx0fvXxz9nLv+eLpYm02Gd4TA3kCGkA6PDmezSucnl0/o1m+",
	"ps9cCldBcz47mH21eLp45lwfAB8tN7V//WyfFma9n5Q6+lWMg/iOGSgHijnEfQ2myg6zKBOncikshs4s",
	"njsVOSTyg2zcMO/zp089brgyKEFpp/1/On0a3vnBwk7VLIB4jRQxP1gQ/PnZ3+5svlI8bBcYKMBlx5Rw",
	"YSlM/vw/H2DycynJayq2xEX3oABr6AqimeoHh/SpdviuHCLrPP4fXQNLKhpoALng48fvewHS+YKhwApG",
	"qjpHRrW0yS+tpEJrRlOgjP5qFWYtlU8INQ9A2aTW7+8RD/uOxu4EtgH48CCTfkNTjwo46bMH2ykX1V7/",
	"kBdvPvvLg5yxr3HlRHnyUimpRt/7pAoW1Bgs6KX6TiIAqo/OIMO6k2GdGNienR31EHmAJK+OaS0bWtqA",
	"BW+8hyPUAS31F64odFBTxLFGMIIdAPI7Y85u02z0yBfReOTKIDi7TOkHVa8x0cEhlUVW+qjSPJbq2KVn",
	"x3Ako3hiqtIQ4D7tan/4jNWYyZgrV+qoXhgVypuWBXpiC81qRYcebrXo7DX3UhNUsnDZ1y2Irxh59PWj",
	"OXn0tf1fy249+revH/k8+lCt6RmWa3o2v2Lb5/+Gfzx3slZspzDj7XZqMWlDP/BNsamVBEHEKzcZFiqp",
	"ipCcV0VhIAsUVsDoRrRad8KXdSyHtFI4aKPay4ZusdDHZVkW1BV7Ky8OxL4F9VUAQp2YwTeQDaqC06At",
	"+17f2U4qApr1bhbwy3113wnqOCD37j396gFm/VaqS56mTHz2p/YhdnvmxMR3orSq1x7azscUwptzGTP6",
	"HGF1VzriRW0/qNi5L+DfLeAbmW7v//IhzCpdiFEF+9iiAs8eaiExQKcTGbh3MvD0IciAlfYzjvq9ifD0",
	"EJ5RzP7+r/ah/4jkKWMmooHG3+uEirhrRyqCUydQL6BTH4Ea1AiEYUfDNNJyn7jSkpWBGJ+Sk3F1RetE",
	"6renLvD8yh+GZvz5AaZ8Iw35VhYinYjGILcSFf0Vo1jesJIpkp67XacF3zHzwIRghW63n04F5rNC8H8V",
	"zJXiAr7m88g3E62YaMVvT7KhJokXPU/Wt5RsoO8Dk4u8rBt4V2zDWNlrD6b+j91Os1YGYJTk9Znp0yR0",
	"fVlEcZLzfmNkuIiybFAVo8G1HY3m2k6x/wOT4io30IPT4gfTg31Wajyp4aYXYXoRJs2f1/zt0zxX0iUc",
	"jT4kh9AAUx8xse3j69vsPLq3dnY49JPf2WOCpcjDBU+PycTaT4R8IuS/b0KOTscUMq/ofcV0gaUL48bl",
	"U/heeipfUs1SIgW6B1UeO1Sk+9K54ZS/LiKigB0NQ3T0PdmWcXSc6TMRwPoScJKJ9k0uJZ+FLNTu++z9",
	"fPZhT11STL7jElO50LRZVScfrLVwSz2F+NimIQMOnngLhrw5K2IwuW5OrpuT6+YX4roZwRGXfIwsM7qy",
	"eIJBhQyT19rVbDZUbeuRt3pB/mF3AqCSBCQrH3yGYAFI1vLgws13gwUxqi78EgAO6R0fITbV8P5RBaNm",
	"GOaNXccjN7Ad6hFkFVRF59UP2sawrEzGdq92YKSvk1PrxIF8Zg5kjAdrg2Xoclct603dn/zw0I6o4ayT",
	"unvyOv2DUYa2bDHCn/SF9ycdJBvYsiQbO2mIG4NP7qGTCnRy+dr13e9OBTB8eb9j5s5u7p35cz4E0z5d",
	"2+nafmZ2vd8tc/DqQsM7u7yTd+UdEpBJkpjsrZPwcld0Mubugh4rY8ik85C8M0L5u/B93EXP8nCEcdLp",
	"TJR4osRfnBppP2VQY06XWRxjFLtMi1kZoFDdE/Rtq5aqj3eoYKoG/V2Q8RAKE687UdhJQv/M9C6j2mjG",
	"RG8ezrJguG0JaXy1oZu8gzD1aOZeUW3O7Gx3oqHrXNcSfQp/H9q7EiY9vOafI1XQJWRjtYuYyMhERj4z",
	"GVFMpAwu1AAZ8Q2DjPktWnHq2tylNj82uXd6SsrCjndFNeadRYavhLwR5UJ+9Pnu445B0Pi03nb2W7U1",
	"TFRqEicnutigi1VFqF6qGBbDGM9NnfnCcJO1c7J2TkzQb8PaufN1Dmyfd3ahJwvopBWaKNlEyT7FHrkz",
	"IatZJ++MlE02yol0TaRrkvF+QzIeE0pm2YYJM6KGVdW4FmQWk+pelk3LMlajqScdme4Kw2ChnJ8gXOui",
	"nlgVir7nSl7zlKXzsBqdC6Bbs+SK8KGcKC7OTscngXg6iF3kmiRUszLEj3s9nYuPbEIEKr3SLCPSrJmC",
	"vnNXPLaEcjgRhknCyi8Zlq/vjL/V6rOp1loHP5H0iRv9gxDY6uZGs5C0Pg8kE6iu0sgqUa0OU4qBKcXA",
	"lGJgqg6148s9VYWaAuh/i2/pUCy96Hkyu+LqWz3uKcS+Pc8DR9t3LGBy0p4C7yfuPMqd7xCOvxvlwV4x",
	"yrOThrl7yilgf5LZJzXs74qz6c4WsBttqele74Ww/E48bEbxOxOBmZSCn0eQ6c0ysNuVh073fOknL5z7",
	"ITyTjDWxUxM7dQ/0tS87wW7k1fkC3TOB/V34Bt1SifVZaOukO5vo+kTX/3jqulvUZIq8B+1nwPW6h2fg",
	"d1d1qbWFshLV534O/EKGVYoTgZ7UDBO5vFVY36crJG/nUT+pJSd6MdGLz6eW/CQyEFdS3gchmFSVk6py",
	"ooCTSPslqCo/ieR2KS7vg+hO6suJ+ZuYvy9FWLy283SKhKfMKM6umSa0DETALosLEQ9MwQGHglH+MPEO",
	"Z1IZIlXKFIQvuuJ+EH9gN+ST/9VjTR7ZMR6Rx4LdWOq75EqbzsXB4LVFpTgUVDnVyWw+Y6LYWGSg8Bf8",
	"+H5+21gNPH88N3tEPthiKI7nbuosftFRTPeqjbDHNsV5THEen+8pshhYf36WGWNDsZHf2jZD8ZDf4kBT",
	"DOQUAznFQH65ZZaPXcaFrnrKftNAV7pWQlOXo1Wf4SCfr3wxkK3pUZ4e5c/2KMNNGVO8uP4Md8VYQqt7",
	"iqvEsR84ljKYdPIBm+In/1hEocWp7/8K//24b9gmz6ixDKHmUnSz8MB++NakbB7j4c9dqx+rRoNqa3kj",
	"kHuyr35rmg4l9TIgUrfMjD5JEpMkMUkSUzYVS2cbdGti5yd2/nf0co9IfZC61AetB7Yj3UHjQnzyO35/",
	"z3jT8j1y5imnwmRenszLdfVBlPtXjKbI+pbv/iAN+Y6ZiYA8JAFpQnuiJBMl+U1xLqNzMw0qKbGhV1Lu",
	"5BRXH3pKuzRd7Oli3wWLAImPBi/ud8zc0a29w+ChP4Z5ciIbE9n4vIbJ3gRKg6QD2t0R8ZgCju6Odkx6",
	"0CnIaDLT3hGJ7MuBNEghXfTQHdHI30V80A6+JA9GEie3lYkETyT4y9JaDeXcAAV5FfZZV5V7ghwXhW8X",
	"23mvAvEki06y6B9YFm3Wnh0vmd7VXZ7k00k+nYjYRMRuIS0qFAJ3ZEZC0fGuiNgkQE480EQ+fgeSDjp2",
	"j0oekXJtuEhM6YCNfcucCBWdqSjBNmddWSZe4cwjSI0dxflElwRGuYWVi1By02WNu+Ii7aU3PreCK2s/",
	"Jq/CIVnyzMULNNciRbbFiIEy4pmYNQ2jAlb8mglsXzq634sX/R2sEh3Ih1Z55x7wFbrheh8kWcXtpF/2",
	"gW7yDHvgal/iL3CpnQX4YOZ+rPzv7c3J/DUAR3tM93LNlRQbJszXuZJpkRh0oFNsxaX4utB7jGqz98xu",
	"gDP19SVNrphI8WKPoyFw+SYv98nL/bO9RYD39bdIqhUV/BdYx275jGo9F4S8tbQNqYWuf0QSZ8lHoZki",
	"a6oJTRKmLX2Jp6V4W1vVPXKG4UTT1Zyu5oNfzeqlgqQtsoH4/uaGv9cvsGK51NxIxdlAQphT33I7lBXm",
	"NBxzyg0zRXROEZ1TROcI8ldRmOktnd7Sz8bmlk/idkyClsiz2JWlpWp6T6laggkeOF9Lc+bJ+2VK2vIH",
	"pBYdjPUusVSj6Am2rtGTnaw/kUmm0KrJJjPZZG7DIPTEV426zN8xc+c3+XfiXdbPNkxXebrKD8zr98c8",
	"jbrOzrvqji/05GJ2x0RlEkMmJ/xJ8rlL2tkbDDWKdDq3tjsnnr8L17ZdlTcPSzAnZdFEpScq/UXpp5wN",
	"dyuSQcsvNj3bimTY9lu1nYy/k/F3Mv5Oxt+RTEFFOCbz72T+/YwPZvUwjjMAR17HbhNw1fjejMDBFA9u",
	"Bm7OPfH2kyH4D0k3uljt3WzBo0iLtwbXSMuOepPIRJNFeBLrJzPS7XiGXpvwqEsNVuF7uNG/G8twPycx",
	"XerpUj+4IDBkHR51sZ1p9B6u9mQjvnPyMskok/1hEovulooO2IlHEdHSUnwPZPR3Yi3eVcvz0MRz0itN",
	"NHui2V+UKstVKuoyFlv5Vruhg0JMLbm2qi91byRqRFGlybLy0Gjl8ec99EWjKb7UhcpmB7P9mX0tXesm",
	"cr31WITZiywlZMK4LSyCOh61D7O2tTcYSApyxJThS9uanfGV4GLl4FZ3dPB2/6q1xtaqfAT658E8RdFB",
	"sUpJ/wh2y9iO0MT4Isu1Adzvgyt5KZTMsg0Tpm+nrGw1aod2fS5bERcrwq4tyoTD2R8Gl1ZPShf2xzRY",
	"uyzBpSCiiZJak5Qvl0wxER8dE5vsMnqY+CM6ZC3jwtC+u1IruLECF57hkbpcdcqxAtI+YscJ47DhCF13",
	"I/pb/fH9x/8bAAD//25LxN+WcwIA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
