// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PcNrbgX8FybpXtmX5IcpLKqOpWriLLjjaWpdUjqXvd2ms0ebobEQnQANhyJ6Wq",
	"/Q/7D/eXbOFFgiTYzW7LmqmJZz7EauJxcHBwXjjn4I8oZlnOKFAposM/IhEvIMP6n0dTwdJCwgWWC/V3",
	"AiLmJJeE0egwuoScg1DdEKYI27ZoRlJAOZaLUTSIcs5y4JKAHi8PjnO9gKq3aoIkQ9iMwyiSC0BiJSRk",
	"I/SOSUBygSXCdIXgExGS0Llpek/SFE0BsSXwe06kBKoggE84y1OIDqPxEvNxyuZjnOejlM2jQSRXufoi",
	"JCd0Hj08lL+w6W8Qy+hhEB3l+bX+LQS2ao3YTMOI8zwlMVZf9by0yKLD9wa5AqJB9LHASQoyum3OO4g+",
	"DVXz4RJzijOFq/du3uOyu/3hf7lRDGxuymNGJVCpwMRpej6LDt//Ef0bh1l0GP1lXO3w2G7v+DVJwXV6",
	"GKxvewkplmRp6EA15vCxIBwSBaje1NsW5hrwndDlL5gbKqjRBFQfcJIQ1RanF7UmjV0aNDbihC4JZzQD",
	"KtESc4KnKaA7WA2XOC0URREuBohQBRckKCnUMIgXVJIMRkjt4x2sEKYJMj0AxwuUFUIqcpqCvAegaF83",
	"OPj2JYoXmONYAhejqLXsDhJyaLjgbEkS4Fc5xP33KoBHtQt1ROKKUDeMpZs9DCJFax3HsZoQqVYlNvb/",
	"3//5v3UcoJTR+QAJiblE90QuEEYpSAkcMY5okU2BDzTuYkYlJhRRhu4XRILIcQyjXqfwj4hR6IGo0wzP",
	"oQvdm6j8lKaEdve+fbhdv7dXEstChJmF+aZYBUaC0Hlax7FlcwksiUGJ4x4XHHJsmcSVQrH552VBqfnX",
	"CeeMR4Poht5Rdk+jQaQ4RgoSkv6Mpr4Cf87WRw+I1rcKqtYnB2brQwV365O3kDqif2FpYSi3Oj51dL+C",
	"GaEgENbUm6Cl7oEKAQmarrS4qnPr+lEKH4wbSj4WYM6D5fn+uIr2CQ2JgjZ9+/xTT3b7mTRvUNIi2BDe",
	"miyovnSzItFe/VsipKZfj2xtY7VGIiETPXhPYw+rs445x6uN/NN0M/Sx/pQ9ypa/a+11YD/Vds6AA40h",
	"pCTZT0qpMWc8T9kKEnR+fDpUOEoJphIRtYuKY6rjNcOxRFMc3ylBtXbuEC358GxgWeKqyDLMVz1ZV5r6",
	"SBTdbOsnwKlcrKJB9ArmHCeQBFjV1uypDm01R2cTb/LONgHOVG9QgvswiI4VwcxUM7gic8XsLuFjAUK2",
	"0dbZFHFPb0bc/jhTW48EmVNIUFz1RTPOMo3l46M21eKc/AJc6BmbABxdnNpvKLHsUJOS+Q0SZE6lIW8i",
	"KrCsSJqpM2OoZoSugKuOSCxYkWpRvgSulhKzOSW/l6MJR+YplmpZhErgFKdGszJ6QIZXiIMaFxXUG0E3",
	"ESN0xjggQmfsEC2kzMXheDwncnT3vRgRpthKVlAiV2OlT3AyLSTjYpzAEtKxIPMh5rHSLmJZcBjjnAw1",
	"sFRv7ChL/sJBsILHIIJH+Y7QpI3LnwlNEFH7ZVpaRbFEmTunlydX18hNYNBqMOhteoVMhQhCZ8BNy3Kn",
	"gSY5I1TqP+KUKMVWFNOMSOHoReF5hI4xpUzrZUWeYAnJCJ1SdIwzSI+xgC+OSoU9MVQoCyMzA4kTLPEm",
	"uXCucXQGEqtewgqmdT06T5fV9CJRiojdhjHdm/zVO2+WVLxFWshDLHc9uC1y+5XjPAclC1hBE4SVFOPD",
	"mIPaY3R8dTlAGUsghUSx4LtiCpyCBIEI03uLczLyeIgYLfdHa0Focxb4lBNulDGIGU1ESLTp/sakKpnG",
	"EqckIXKlOZom4GpiNc2M8QzL6DAiVL48qKhGcYo5cIUt+CQ5XmcQlspGi+LqykTLUlQDIywNrYNwol2h",
	"17gVHI41w1V4zllepPqn6Ur/enRxioQ+wAr3ur1auWJsJMsKqazPgF1o6CgoKZTBNcUCvvtmCDRmCSTo",
	"4uSs+vfPx1d/2d9T4IzQGZbxwnJyRW2jUn4QSBNEKMI+PawTQoZJ1bZkupIQOsdaLPF3QRXplCaGyDRM",
	"vKQJ08dwfM05PxY4JTMCidagg/yiIAHee3P66gn2yQNC4HlIAb7Rv2usq2VoYQBaJb6DFTK9vPVbU4AI",
	"UdQlek1b3kjAasmbddMnQEyDEzpqrhHHdqyvQ4mvCArnOWdLnI4ToASn4xkmacEBiVIjLVfp+RdEB94R",
	"mVVeQ9HmeF7T8Bm1Q7Z1tEGFOMSUql/ivNfpUuxVs7kAMo7Lb0bzVjvL/JM2Qj8r7RTFXkMO6EijDpIB",
	"egWUqP8qDL3GJDVA9TLXysmDZppPDd4SgjRQDtS9wGr7EpCYpEILEEYBYXXkpNvuuOBcK0RS7alTXhVR",
	"X3osrb61KRbymmMq9EzXpMvtpdohSTIwM5WgybIvJEZNU3BZMpQMYcrkAnhtt5U+NlRjhRUjofhFG4qf",
	"igxTxAEnmppsO0TMmVBqpsMOnrJCWohL8IIMjU31cU/eAAUjp8OrHzlNZjQvWxqmUsfGPRaa8ymZlaAi",
	"N9P6cv27b4JynQMWQUsFPZ9yArMXyLSoVAc35zPRa6U9lT43qlPy3Eg9uxn3aeME6BFKCAYhkisRUO3/",
	"2sOy2ctRw9FAEyWboWuuLK3XOBUwQNZ69Y1z9T0aRLrB1uZ4Azo7VuNXN3Tj55olXcNmmx7txUpFdcQ3",
	"bLzVOE4XDaLri7NfgGsdwxj07oPhgXrNigG2m8YxCEGmKTT/cDzlAnOhm16taKz/8YvSc1ULlqaskKf0",
	"grM5B6E2/0ZZY9Zpm0Psmp4VqSR5Cuf3FLjQcC1JDK9AGWJEKLNCdeq3ESeUszTNgEorT731tr7Vl9sp",
	"kr0hOtuUuOxsUSK5s0UdnEvImSCS8VUQ9QrjnR9a++N/LPfqdQog3S7oP0K7ZnbD2zvzg7+D5pe++2jI",
	"fEbmTZdrP8fuGyID3TfdYvxcav9XEHOQO1yB7DDrT1LmoW4aB3nhduWMUbXR7duvurzOTLPN966Vq4Uh",
	"22mz6uqPHvS7r78Kba/ErJIzevIpV7QUVnQ4owjKBsjISy3q1NhJkWonEslAjCZULdK2IAJ9+Cuy//9w",
	"iIbojFBlvR6iD3/9gDJrEe4Nv/37CA3RT6zgrU8HL9WnV3ilkHbGqFzUW+wPX+6rFsFP+wde518B7pqj",
	"fzea0KsizxlXZobaSCyZAmKoGh6WRqvSvo3j7DmM5qOBHoZQtFAgl+PBEvhK//ZCzfth+OEQXWI6r3rt",
	"Db//oBG3f4COztTef4+OzkzrwYdDpK8qXOP9wf6BbS2k1oL3D+QCZRqHps/4wyG6kpBXYI1dHwNMs8eV",
	"ucGrr+X7CiVKLn/vdZnQExOFoDCH9obfD/a/Gx68tFsaVGWOCyFZZhjLKZ2xde6QpjalvUXG55ugWA+E",
	"7AGzGxCcsmnueoMQaohRG4pa8az7/VtKjAG8DZz5ve4CzxcrQWKceuN99XJ/9XJ/9XKPKwWkv3Vj++zg",
	"v77tPMetq/n2vXHYR9UwZ/2r8/V35NpWSlZh6W+CSqx5IDFRWhi6X5B4oX0fuifqdRWvptGRKwE++q6c",
	"xbVBzpIuDdTw6J7J22/PwkEkD4Pu2/jKBrRNyotufcgacO12Od80jzt8P+Wds9ovD6Hl4nvRVf3ONSTV",
	"hGng6Gehr38bEQmBK+k6mRIrSteSqS/tjLvFcT7thPAjIB7FIbH+Qr6J741YNXp4FyKPPf9Z5UUw+FLn",
	"aUbmbbRxoAlwSDrF8KVt4ARv57ibvMr1edYuUrC0U8Own31FwzpL9M8xoxRi61coN7u9bmGU9dNXYUZk",
	"P6PTV77LqjFDmDBMzzNPdDTovdT1ylkco3asTcFtrx/+vRbqGGOqpaUw3mJCiSQ4Jb8bt2YZswo8IxSn",
	"gxJmyVy3AQIZd20XTs5puooOJS+gQZqNVQ08BHZvpW83txHhBrN6J3YkldSt7dIf3tpDifkcZD+x6YNy",
	"rfuFnX1myH5L8sZps/HyMskcFqFmaC0tA7lgSf1I+S6wGwra4aMdXLFkfHUJoneg8TqIvZHXNavPWmLh",
	"VMlBTuTqeAHxXRdD6m7bPL11lkVcDxSrLigHrk6EuRPfUQYMgzKgsniacxqIPoP1dy9+N97fOdIGL/IW",
	"yKyozkVu3lDhrH/fx1q6+Lahw9ACqpnWtfFh6G5XQtfdpIK7jdZOn7xVTrpItHV284YFr2dJlNUhV7sT",
	"jSKErVWciry1elMBvUG5Ua1LXLXlI8mUJpjlbu2NwZe6Z6Wj9rs42+lU2chls0VOtZZ59jl43vlgtoHp",
	"fTQ7BYDnTC/pO3w8dzqKjWPRsaSuk7XhDLePb3Xs3pIZxKs4hZ2U2dT1fgQzoOn0qgZ/LBnQWOtu7D80",
	"SBd5+blLIYy1+by5VrJ7XL/rqP+yJaE1oG6SSuNzDYrA9xBoG5rViO5chIPy/K/IfJpaxc3og+j8qjQD",
	"OnWPLHjtf10bxMSCG2cJRzeXbzcbTmbcbsI4FzsdofOr3kv4pW74uWUEz4X+8orMO8PhEv2tOZZxtSOx",
	"wAfffneI90aj0Yu+qKlP2o2o8v5wK3SV3tZNgj7Oi37soA6HE1oJEXef0z+DjPHVZ42Q6sjT3YdoRg7l",
	"RVTCZRfYd3fW3w+K2gWh2S/jDm9nKfyKueUVx5xIEuN053yFEKB+OkT7azV56KsHUOizAzL0zY+38FzJ",
	"HZytwdfwmuuYyl3VL08ot3fCO2UKNe6hWxGSxrfUDYj5vgMMwWvw0PSCpSEfrY4oc9iIJVlW3iHrFukP",
	"S93pFQx0rku9rd0dOlKsJxxWRBr3uWF8AQ+WAq12Bu3Fu90RGzPeHweNq/cQFkyeeNLhrTMfdfArUby6",
	"HjTQCEHAMl5cYCmB06A72u2sbohy27K2mJYH21wbOzgKSqSW8gOTN8u4/q9SNEUxm5FPA2SSghaQpkMh",
	"VymgecqmbjINv54dzzGhQrrYyHSFUoYTMFNomDL86S3QuVxEhwfffjeI7BDRYfS/3+8N/46Hvx8N/+tw",
	"Mhn+92ii//d+Mrn9H5PJcDL562Tyw+3fnv9Hv3Yvfng+mYzem4ahz/8WUgg25wCaq78LlpK4p/y68XoY",
	"cn3olCvrfVNtb1TYNBBe+qFlnsj2zbA2p0lqro1iWeC0CmH9XF5rtTWf5VZWyRb8pX3PFzhjuH1bsfXo",
	"jdue/kHQ5R5oPJr7OHfzo/AYjBD20fu5gc++vOnFsKurGO2bsVbvTh4M53S5AqB9ApgtWZh4XaAuAcDy",
	"P/T83fn1yaG5MCzDQ4hAlEnEQRac1pIGXvT00iitaM6GvwlGh2ROGQdzVaCAdybYTibxlhKq7FOTUdsq",
	"rVqqbEPlLco27N7F8PQYoGpf8r1kG5aXdPiovCNWg6p+pKPwCffR6NNxeR703lTwVljzt71bs9/9+tej",
	"9AXmyT3moANwTBwaoXMrcFEtJObxr4UtDC4r4DEuhgOo2c0vtFWad9jHeK5DQ8MZ3ZcwZcwGzV6we+CQ",
	"nM9mNSfk0T0mUkcA25tREx4+S0ksL3AhtnQZ1Rbkgdb65kEb+Fq3nmqf/DUFPteWGfjedGLVPoaQEWjW",
	"xE+1nTWW0i8s8Dx318nmNHhZkPApZ6Li9XgOVI4m9ATHC53bFjPOQeSMJibbpVLgzbGwwW8xzvGUpESu",
	"RhO6OcDQLKJ2qmKWpqZITxkl1qkYKSA7wxGULDya64JApknwEPqBXx1jeC2U7mEiXC2eWuGP1ciKdEJB",
	"Az8yJtHpq22GMvGbfcRHK2RUyUvHBA22w6s8LznlleOUPcFrhpf5CC2x0IZiUN++br7V0uE33KDnuqX2",
	"wmaY4rlJmNJ82QgmXQgqTotEfblfAHW/u5jPKaCE3VNrPyk5YvPuApd2tt2VCd/eqNSYxZStS+G+a/+H",
	"DWhLdnL5Gpge9crEF49m+McUj7XF7iYe20NscWlSIay8Mcmv2Suskz3PC3k+s//2Mkt2cSnWgPSmCHz1",
	"Zw12bqS41L/6XkMi7jbmbmydLjH4J8v3CHIUa0drVmIG0MyEiDuT671NdcOEcNARMmV5Q+cKU8PXx1y/",
	"ljXF9l4VfnLnDBepstP2lFLehijDn0hWZFXlBpym7N6PbDXRcZKh2JbhMpXyyg4Vv3QZ8QnCOpyfqYO9",
	"tBfXoNZox56ulIWurNOCEjlCVc5I+aPOXj5EH4RJvxCm9sQAfcjMDyajQv2wMD/o3BG9F5VH6/kPh+/3",
	"h3+/nUySv774YTJJ3otscRt0PJ3QmClZ0Cc8C2xbQ406uk5vH5a4kVbgM4M8xURpQ6bCQ+/kPjPVhe3s",
	"/v7RDvIQyPFrg99qsqb0kE21VxtuQr7WOqW+5mN8zcf4E+ZjtA7UdqkZ7e6PW2WoIyUYpz1Yg2talWEI",
	"63Ilo/D8qpZj6AKsnWG42OUWryn4cb8AuQDu17dACyzQFIAiN4C351PGUsDU+EWnkH5OFdkjV83FjKQN",
	"3TxPV1Xdvo5kt9bm2XVutUOVqt5Pr+re6rZCs2HSTTvu3Wp87t4fdYR7aPGPpc3h8Xf/HovaxveLEnQ9",
	"fuxKIKrnIam2PfRIb9SBv6SAOjbYcgt2uFoKIL7coFGQ1sIGdLCZkTpeQzNzq+0z4cKW9GVLIN5F8PAW",
	"hCpc+cV6hCkY4NNU4ADX7+76p8UNIm3jXG5Ka7nWpLg2tUXLTxu5P/pNMIqeM+tqe9ERNvvYnMqVaHEX",
	"O7oSuse8iCivghZAkRLoHvEQEWKtHdxN7Wcvxtble+houN0JaA3SxXJwurVMbnDkh8HmwlA+LberQ422",
	"rvnUrnAE4SU/bRUnv2J8EA+x+Wj2aEZCgbfxuv7aVEISPkn0/Ob69fD7F4jxZmk8bxKdBEXSTgyrds5y",
	"2kwHniEYdK2p5Xfna6mvZYZWe91zzoo8vGq1gmcC6RYDz5gGonUh7KpY23LqwEmMTl+N0Ctj42tNZRJx",
	"xuQkCuvDLIG1U+fAbRCQLis5Qv/JCm0mGGCMDzhTSv0MZyQlmCMWS5xW5d6xtot/B85cOYS97775Rm8f",
	"NpIkJpntYLK4Qn2+Odh7oewUWZBkLEDO1X8kie9WaGpdA6gMEx+h05m+qi4xNjAu4PpitHWr1ql4YIUw",
	"BV44Y7cQwNdii93ruoaPvlFdNLedw22bZx1qFL2pce0tkOAbEOWZ63BQhevZtDLJ50ReKjDCstirpo3R",
	"GyLrwWS2sOE2vjnnkbPJmzMyd/mVVV2ijsxx93mzklkNVSu82Y6D0srUJSzJOn3EfFVAF8IrEL0W3lai",
	"bQl8a9ZBl5dx3YsR/mobEZe9y5bbnQ9N3FFfqEU8CynzntRD0U/X1xc96Ued/fArOOpXRzFGy3omzIM0",
	"9qJVMs+ucdKrGV+jQRGwBO45Vr1XbD6L+nib+hzxYJtZuaIxWkOXJh4xtHheSuKby7e2BCnLQCA8k9aS",
	"VwJcZzGgU6lzk80NHKCPBWiXOMcZ6KdERBEvEBaHaBKNFQ2OJRs7t9QPuvW/69Zd/LOTwsvte3qidhQZ",
	"mnntcyW7vA4TegaiddvSkcDReqmgLK5hsy8CRS9QjuO7XhcXXQkqnWi5KNK0CvesLjROZ++YvDC2Qutq",
	"wwU51IXuM7/PsxH6VVlByoZS347Se7wSz4zyYBZKBMqLNFWiXZd/Mu8E1Xq9U19qnfQLOTg1xUd0jdnu",
	"1FkzZzRoLkaP2vOKQOGnHEf90RhL/WTHcyjt8/5HSRw9nxy50kxji3ykdt9A1K2fXGUZlrkZ2PBoRkDw",
	"18ho46I8qtviXY/NgJnK3BzmREi+GqFrZZQrFXsKJp6mdtJUR1NStrz5PD8+LQcbKLadMjpX/7UqEONZ",
	"eQui2pqBhH+X2Ydnrns3ZP37SF+OXZnorjUh+D5DsgJ2l0STSm1ebyZbgHrysq6Kiofbr9OYMZLZIt9t",
	"/tJrxaVNEYht/rKisBNxg2ht1cqexaa2B3MQCT1bX3ujghKZjoG8EVZQuaOmWPOAmwk8bVCPXPPRVcvo",
	"h5AK5uAA+j227lH0541DhXe+Gn7gYeh2k7fR9q42KUQ6Z2/PWALp1zAVL0zl7K15IAQlnMxM1Utb0QPT",
	"0I2+bvxu4zMD5bBT0HVpzIQdNClIAjHmJ1Z/r2txSis+HI9TFuN0wYQ8/HZvb3+cgeQkbkesaOuovJ/2",
	"gSlXbGdzrqQTdeR1JtTR6YtezhalJZ3pNNQ/QbFa7+q7HShcflOKcFl0yry6mqaKkATRT1xUWc9a+V3g",
	"JQwsB7MmntA9DLS6RB23bY0EC7jtKWWySnfa8YakamwK1dfyXoL1St0zGGXVkjUXlSbzSMdX3GPhXtzo",
	"fzuZQAq7zGXft9Xdt5lvvqbu/xES8LHQEs5WVaxFl+BSg0TemwDlBZgpV2Wu/tBF86ER92jvJeBkyGi6",
	"6vlMwGdfkJ1hXXTGBs3cwUpUj7va67JGiTTG55iS303iSIwlzBlXfz4XMcvNrwJSiOULR8xBKuonhm10",
	"U/Cphnsa8j4f+dE9WCJ2r1850eFT5veBUiwmOlhkrOaaRLZ8dFfRS92rO4qLIpbjjwU4JOppNUut4uGM",
	"r+yZ8MKtqhvSKoqrn6f7Ast44UWylapsmAZm+nWDBvNgHSfJhp8bl6mVg745jpNE5zflqdFQOGRsqY9S",
	"vVZEhcCwO/kI/c+r83fogmmElG9gt3prQgyDaiK8lLKZJMoMtECNWnKB5ev8tE29vvaA89qHvBG3Tbd/",
	"x/so0PdRH/AWPB4TmsCn0W+iH1U5AXiUApeXNsY+786SaS9pUS8L1wiJ0O4wNXY4PqHoYrsuVldJWOl4",
	"vVq3ZwDgJXBlwxfC+qTK6rNTmDFuJyZ0PkKv9VE/XB96+0w8q8fUPsue1WNqny2edcbUTibJ37rDaHPg",
	"MVDZWdum+q6wZlZkwhY4mc+VVhDCpJFIxkxbQp+02dp+X9lO4ZwAN6K3TbV11IXK7Sbiqk3WDiS2X1s0",
	"41hQsACJTuLp5w3shKUauLOJN2NnGwOKt2hXhEEtlailZoRi+0OG89xeuR9f3HTGJYSfhTBJB51hPB0J",
	"CaUZ2NVxjZXo9P7Orp1WwUPJGFfGeKqp60qe93roowMTm7T7dXBtCIbqwOLGGbuR+HC7xm5p083aZK6w",
	"TYtrV6cNs8Hx93V1SHQjxFWrETqn6cq8LqZ/zYEjxxJ0RJThm1vXJqkETag6iRJkhM5PlXoQDMst5cIU",
	"5D0ALfNEdFcF9xOw+jJ3oovfrzFRB/5WBFYc4qMb3rkiRiuRBadWPVKAxzh1oW8Jo8/cjSoyXnNPSf+a",
	"uvBlUxfiYHTRVTGfm3cwte/Gbk7sAnI0/kxE3wDtIWIjeYxHsccLsV/zJR41X6LjMcI+2q+fQ6rw6Eyt",
	"rjcdOh4AzHC8IBQ6p7pfrBoTqI22zvSJrnpacGX12ro36NQCZEiACARZLrVfgoMpclKPM11ikuqXT9ER",
	"ujSvEMYp5valVxsrIlzAfAJoWijOA6ZcilLdOUkAEbkhn3Vd0YUKeehcP+V3iCbRVaHfPptEyhz0VvrF",
	"yUbkEA8xTYadBU57pK2U7yFqNtHzBcRrksF/MXcX5lzGb5nRUdtlhtHvSpCX3gkurDDUSD09enfkntI6",
	"ujw5Gr89Pz66Pj1/N0D3mhjUj/XEOIUwQnWQKUcsBkwNH3Y9a28A55hLEhcp5kgQCTrEkdh3MzEHPDDv",
	"SBkjFh3psEA8fgf3//2fjN8N0EmhBNT4AnPi1JKC4mxK5gUrBHo5jBeY41gH07i1NkIh0fNJ9ObsehIN",
	"0CS6uT6eROHI85tWunnz3r2SevZNMsOucSGZOihxmRuvFTKahLLqpTIF5rYEi605oSBnRShMe2Nh/sa7",
	"auYwcfmG4xj8lNe1+q5rp5Qyj7jW9SmJsEXmofjGB6/wtr7Nj/XCIMNEmSQScPYfs5TMFzKW6YiwyDkL",
	"tXn8Wn9Bx+qgshRdA86iQVTw1N6UqKNd691yeb6vD3H7PNTthRWONk1AJ6+C4nLGaaMrJkBmg6tnKYDU",
	"rAmSubuwNI5UuQDC0T3jd4oUhKn2kZIYqIDqejY6ynG8AHQw2mst5v7+foT15xHj87HtK8ZvT49P3l2d",
	"DA9Ge6OFzFKzYVJ7fxpIOro4jQbR0ilz0XIfp/kC79uqFxTnJDqMXo72RvvWU6YJTnG68XJ/7D+Pb1JN",
	"nMzWLiIWyqc9NtfuuOez6iU7P03Kzp09o/KB+B+ZeffIC5X3AhzGv1kJauh04+npnO+hTte2Qpep8yLM",
	"4TzY238qQEKITtRWfrO392gwlOmWrQl/xAkq4VGT7j/BpDcUF3KhLxrsUl8+wayvGZ+SJAFqpvz7E0xZ",
	"r2ak5z14inmvGUNnmK7c1upsnm+fBMtXhsfe0FKxNA5qPNfuuk7uE92qZpuZ1PgPxWQfdLw8yJBLHydG",
	"jpdpCp0nsM2r3oBcx6iqiF3t2lp/27WZVyoLeG5MP6JGsMkEVoqUz4v5nGrgbVDTO1pQ8rGAU+O10WzN",
	"+KZqjG3vH8PYzn/+k7GXb55gyndMvmYFTb4ylt6MxWpzlouMXYprJzt5A9JmEthc2MS949ql7rwB6bJr",
	"7VuwW/IN+1Ks4Q31yUXTTfw4rOOhHWRV1lTV6cKo8TxdOa1OTajmDeYWr5v3S/Ini/1OZnRgzmjzSCEv",
	"GvYfxa+eiHmgins8iTr0T6EIeTzDnOW1DKLyX+VYxuHYVhe36uVpv9rEJXS3Wmr+blzCVyU0hI/FEW63",
	"McuGeuq/bbdrtcCXXkbZ0/GGr8bXv4R2hP506hHq0o9KXjeI8iKg6NzY8pTbMrJLE6f1yKysKi355Lxs",
	"NybylXX9SRSlf1K1pSpr09+bS1GoTuJ6N267+OKXOVvteZ7YbdsBwFd37b+wu/bP6KjtVBhaHGUTw9nk",
	"mX0Dclue8wZkiOFspV10z/eo7tcv68voxY2++li/WhH/CKagw9R1yJg+jubCe2yywk2/9pMc9pQLxGhT",
	"/9cBN/YQWlWn7Z+sj9B9xv3B2sA/3D78/wAAAP//QS/aCQWuAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
