// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PcNrbgX8FybpXtmX5IcpLKqOpWriLLjjaWpdUjqXvd2ms0ebobEQnQANhyJ6Wq",
	"/Q/7D/eXbOFFgiTYzW7LmqmJZz7EauJxcHBwcN74I4pZljMKVIro8I9IxAvIsP7n0VSwtJBwgeVC/Z2A",
	"iDnJJWE0OowuIecgVDeEKcK2LZqRFFCO5WIUDaKcsxy4JKDHy4PjXC+g6q2aIMkQNuMwiuQCkFgJCdkI",
	"vWMSkFxgiTBdIfhEhCR0bprekzRFU0BsCfyeEymBKgjgE87yFKLDaLzEfJyy+Rjn+Shl82gQyVWuvgjJ",
	"CZ1HDw/lL2z6G8QyehhER3l+rX8Lga1aIzbTMOI8T0mM1Vc9Ly2y6PC9Qa6AaBB9LHCSgoxum/MOok9D",
	"1Xy4xJziTOHqvZv3uOxuf/hfbhQDm5vymFEJVCowcZqez6LD939E/8ZhFh1GfxlXOzy22zt+TVJwnR4G",
	"69teQoolWRo6UI05fCwIh0QBqjf1toW5BnwndPkL5oYKajQB1QecJES1xelFrUljlwaNjTihS8IZzYBK",
	"tMSc4GkK6A5WwyVOC0VRhIsBIlTBBQlKCjUM4gWVJIMRUvt4ByuEaYJMD8DxAmWFkIqcpiDvASja1w0O",
	"vn2J4gXmOJbAxShqLbuDhBwaLjhbkgT4VQ5x/70K4FHtQh2RuCLUDWPpZg+DSNFax3GsJkSqVYmN/f/3",
	"f/5vHQcoZXQ+QEJiLtE9kQuEUQpSAkeMI1pkU+ADjbuYUYkJRZSh+wWRIHIcw6jXKfwjYhR6IOo0w3Po",
	"QvcmKj+lKaHdvW8fbtfv7ZXEshBhZmG+KVaBkSB0ntZxbNlcAktiUOK4xwWHHFsmcaVQbP55WVBq/nXC",
	"OePRILqhd5Td02gQKY6RgoSkP6Opr8Cfs/XRA6L1rYKq9cmB2fpQwd365C2kjuhfWFoYyq2OTx3dr2BG",
	"KAiENfUmaKl7oEJAgqYrfV3VuXX9KIUPxg0lHwsw58HyfH9cRfuEhq6CNn37/FNPdvuZNG9Q0iLYEN6a",
	"LKi+dLMi0V79WyKkpl+PbG1jtUYiIRM9eE9jD6uzjjnHq43803Qz9LH+lD3Klr9r7XVgP9V2zoADjSEk",
	"JNlPSqgxZzxP2QoSdH58OlQ4SgmmEhG1i4pjquM1w7FEUxzfqYtq7dwhWvLh2cCyxFWRZZiverKuNPWR",
	"KLrZ1k+AU7lYRYPoFcw5TiAJsKqt2VMd2mqOzibe5J1tApyp3qAE92EQHSuCmalmcEXmitldwscChGyj",
	"rbMp4p7cjLj9caa2Hgkyp5CguOqLZpxlGsvHR22qxTn5BbjQMzYBOLo4td9QYtmhJiXzGyTInEpD3kRU",
	"YNkraabOjKGaEboCrjoisWBFqq/yJXC1lJjNKfm9HE04Mk+xVMsiVAKnODWSlZEDMrxCHNS4qKDeCLqJ",
	"GKEzxgEROmOHaCFlLg7H4zmRo7vvxYgwxVayghK5Git5gpNpIRkX4wSWkI4FmQ8xj5V0EcuCwxjnZKiB",
	"pXpjR1nyFw6CFTwGETzKd4QmbVz+TGiCiNov09IKiiXK3Dm9PLm6Rm4Cg1aDQW/TK2QqRBA6A25aljsN",
	"NMkZoVL/EadECbaimGZECkcvCs8jdIwpZVouK/IES0hG6JSiY5xBeowFfHFUKuyJoUJZGJkZSJxgiTfd",
	"C+caR2cgseol7MW0rkfn6bKSXiTKK2K3YUz3Jn/1zpslFW+RFvIQy10PbovcfuU4z0HdBaygCcLqFuPD",
	"mIPaY3R8dTlAGUsghUSx4LtiCpyCBIEI03uLczLyeIgYLfdHa0Focxb4lBNuhDGIGU1E6GrT/Y1KVTKN",
	"JU5JQuRKczRNwNXEapoZ4xmW0WFEqHx5UFGN4hRz4Apb8ElyvE4hLIWNFsXVhYmWpqgGRlgaWgfhrnaF",
	"XmNWcDjWDFfhOWd5keqfpiv969HFKRL6ACvc6/Zq5YqxkSwrpNI+A3qhoaPgTaEUrikW8N03Q6AxSyBB",
	"Fydn1b9/Pr76y/6eAmeEzrCMF5aTK2oblfcHgTRBhCLs08O6S8gwqdqWTFcSQudYX0v8XVBEOqWJITIN",
	"Ey9pwvQxHF9zzo8FTsmMQKIl6CC/KEiA996cvnqCffKAEHgeEoBv9O8a62oZ+jIALRLfwQqZXt76rSpA",
	"hCjqN3pNWt5IwGrJm2XTJ0BMgxM6aq4Rx3asr0OIrwgK5zlnS5yOE6AEp+MZJmnBAYlSIi1X6dkXRAfe",
	"EZlVVkPR5nhe0/AZtUO2ZbRBhTjElKhf4rzX6VLsVbO5ADKOy29G8lY7y/yTNkI/K+kUxV5DDuhIow6S",
	"AXoFlKj/Kgy9xiQ1QPVS18rJg2qaTw3eEoI0UA7UvcBq+xKQmKRCXyCMAsLqyEm33XHBuRaIpNpTJ7wq",
	"or70WFp9a1Ms5DXHVOiZrkmX2Uu1Q5JkYGYqQZNlX0iMmKbgsmQoGcKUyQXw2m4reWyoxgoLRkLxizYU",
	"PxUZpogDTjQ12XaImDOhxEyHHTxlhbQQl+AFGRqb6uOevAEK5p4Or37kJJnRvGxpmEodG/dYaM6n7qwE",
	"FbmZ1r/Xv/smeK9zwCKoqaDnU05g9gKZFpXo4OZ8JnqttKfQ50Z1Qp4bqWc3Yz5tnAA9QgnBIERyJQKq",
	"/V97WDZbOWo4GmiiZDN0zZWm9RqnAgbIaq++cq6+R4NIN9haHW9AZ8dq/OqGbvxc06Rr2GzTo3WsVFRH",
	"fMXGW43jdNEgur44+wW4ljGMQu8+GB6o16wYYLtpHIMQZJpC8w/HUy4wF7rp1YrG+h+/KDlXtWBpygp5",
	"Si84m3MQavNvlDZmjbY5xK7pWZFKkqdwfk+BCw3XksTwCpQiRoRSK1SnfhtxQjlL0wyotPept97Wt/py",
	"O69kb4jONiUuO1uUSO5sUQfnEnImiGR8FUS9wnjnh9b++B/LvXqdAki3C/qP0K6Z3fD2zvzg76D5pe8+",
	"GjKfkXnT5NrPsPuGyED3TV6Mn0vp/wpiDnIHF8gOs/4kZR7qpnGQF25XzhhVG932ftXv68w02+x3rUwt",
	"DNlOm0VXf/Sg3X29K7S9ErNKzujJp1zRUljQ4YwiKBsgc1/qq06NnRSpNiKRDMRoQtUibQsi0Ie/Ivv/",
	"D4doiM4IVdrrIfrw1w8osxrh3vDbv4/QEP3ECt76dPBSfXqFVwppZ4zKRb3F/vDlvmoR/LR/4HX+FeCu",
	"Ofp3owm9KvKccaVmqI3EkikghqrhYam0KunbGM6ew2g+GuhhCEULBXI5HiyBr/RvL9S8H4YfDtElpvOq",
	"197w+w8acfsH6OhM7f336OjMtB58OETaVeEa7w/2D2xrIbUUvH8gFyjTODR9xh8O0ZWEvAJr7PoYYJo9",
	"rowHr76W7yuUqHv5e6/LhJ6YKASFObQ3/H6w/93w4KXd0qAoc1wIyTLDWE7pjK0zhzSlKW0tMjbfBMV6",
	"IGQPmN2A4JRNddcbhFBDjFpR1IJn3e7fEmIM4G3gzO91E3i+WAkS49Qb76uV+6uV+6uVe1wJIP21G9tn",
	"B/v1bec5brnm237jsI2qoc76rvP1PnKtKyWr8O1vgkqseiAxUVIYul+QeKFtH7on6uWKV9PoyJUAH31X",
	"zuLaIKdJlwpqeHRP5e23Z+EgkodBtze+0gFtk9LRrQ9ZA67dnPNN9bjD9lP6nNV+eQgtF9+Lruo+19Ct",
	"JkwDRz8L7f5tRCQEXNJ1MiX2Kl1Lpv5tZ8wtjvNpI4QfAfEoBon1Dvkmvjdi1cjhXYg89uxnlRXB4Eud",
	"pxmZt9HGgSbAIem8hi9tA3fxdo67yapcn2ftIgVLOyUM+9kXNKyxRP8cM0ohtnaFcrPb6xZGWD99FWZE",
	"9jM6feWbrBozhAnD9Dzzro4GvZeyXjmLY9SOtSm4rfvh32uhjjGm+rYUxlpMKJEEp+R3Y9YsY1aBZ4Ti",
	"dFDCLJnrNkAg467twsk5TVfRoeQFNEizsaqBh8DurfT15jYi3GBW7sSOpJK6tl3aw1t7KDGfg+x3bfqg",
	"XOt+YWOfGbLfkrxx2my8dCaZwyLUDK2lZSAXLKkfKd8EdkNBG3y0gSuWjK8uQfQONF4HsTfyumb1WUss",
	"nKp7kBO5Ol5AfNfFkLrbNk9vnWUR1wPFqgvKgasTYXziO94Bw+AdUGk8zTkNRJ/B+rsXvxvv7xxpgxV5",
	"C2RWVOciN2+ocNq/b2MtTXzb0GFoAdVM69r4MHS3K6HrblLB3UZrp03eCiddJNo6u3lDg9ezJErrkKvd",
	"iUYRwtYiTkXeWrypgN4g3KjWJa7a9yPJlCSY5W7tjcGXumclo/ZznO10qmzkstkiJ1rLPPscPO98MNvA",
	"9D6anReAZ0wv6Tt8PHc6io1j0bGkrpO14Qy3j2917N6SGcSrOIWdhNnU9X4ENaBp9KoGf6w7oLHW3dh/",
	"aJAu8vJzl0IYa/N541aye1z3ddR/2ZLQGlA3SaXxuQZF4HsItA3NakR3LsJBef5XZD5NreBm5EF0flWq",
	"AZ2yRxZ0+1/XBjGx4MZYwtHN5dvNipMZt5swzsVOR+j8qvcSfqkrfm4ZwXOhv7wi885wuER/a45lTO1I",
	"LPDBt98d4r3RaPSiL2rqk3YjqvQfboWu0tq66aKP86IfO6jD4S6thIi7z+mfQcb4avcRmmE/eRGVg1ro",
	"+qJ2vXNP1Lx7BtnGlt1OMfgVc3vQjzmRJMbpzskGIUD9XIb212ry0FcPoNBnB2Tomx8s4dmBO9hSgynh",
	"Nb6UytbUL8kntw7dndJ8Gk7kVnijMQx1A2K+7wBD0Icdml6wNGRg1eFgDhuxJMvKtGNtGv1hqVusglHK",
	"9Stra1uFDvPqCYe934zt23CtgPlJgVY7g9ZrbnfEBnz3x0HDbx7CgknyTjpMbeajjlwlitHWPf6N+AEs",
	"48UFlhI4DdqS3c7qhii3LWuLaZmfjc/XwVFQIvUVPTBJr4zr/yopURSzGfk0QCajZwFpOhRylQKap2zq",
	"JtPw69nxHBMqpAtsTFcoZTgBM4WGKcOf3gKdy0V0ePDtd4PIDhEdRv/7/d7w73j4+9Hwvw4nk+F/jyb6",
	"f+8nk9v/MZkMJ5O/TiY/3P7t+X/0a/fih+eTyei9aRj6/G+h23xzAp/x212wlMQ9L58br4ch14fOe2W9",
	"YaltSgrL9cLLHbTME9m+Gda6MEmNzyeWBU6r+NPP5bVW1PJZbqVSbMFf2k66wBnDbVfD1qM3XDX9I5jL",
	"PdB4NM4057ZReAyG9/ro/dyoZf++6cWwKz+KNqxYlXUn84OzmFwB0D7Rx5YsTLAtUBe9b/kfev7u/Prk",
	"0Hj7ytgOIhBlEnGQBae1iP8XPU0sSiqas+FvgtEhmVPGwdj5FfBOf9pJn93yhir71O6obYVWfatsQ+Ut",
	"yjbs3gXg9Bigal/yvWQblpd0GJi8I1aDqn6ko/AJ99Ho03F5HvTeVPBWWPO3vVuy391361H6AvPkHnPQ",
	"0TMmiIzQub1wUS2e5fF9uhYGF9L/GF7dAGp2M+pslaMdNhCe67jOcDr2JUwZsxGvF+weOCTns1nNgnh0",
	"j4nU4bvWrWliu2cpieUFLsSW9p7agjzQWt88aANf69pT7ZO/psDn2jID35sWqNrHEDICzZr4qbazxlL6",
	"xfSd584XbE6Dl8IIn3ImKl6P50DlaEJPcLzQiWkx4xxEzmhiUlUqAd4cCxu5FuMcT0lK5Go0oZujA80i",
	"aqcqZmlqKuyUIV6dgpECsjOWQN2FR3Ndzcc0CR5CP2qrYwyvhZI9THiqxVMrdrEaWZFOyOP/I2MSnb7a",
	"ZigTfNnn+mjFe6r70jFBg+3wKs9LTnnlOGVP8JqxYT5CSyy0oRjUt6+bb7Vk+A3u71y31CbUDFM8N9lO",
	"mi+bi0lXcYrTIlFf7hdA3e8uYHMKKGH31OpP6h6xSXMBj5ttd2VirzcKNWYxZevyct+1/8MGtCU72WsN",
	"TI/q7/CvRzP8Y16PtcXudj22h9jC41EhrHR35NfsFdaZmueFPJ/Zf3tpIbuYFGtAelMEvvqzBjs38lPq",
	"X32rIRF3GxMvts51GPyTJWsEOYrVozUrMQNoZkLEnUnU3qY0YUI46PCWsjahM4Wp4etjrl/Lmkp5rwo/",
	"M3OGi1TpaXtKKG9DlOFPJCuyquwCTlN274elmtA2yVBsa2iZMndlh4pfunT2BGEdi8/UwV5arzOoNdqx",
	"pyuloSvttKBEjlCV8FH+qFOPD9EHYXInhCkcMUAfMvODSYdQPyzMDzrxQ+9FZdF6/sPh+/3h328nk+Sv",
	"L36YTJL3IlvcBg1PJzRm6i7oE1sFtq2hRh0ap7cPS9zICfCZQZ5ioqQhU56hd2aemerCdnZ//2gHeQgk",
	"6LXBbzVZUzfI5smrDTfxWmuNUl+TKb4mU/wJkylaB2q7vIp298ctEdSRz4vTHqzBNa1qKIRluZJReHZV",
	"yzF09dTOGFrsEoPXVOu4X4BcAPeLU6AFFmgKQJEbwNvzKWMpYGrsolNIP6cE7JErxWJG0opunqerquhe",
	"R6Zaa/PsOrfaoUpU7ydXdW91W6DZMOmmHfe8Gp+790cdsRr6+sfSJuD4u3+PRW3j+4X4uR4/dmX/1JOI",
	"VNsecqQ36sBfUkAcG2y5BTu4lgKILzdoFKS1sAIdbGZuHa+hmbnV9plwMUfa2RIIVhE8vAWh8lR+pR1h",
	"sv19mgoc4Lrvrn9O2yDSOs7lppyUa02Ka/NS9P1pw+5HvwlG0XNmTW0vOmJeH5tTufoqzrGjy5h7zIuI",
	"0hW0AIrUhe4RDxEh1trB3dR+9mJsXbaHjobbnYDWIF0sx1x9OzFSzzW5qaqTT8vt0k6jrQs2tcsTQXjJ",
	"T1uCyS/3HsRDbD6aPZqRUNRsvK6/VpWQhE8SPb+5fj38/gVivFnXzptEZzCRtBPDqp3TnDbTgacIBk1r",
	"avndyVbqa5le1V73nLMiD69areCZQLrFwFOmgWhZCLsS1LYWOnASo9NXI/TK6PhaUplEnDE5icLyMEtg",
	"7dQ5cBsEpGtCjtB/skKrCQYYYwPOlFA/wxlJCeaIxRKnVa12rPXi34EzV8tg77tvvtHbh81NEpPMdjAp",
	"WKE+3xzsvVB6iixIMhYg5+o/ksR3KzS1pgFUxniP0OlMu6pLjA2MCbi+GK3dqnUqHlghTIEXTrctBPC1",
	"2GL3uijho29UF81tZ3Db5k2GGkVvalx7yCP4gEN55joMVOFiNK008DmRlwqM8F3slcLG6A2R9WAyW5Vw",
	"G9ucs8jZzMsZmbvkyKqoUEfat/u8WcishqpVzWzHQWlh6hKWZJ08Yr4qoAvhVXdeC28rS7YEvjXroMvK",
	"uO65B3+1jYjL3jXH7c6HJu4oDtQinoWUeU/qoein6+uLnvSjzn74CRv1q6MYI2U9E+Y1GetolczTa9zt",
	"1Yyv0aAIWAL3DKveEzSfRX28TX2OeLBNi1zRGK2hSxOPGFo8L2/im8u3tn4oy0AgPJNWk1cXuE5BQKdS",
	"JxYbDxygjwVokzjHGeh3QEQRLxAWh2gSjRUNjiUbO7PUD7r1v+vWXfyzk8LL7Xt6onYUGZp57Vsjuzzt",
	"EnrDoeVt6ci+aD0zUFbGsKkTgYoVKMfxXS/HRVd2SSdaLoo0rcI9K4fG6ewdkxdGV2i5NlyQQ/3Sfeb3",
	"eTZCvyotSOlQ6ttReo9X4pkRHsxCiUB5kabqate1m8wjP7Ve79SXWif9vA1OTeUQXSC2O+/VzBkNmovR",
	"o/Z0ESj8lOOoPxpjqZ/seA6lfR7vKImj53shV5ppbJFM1O4biLr1M6MswzKegQ0vXgQu/hoZbVyUR3Vb",
	"PMqxGTBTVpvDnAjJVyN0rZRyJWJPwcTT1E6a6mjqwZaez/Pj03KwgWLbKaNz9V8rAjGelV4Q1dYMJHxf",
	"Zh+eue7Rj/WPG305dmWiu9aE4PsMyV6wuySaVGLzejXZAtSTl3WVQzzcfp1GjZHMVuhu85deKy51ikBs",
	"85e9CjsRN4jWlpzsWSlqezAHkdCz9dU3KiiR6RjIG2EFlTtKijULuJnAkwb1yDUbXbWMfgipYA4OoB9T",
	"6x5Ff944VHjnq+EHHoZuN1kbbe9qk0Kkc/b2jCWQfg1T8cJUzt6a1z1QwsnMlKy05TgwDXn0deN3G98I",
	"KIedgi4qYybsoElBEogxP7Hye12KU1Lx4XicshinCybk4bd7e/vjDCQncTtiRWtHpX/aB6ZcsZ3NmZJO",
	"1JHXmVBHpy96GVuUlHSm01D/BJVmPdd3O1C4/KYE4bJilHkyNU0VIQmi36eoUpa18LvASxhYDmZVPKF7",
	"GGh1fTlu25obLGC2p5TJKt1pRw9J1dhUma/lvQSLjbo3LMqSI2sclSbzSMdX3GPhnsvo751MIIVd5rKP",
	"0+ru28w3X1O0/wgJ+FjoG86WRKxFl+BSgkReQf/SAWZqTRnXH7povhLiXty9BJwMGU1XPWv8f7aD7Azr",
	"ijE2aOYOVqJ6mdW6yxr1zRifY0p+N4kjMZYwZ1z9+VzELDe/Ckghli8cMQepqN81bKObgu8s3NOQ9fnI",
	"j+7BErF7/USJDp8yvw+UYDHRwSJjNdcksrWfuypW6l7dUVwUsRx/LMAhUU+rWWoVD2dsZc+EF25VeUir",
	"KK5+lu4LLOOFF8lWirJhGpjppwkazIN1nCQbfm5MpvYe9NVxnCQ6vylPjYTCIWNLfZTqhR4qBIbNyUfo",
	"f16dv0MXTCOkfMC61VsTYhhUE+GlhM0kUWqgBWrUuhdYvs5O25Tra68vr32FG3HbdPtHuI8CfR/19W3B",
	"4zGhCXwa/Sb6UZW7AI9S4PLSxtjn3Vky7SUt6jXdGiER2hymxg7HJxRdbNfF6qobVjper9btKQB4CVzp",
	"8IWwNqmydOwUZozbiQmdj9BrfdQP14fePhPP6jG1z7Jn9ZjaZ4tnnTG1k0nyt+4w2hx4DFR2Fqapvius",
	"mRWZsAVO5nMlFYQwaW4ko6YtoU/abG2/r2yncE6AG9Hbpto66pfK7Sbiqk3WDiS2X1s041hQsACJTuLp",
	"Zw3shKUauLOJN2NnGwOKt2hXhEEtlailZoRi+0OG89y63I8vbjrjEsJvOpikg84wno6EhFIN7Oq4Rkt0",
	"cn9n106t4KFkjCujPNXEdXWf93qlowMTm6T7dXBtCIbqwOLGGbuR+HC7Rm9p083aZK6wTotrrtOG2uD4",
	"+7o6JLoR4qrVCJ3TdGWeBtO/5sCRYwk6Isrwza1rk1QXTag6ibrICJ2fKvEgGJZb3gtTkPcAtMwT0V0V",
	"3E/A6svciS5+v0ZFHfhbEVhxiI9ueKSKGKlEFpxa8UgBHuPUhb4ljD5zHlVkrOaekP41deHLpi7Eweii",
	"q2I+N49YatuN3ZzYBeRo/JmIvgHaQ8RG8hiLYo/nXb/mSzxqvkTHS4J9pF8/h1Th0alaXQ8ydLzel+F4",
	"QSh0TnW/WDUmUBttjekTXbK04ErrtXVv0KkFyJAAEQiyXGq7BAdT5KQeZ7rEJNXPlqIjdGmeEIxTzO0z",
	"rTZWRLiA+QTQtFCcB0y5FCW6c5IAInJDPuu6ogsV8tC5fofvEE2iq0I/XDaJlDrorfSLk43IIR5imgw7",
	"q5P2SFspHzPUbKLn84XXJIP/Ys4X5kzGb5mRUds1gtHv6iIvrRNc2MtQI/X06N2Rewfr6PLkaPz2/Pjo",
	"+vT83QDda2JQP9YT4xTCCNVBphyxGDA1fNj1rD3gm2MuSVykmCNBJOgQR2IfvcQc8MA8AmWUWHSkwwLx",
	"+B3c//d/Mn43QCeFuqDGF5gTJ5YUFGdTMi9YIdDLYbzAHMc6mMattREKiZ5Pojdn15NogCbRzfXxJApH",
	"nt+00s2bfvfq1rMPihl2jQvJ1EGJy9x4LZDRJJRVL5UqMLclWGzNCQU5K0Jh2hur6jceRTOHics3HMfg",
	"p7yulXddOyWUecS1rk9JhC0yD8U3PnhVs7U3P9YLgwwTpZJIwNl/zFIyX8hYpiPCImcs1Orxa/0FHauD",
	"ylJ0DTiLBlHBU+spUUe71rtl8nxfH+L2eajbC3s52jQBnbwKissZo42umACZDa6epQBSsyZI5s5haQyp",
	"cgGEo3vG7xQpCFPtIyUxUAGVezY6ynG8AHQw2mst5v7+foT15xHj87HtK8ZvT49P3l2dDA9Ge6OFzFKz",
	"YVJbfxpIOro4jQbR0glz0XIfp/kC79uqFxTnJDqMXo72RvvWUqYJTnG68XJ/7L9tb1JN3J2tTUQslE97",
	"bNzuuOeb6CU7P03Kzp09o/J19x+ZebTIC5X3AhzGv9kb1NDpxtPTOd9Dna5thS5T50WYw3mwt/9UgIQQ",
	"nait/GZv79FgKNMtWxP+iBNUwqMm3X+CSW8oLuRCOxrsUl8+wayvGZ+SJAFqpvz7E0xZr2ak5z14inmv",
	"GUNnmK7c1upsnm+fBMtXhsfe0FKwNAZqPNfmuk7uE92qZpuZ1PgPxWQfdLw8yJBJH5sH/Ks0hc4T2OZV",
	"b0CuY1RVxK42ba33dm3mlUoDnhvVj6gRbDKBvUXKt8F8TjXwNqhpHS0o+VjAqbHaaLZmbFM1xrb3j2Fs",
	"5z//ydjLN08w5TsmX7OCJl8ZS2/GYqU5y0XGLsW1k528AWkzCWwubOIeYe0Sd96AdNm19iHXLfmGfebV",
	"8Ib65KJpJn4c1vHQDrIqa6rqdGHUeFuunFanJlTzBnOL1837JfmTxX4nMzowZ7R5pJAXDfuP4ldPxDxQ",
	"xT2eRBz6pxCEPJ5hzvJaBlHZr3Is43Bsq4tb9fK0X23iErpbLTV/Ny7hixIawsfiCLfbqGVDPfXfttu1",
	"WuBLL6Xs6XjDV+XrX0I6Qn868Qh1yUclrxtEeREQdG5secptGdmlidN6ZFZWlZZ8cl62GxP5yrr+JILS",
	"P6nYUpW16W/NpShUJ3G9GbddfPHLnK32PE9stu0A4Ku59l/YXPtnNNR2CgwtjrKJ4WyyzL4BuS3PeQMy",
	"xHC2ki6653tU8+uXtWX04kZfbaxftYh/BFPQYeo6ZEwfR+PwHpuscNOv/SSHPeUCMdqU/3XAjT2EVtRp",
	"2yfrI3SfcX+wNvAPtw//PwAA//+3MCgKwq0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
